# Test notebook

The purpose of this notebook is to test an equation and compare them with the baselines: Burton, MBR, and DDM1, 2 and 3. We will also plot each storm and get the metrics for the equation.

The only cell that we have to modify is the following one, where we can change the features, the mode (template or default) and the output directory for the plots.
Raw EQ is the equation that we want to test, the raw version generated from the train_script.py file.

In [2]:
import os

FEATURES = ["Vp", "Np", "Bzsouth", "Bmag", "DST"]
MODE = "template"  # 'template' or 'default'
OUTPUT_DIR = "template_primitive_features"
RAW_EQS = [
    'g = (#3 - -2.152752) * ((((4.7333016 - #2) * #3) - #1) / 501.94562); d = square(1.4046433 - (#1 * 0.015329162))',
    'g = ((#1 + (#3 * (#2 - sqrt(#3)))) * 0.0020573507) * (-1.775414 - #3); d = square((#1 * -0.015831897) + 1.3089455)',
    'g = (#3 - -2.1569605) * (((#2 * #3) + #1) * -0.0018313164); d = square((#1 * -0.015403083) + 1.3434031)',
    'g = (#2 + (#1 * ((#3 * (-0.301232 - ((#1 * 3.5000103e-5) * #2))) - 0.55653155))) * 0.0053468808; d = square((0.015961226 * #1) + -1.2015269)',
    'g = (((#3 * (#2 - sqrt(#4))) + #1) * (1.6439178 + #3)) * -0.0021015273; d = square(-1.2798462 - (#1 * -0.015890777))',
    'g = ((#1 + (#2 * #3)) * 0.0018150203) * (-2.0452397 - #3); d = square((#1 * -0.015376654) - -1.3081883)',
    'g = ((#2 * ((#1 * #3) * 0.00011782655)) + (#3 + 1.3935444)) * (#1 * -0.0016007437); d = square((#1 * -0.016486706) - -1.0748392)',
]

output_folder = OUTPUT_DIR
# Count number of existing subfolders
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

import sympy as sp
from tqdm import tqdm

from sympy.printing import latex

# Internal module imports
import storm_dates
import baseline_models

# from evaluation_engine import UnifiedModel, simulate_storm, compute_features
from evaluation_engine import EquationModel, simulate_storm
from train_script import load_and_preprocess, compute_features

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

In [4]:
raw_data = load_and_preprocess()
data = compute_features(raw_data)

Reading from file ./data/all_timeline/ace_imf_1h_1998.csv
Reading from file ./data/all_timeline/ace_imf_1h_1999.csv
Reading from file ./data/all_timeline/ace_imf_1h_2000.csv
Reading from file ./data/all_timeline/ace_imf_1h_2001.csv
Reading from file ./data/all_timeline/ace_imf_1h_2002.csv
Reading from file ./data/all_timeline/ace_imf_1h_2003.csv
Reading from file ./data/all_timeline/ace_imf_1h_2004.csv
Reading from file ./data/all_timeline/ace_imf_1h_2005.csv
Reading from file ./data/all_timeline/ace_imf_1h_2006.csv
Reading from file ./data/all_timeline/ace_imf_1h_2007.csv
Reading from file ./data/all_timeline/ace_imf_1h_2008.csv
Reading from file ./data/all_timeline/ace_imf_1h_2009.csv
Reading from file ./data/all_timeline/ace_imf_1h_2010.csv
Reading from file ./data/all_timeline/ace_imf_1h_2011.csv
Reading from file ./data/all_timeline/ace_imf_1h_2012.csv
Reading from file ./data/all_timeline/ace_imf_1h_2013.csv
Reading from file ./data/all_timeline/ace_imf_1h_2014.csv
Reading from file ./data/all_timeline/ace_imf_1h_2015.csv
Reading from file ./data/all_timeline/ace_imf_1h_2016.csv
Reading from file ./data/all_timeline/ace_imf_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_1h_2024.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1998.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1999.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2000.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2001.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2002.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2003.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2004.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2005.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2006.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2007.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2008.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2009.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2010.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2011.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2012.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2013.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2014.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2015.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2016.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2024.csv

In [ ]:
def predict_and_plot_storm(model, eqs, start, end, storm_df, storm_id, save_path):
    # 1. Generate Predictions
    y_true = storm_df[start:end]["DST"].values
    colors = ["blue", "yellow", "green", "orange", "purple", "cyan", "magenta"]
    res_eqs = []
    string_title = f"Storm {storm_id} Reconstruction\n"
    metrics_info = []
    
    
    for eq_index, eq in enumerate(eqs):
        res_eq = simulate_storm(model[eq], storm_df)
        res_eq = res_eq[start:end]["DST_pred"].values
        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        metrics_info.append(m_eq)
        string_title += f"Evaluation for Equation {eq_index + 1} ({colors[eq_index]}): ${model[eq].latex_str()}$ \n"
    
        res_eqs.append(res_eq)

    # 2. Calculate Metrics
    
    # 3. Setup Figure (3 Columns)
    fig, axs = plt.subplots(1, 3, figsize=(24, 7), constrained_layout=True)
    fig.suptitle(
        string_title, fontsize=18
    )
    # Column 1: Time Series
    axs[0].plot(
        storm_df[start:end].index,
        y_true,
        color="black",
        label="Observed",
        alpha=0.6,
        linewidth=2,
    )
    
    for eq_index, res_eq in enumerate(res_eqs):
    
        axs[0].plot(
            storm_df[start:end].index,
            res_eqs[eq_index],
            color=colors[eq_index],
            linestyle="--",
            label=f"Equation {eq_index + 1}",
            linewidth=1.5,
        )
    
    axs[0].tick_params(axis='both', which='major', labelsize=14)
    axs[0].tick_params(axis='both', which='minor', labelsize=10)
    axs[0].legend(fontsize = 16)
    axs[0].grid(True)
    axs[0].set_xlim(start, end)
    

    axs[0].xaxis.set_major_locator(MultipleLocator(2))
    
    diffs = []
    
    for eq_index, res_eq in enumerate(res_eqs):
        diff_eq = res_eq - y_true
        diffs.append(diff_eq)

        axs[1].plot(storm_df[start:end].index, diff_eq, color=colors[eq_index], label=f"Equation {eq_index + 1} Error")
    
    axs[1].axhline(0, color="black", linestyle="--")

    title_metrics = (
        f"Error Comparison\n"       
    )
    
    for eq_index, m_eq in enumerate(metrics_info):
        title_metrics += f"Eq {eq_index + 1}: MAE={m_eq['MAE']:.2f}, RMSE={m_eq['RMSE']:.2f}, R²={m_eq['R2']:.3f}, BFE={m_eq['BFE']:.3f}\n"
        
        
    axs[1].set_title(title_metrics, fontsize=18)
    axs[1].set_ylabel("Error (nT)", fontsize=16)
    axs[1].legend(fontsize=16)
    axs[1].grid(True)
    axs[1].set_xlim(start, end)
    axs[1].tick_params(axis='both', which='major', labelsize=14)
    axs[1].tick_params(axis='both', which='minor', labelsize=10)
    
    axs[1].xaxis.set_major_locator(MultipleLocator(2))

    # Column 3: BFE
    baseline_models.plot_evaluation_bfe_multi(
        axs[2],
        y_true,
        res_eqs,
        [f"Equation {i+1}" for i in range(len(eqs))],
        [colors[i] for i in range(len(eqs))],
        fontsize = 16   
    )

    plt.savefig(save_path)
    plt.close()

In [6]:
def save_prediction_data(model, eqs, start, end, storm_df, output_path):
    """
    Generates and saves a CSV with observed and predicted DST and dDST/dt.
    """
    # 1. Observed Data
    # Real dDST is calculated as the difference to the next hour
    real_dst = storm_df[start:end]["DST"].values
    real_ddst = storm_df[start:end]["DST"].diff().shift(-1).values

    # 2. Equation Predictions
    # We need the iterative predictions for DST
    pred_dst_eqs = []
    for eq_index, eq in enumerate(eqs):
        pred_dst_eq = simulate_storm(model[eq], storm_df)
        if model[eq].is_template:
            pred_dst_eq = pred_dst_eq[start:end][
                ["DST_pred", "dDST", "injection_component", "decay_component"]
            ]
        else:
            pred_dst_eq = pred_dst_eq[start:end][["DST_pred", "dDST"]]
        pred_dst_eqs.append(pred_dst_eq)
        
    # 3. Baseline Predictions (Burton & OBM)
    
    # 4. Construct Comprehensive DataFrame

    if model[eq].is_template:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Injection_Component": pred_dst_eq["injection_component"].values,
                "Decay_Component": pred_dst_eq["decay_component"].values,
                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values
            results_df[f"Injection_Component_{eq_index+1}"] = pred_dst_eq["injection_component"].values
            results_df[f"Decay_Component_{eq_index+1}"] = pred_dst_eq["decay_component"].values
        
    else:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values


    results_df.to_csv(output_path)
    return results_df

## Test storms

In [7]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TEST_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)
    
with open(os.path.join(OUTPUT_DIR, 'equation.txt'), 'a') as f:
    f.write(f'Equation: {RAW_EQ}\n')            
    f.write(f'LaTeX: {latex(models[RAW_EQ].latex_str())}\n')

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

IndexError: list index out of range

In [ ]:
storms[0].columns

Index(['Observed_DST', 'Real_dDST_dt', 'Pred_DST_Equation',
       'Pred_dDST_dt_Equation', 'Injection_Component', 'Decay_Component',
       'Pred_DST_Equation_1', 'Pred_dDST_dt_Equation_1',
       'Injection_Component_1', 'Decay_Component_1', 'Pred_DST_Equation_2',
       'Pred_dDST_dt_Equation_2', 'Injection_Component_2', 'Decay_Component_2',
       'Pred_DST_Equation_3', 'Pred_dDST_dt_Equation_3',
       'Injection_Component_3', 'Decay_Component_3', 'Pred_DST_Equation_4',
       'Pred_dDST_dt_Equation_4', 'Injection_Component_4', 'Decay_Component_4',
       'Pred_DST_Equation_5', 'Pred_dDST_dt_Equation_5',
       'Injection_Component_5', 'Decay_Component_5', 'Pred_DST_Equation_6',
       'Pred_dDST_dt_Equation_6', 'Injection_Component_6', 'Decay_Component_6',
       'Pred_DST_Equation_7', 'Pred_dDST_dt_Equation_7',
       'Injection_Component_7', 'Decay_Component_7'],
      dtype='object')

In [ ]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[storm_indices[storm_index], "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]


global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'

for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_CC,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_CC,...,Equation 6_RMSE,Equation 6_MAE,Equation 6_R2,Equation 6_CC,Equation 6_BFE,Equation 7_RMSE,Equation 7_MAE,Equation 7_R2,Equation 7_CC,Equation 7_BFE
54,54,9.745655,6.83855,0.765586,0.923463,12.618396,9.170363,6.306532,0.792444,0.929433,...,9.950981,6.892319,0.755605,0.924818,13.239107,8.673717,6.588866,0.814317,0.928641,11.301985
55,55,15.45666,12.125151,0.802554,0.914472,17.293221,15.477186,12.047038,0.802029,0.914773,...,15.516899,12.059337,0.801012,0.913815,17.1403,16.449289,12.926959,0.77638,0.900502,18.164656
56,56,11.923871,9.441087,0.687895,0.864996,13.776978,11.76299,9.26387,0.69626,0.871547,...,11.595705,9.033693,0.704838,0.869104,13.571008,11.831529,9.30636,0.69271,0.883821,14.710407
57,57,10.548566,8.06729,0.717111,0.885463,10.447585,10.641121,8.014319,0.712125,0.893614,...,10.129202,7.717149,0.739156,0.896014,9.454292,9.834485,7.633421,0.754114,0.906933,9.969161
58,58,9.316351,6.358408,0.790282,0.915747,15.773875,8.454199,5.979033,0.827301,0.919482,...,8.737426,5.972947,0.815536,0.920243,15.027077,8.344028,5.728047,0.831773,0.931581,14.176383
59,59,19.212159,16.20118,0.628309,0.910652,12.301995,18.93238,16.047103,0.639056,0.921116,...,18.755635,15.918559,0.645763,0.916767,12.317915,15.741868,13.450539,0.750459,0.94344,10.585746
60,60,16.652461,13.110027,0.801415,0.960356,20.074287,16.513636,13.513491,0.804712,0.958955,...,15.905531,13.17985,0.81883,0.963424,17.604023,15.842252,12.058539,0.820269,0.957678,20.299388
61,61,11.789867,8.40107,0.917132,0.961177,17.16978,11.88397,8.886693,0.915804,0.96213,...,12.410941,8.671901,0.908172,0.95925,18.248169,10.534158,7.737233,0.933844,0.966963,16.059308
62,62,12.65854,10.555086,0.627468,0.801518,14.578574,12.74353,10.836518,0.622448,0.810219,...,12.239675,10.29346,0.651714,0.826605,13.171476,11.981492,9.955988,0.666252,0.842861,12.976021
63,63,13.332099,8.723691,0.870862,0.962578,20.154227,12.608102,8.299471,0.884507,0.961065,...,12.509199,8.250986,0.886312,0.965227,18.605889,11.964242,8.226228,0.896001,0.961207,16.950241
64,64,10.038285,7.675632,0.805958,0.922071,13.468333,9.427073,7.313159,0.828869,0.923939,...,9.314894,7.211591,0.832917,0.931857,12.45671,9.086525,6.96481,0.841009,0.925621,10.96379
65,65,13.400682,10.464988,0.67628,0.822888,13.184393,14.197179,10.715885,0.636654,0.80923,...,13.389623,10.162231,0.676814,0.82748,12.437488,13.969314,10.625351,0.648224,0.810407,14.931509
66,66,15.869952,11.57582,0.654415,0.877968,23.128865,16.016953,11.754645,0.647983,0.861463,...,16.001343,11.648074,0.648669,0.867084,23.151053,15.963856,12.487348,0.650313,0.842882,20.136221
67,67,9.19151,6.765642,0.849833,0.935067,14.297932,8.376661,6.240317,0.875278,0.943944,...,8.549636,6.332061,0.870074,0.942746,12.204151,9.318691,6.999814,0.845649,0.933852,13.460852
68,68,18.717281,15.040402,0.975709,0.9878,17.225934,19.61423,15.942609,0.973325,0.986747,...,19.17397,15.366333,0.974509,0.987254,18.114822,32.33829,23.7555,0.927491,0.979117,36.142446
69,69,10.617919,8.059353,0.80185,0.911011,12.012459,10.488475,7.994046,0.806652,0.905077,...,10.256102,7.79471,0.815125,0.909927,11.612701,10.819474,8.197625,0.794256,0.899904,12.287483
70,70,17.530878,12.099253,0.823258,0.93829,22.029528,17.810786,12.353312,0.817569,0.93831,...,17.664473,12.197304,0.820554,0.9395,20.835002,17.587122,12.130689,0.822122,0.940172,18.928345
71,71,12.315912,7.994873,0.886795,0.945877,14.043419,12.22843,8.467716,0.888398,0.947306,...,12.392095,8.422394,0.88539,0.945323,14.350788,11.721263,8.023882,0.897463,0.950441,13.734328
72,72,24.356635,13.96298,0.908965,0.954435,26.332983,23.983732,14.017114,0.911731,0.956656,...,25.500731,15.495334,0.900212,0.950355,30.817676,19.379545,13.642932,0.942368,0.973117,24.557822
73,73,7.781718,5.660338,0.895655,0.963514,6.93833,9.818305,7.371346,0.833891,0.963182,...,8.860108,6.609746,0.864731,0.96445,8.113815,10.847307,8.388186,0.797249,0.960936,10.438264
20,Mean,13.52285,9.956041,0.794367,0.917967,15.842555,13.507465,10.068211,0.795852,0.918909,...,13.442708,9.961499,0.800797,0.921062,15.623673,13.611422,10.241416,0.805113,0.922004,16.038718
21,Global,13.840596,9.805113,0.888445,0.944074,25.278208,13.824272,9.902958,0.888708,0.945199,...,13.761436,9.775419,0.889718,0.944764,25.720426,13.927125,9.867401,0.887046,0.943743,32.2498

In [ ]:
print(summary_df.to_latex(index=False, float_format="%.3f").replace("_", " ").replace("Equation ", "Eq ").replace("Storm Index", "Storm"))

\begin{tabular}{llllllllllllllllllllllllllllllllllll}
\toprule
Storm & Eq 1 RMSE & Eq 1 MAE & Eq 1 R2 & Eq 1 CC & Eq 1 BFE & Eq 2 RMSE & Eq 2 MAE & Eq 2 R2 & Eq 2 CC & Eq 2 BFE & Eq 3 RMSE & Eq 3 MAE & Eq 3 R2 & Eq 3 CC & Eq 3 BFE & Eq 4 RMSE & Eq 4 MAE & Eq 4 R2 & Eq 4 CC & Eq 4 BFE & Eq 5 RMSE & Eq 5 MAE & Eq 5 R2 & Eq 5 CC & Eq 5 BFE & Eq 6 RMSE & Eq 6 MAE & Eq 6 R2 & Eq 6 CC & Eq 6 BFE & Eq 7 RMSE & Eq 7 MAE & Eq 7 R2 & Eq 7 CC & Eq 7 BFE \\
\midrule
54 & 9.746 & 6.839 & 0.766 & 0.923 & 12.618 & 9.170 & 6.307 & 0.792 & 0.929 & 12.136 & 9.856 & 6.843 & 0.760 & 0.925 & 13.042 & 8.695 & 6.595 & 0.813 & 0.929 & 11.029 & 9.039 & 6.153 & 0.798 & 0.930 & 12.028 & 9.951 & 6.892 & 0.756 & 0.925 & 13.239 & 8.674 & 6.589 & 0.814 & 0.929 & 11.302 \\
55 & 15.457 & 12.125 & 0.803 & 0.914 & 17.293 & 15.477 & 12.047 & 0.802 & 0.915 & 16.816 & 15.441 & 12.018 & 0.803 & 0.915 & 16.969 & 16.373 & 12.792 & 0.778 & 0.903 & 18.150 & 15.514 & 12.034 & 0.801 & 0.915 & 16.761 & 15.517 & 12.059 & 0.801 & 0.914 & 17.140 & 16.449 & 12.927 & 0.776 & 0.901 & 18.165 \\
56 & 11.924 & 9.441 & 0.688 & 0.865 & 13.777 & 11.763 & 9.264 & 0.696 & 0.872 & 13.862 & 11.754 & 9.165 & 0.697 & 0.868 & 13.684 & 12.344 & 9.641 & 0.666 & 0.880 & 15.320 & 11.675 & 9.185 & 0.701 & 0.873 & 13.812 & 11.596 & 9.034 & 0.705 & 0.869 & 13.571 & 11.832 & 9.306 & 0.693 & 0.884 & 14.710 \\
57 & 10.549 & 8.067 & 0.717 & 0.885 & 10.448 & 10.641 & 8.014 & 0.712 & 0.894 & 9.156 & 10.215 & 7.755 & 0.735 & 0.896 & 9.319 & 10.053 & 7.852 & 0.743 & 0.900 & 10.416 & 10.756 & 8.088 & 0.706 & 0.894 & 9.050 & 10.129 & 7.717 & 0.739 & 0.896 & 9.454 & 9.834 & 7.633 & 0.754 & 0.907 & 9.969 \\
58 & 9.316 & 6.358 & 0.790 & 0.916 & 15.774 & 8.454 & 5.979 & 0.827 & 0.919 & 14.344 & 8.749 & 6.008 & 0.815 & 0.921 & 14.974 & 8.594 & 5.818 & 0.822 & 0.930 & 14.660 & 8.416 & 5.991 & 0.829 & 0.919 & 14.242 & 8.737 & 5.973 & 0.816 & 0.920 & 15.027 & 8.344 & 5.728 & 0.832 & 0.932 & 14.176 \\
59 & 19.212 & 16.201 & 0.628 & 0.911 & 12.302 & 18.932 & 16.047 & 0.639 & 0.921 & 11.733 & 18.954 & 16.054 & 0.638 & 0.915 & 12.257 & 16.777 & 14.235 & 0.717 & 0.937 & 10.676 & 18.906 & 16.055 & 0.640 & 0.923 & 11.683 & 18.756 & 15.919 & 0.646 & 0.917 & 12.318 & 15.742 & 13.451 & 0.750 & 0.943 & 10.586 \\
60 & 16.652 & 13.110 & 0.801 & 0.960 & 20.074 & 16.514 & 13.513 & 0.805 & 0.959 & 18.459 & 15.869 & 13.114 & 0.820 & 0.964 & 17.448 & 15.882 & 12.109 & 0.819 & 0.961 & 20.218 & 16.600 & 13.636 & 0.803 & 0.958 & 18.423 & 15.906 & 13.180 & 0.819 & 0.963 & 17.604 & 15.842 & 12.059 & 0.820 & 0.958 & 20.299 \\
61 & 11.790 & 8.401 & 0.917 & 0.961 & 17.170 & 11.884 & 8.887 & 0.916 & 0.962 & 17.416 & 12.329 & 8.682 & 0.909 & 0.960 & 18.069 & 10.560 & 7.590 & 0.934 & 0.967 & 16.165 & 11.791 & 8.984 & 0.917 & 0.964 & 17.053 & 12.411 & 8.672 & 0.908 & 0.959 & 18.248 & 10.534 & 7.737 & 0.934 & 0.967 & 16.059 \\
62 & 12.659 & 10.555 & 0.627 & 0.802 & 14.579 & 12.744 & 10.837 & 0.622 & 0.810 & 13.081 & 12.294 & 10.326 & 0.649 & 0.822 & 13.216 & 11.927 & 9.866 & 0.669 & 0.835 & 13.424 & 12.822 & 10.947 & 0.618 & 0.812 & 12.960 & 12.240 & 10.293 & 0.652 & 0.827 & 13.171 & 11.981 & 9.956 & 0.666 & 0.843 & 12.976 \\
63 & 13.332 & 8.724 & 0.871 & 0.963 & 20.154 & 12.608 & 8.299 & 0.885 & 0.961 & 18.443 & 12.574 & 8.374 & 0.885 & 0.965 & 18.675 & 11.698 & 7.691 & 0.901 & 0.968 & 17.293 & 12.693 & 8.308 & 0.883 & 0.960 & 18.477 & 12.509 & 8.251 & 0.886 & 0.965 & 18.606 & 11.964 & 8.226 & 0.896 & 0.961 & 16.950 \\
64 & 10.038 & 7.676 & 0.806 & 0.922 & 13.468 & 9.427 & 7.313 & 0.829 & 0.924 & 12.233 & 9.387 & 7.269 & 0.830 & 0.930 & 12.462 & 9.156 & 7.029 & 0.839 & 0.926 & 11.212 & 9.368 & 7.271 & 0.831 & 0.924 & 12.103 & 9.315 & 7.212 & 0.833 & 0.932 & 12.457 & 9.087 & 6.965 & 0.841 & 0.926 & 10.964 \\
65 & 13.401 & 10.465 & 0.676 & 0.823 & 13.184 & 14.197 & 10.716 & 0.637 & 0.809 & 12.369 & 13.374 & 10.216 & 0.678 & 0.827 & 12.456 & 13.843 & 10.913 & 0.655 & 0.814 & 16.027 & 14.477 & 10.818 & 0.622 & 0.806 & 12.146 & 13.390 & 10.162 & 0.677 & 0.827 & 12.437 & 13.969 & 10.625 & 0.648 & 0.810 & 14.932 \\
66 & 15.870 & 11.576 & 0.654 & 0.878 & 23.129 & 16.017 & 11.755 & 0.648 & 0.861 & 22.630 & 15.824 & 11.495 & 0.656 & 0.872 & 22.954 & 15.174 & 11.711 & 0.684 & 0.867 & 19.782 & 16.134 & 11.870 & 0.643 & 0.856 & 22.638 & 16.001 & 11.648 & 0.649 & 0.867 & 23.151 & 15.964 & 12.487 & 0.650 & 0.843 & 20.136 \\
67 & 9.192 & 6.766 & 0.850 & 0.935 & 14.298 & 8.377 & 6.240 & 0.875 & 0.944 & 11.865 & 8.462 & 6.287 & 0.873 & 0.944 & 12.158 & 9.310 & 7.043 & 0.846 & 0.935 & 13.905 & 8.365 & 6.286 & 0.876 & 0.945 & 11.544 & 8.550 & 6.332 & 0.870 & 0.943 & 12.204 & 9.319 & 7.000 & 0.846 & 0.934 & 13.461 \\
68 & 18.717 & 15.040 & 0.976 & 0.988 & 17.226 & 19.614 & 15.943 & 0.973 & 0.987 & 17.929 & 19.305 & 15.507 & 0.974 & 0.987 & 18.261 & 33.211 & 23.966 & 0.924 & 0.980 & 38.076 & 19.717 & 16.059 & 0.973 & 0.987 & 18.136 & 19.174 & 15.366 & 0.975 & 0.987 & 18.115 & 32.338 & 23.756 & 0.927 & 0.979 & 36.142 \\
69 & 10.618 & 8.059 & 0.802 & 0.911 & 12.012 & 10.488 & 7.994 & 0.807 & 0.905 & 11.910 & 10.293 & 7.840 & 0.814 & 0.909 & 11.671 & 10.758 & 8.190 & 0.797 & 0.906 & 12.280 & 10.510 & 8.004 & 0.806 & 0.905 & 11.909 & 10.256 & 7.795 & 0.815 & 0.910 & 11.613 & 10.819 & 8.198 & 0.794 & 0.900 & 12.287 \\
70 & 17.531 & 12.099 & 0.823 & 0.938 & 22.030 & 17.811 & 12.353 & 0.818 & 0.938 & 20.655 & 17.641 & 12.166 & 0.821 & 0.939 & 20.723 & 17.138 & 11.729 & 0.831 & 0.940 & 18.883 & 17.837 & 12.408 & 0.817 & 0.939 & 20.401 & 17.664 & 12.197 & 0.821 & 0.940 & 20.835 & 17.587 & 12.131 & 0.822 & 0.940 & 18.928 \\
71 & 12.316 & 7.995 & 0.887 & 0.946 & 14.043 & 12.228 & 8.468 & 0.888 & 0.947 & 14.190 & 12.279 & 8.319 & 0.887 & 0.946 & 14.250 & 11.696 & 7.879 & 0.898 & 0.950 & 13.638 & 12.371 & 8.680 & 0.886 & 0.947 & 14.359 & 12.392 & 8.422 & 0.885 & 0.945 & 14.351 & 11.721 & 8.024 & 0.897 & 0.950 & 13.734 \\
72 & 24.357 & 13.963 & 0.909 & 0.954 & 26.333 & 23.984 & 14.017 & 0.912 & 0.957 & 25.496 & 25.272 & 15.369 & 0.902 & 0.951 & 30.512 & 20.032 & 13.808 & 0.938 & 0.972 & 25.985 & 24.028 & 14.120 & 0.911 & 0.956 & 25.515 & 25.501 & 15.495 & 0.900 & 0.950 & 30.818 & 19.380 & 13.643 & 0.942 & 0.973 & 24.558 \\
73 & 7.782 & 5.660 & 0.896 & 0.964 & 6.938 & 9.818 & 7.371 & 0.834 & 0.963 & 9.094 & 8.737 & 6.441 & 0.868 & 0.964 & 7.930 & 9.619 & 7.174 & 0.841 & 0.962 & 8.946 & 10.249 & 7.843 & 0.819 & 0.964 & 9.773 & 8.860 & 6.610 & 0.865 & 0.964 & 8.114 & 10.847 & 8.388 & 0.797 & 0.961 & 10.438 \\
Mean & 13.523 & 9.956 & 0.794 & 0.918 & 15.843 & 13.507 & 10.068 & 0.796 & 0.919 & 15.191 & 13.431 & 9.962 & 0.801 & 0.921 & 15.552 & 13.642 & 10.182 & 0.806 & 0.923 & 16.304 & 13.564 & 10.137 & 0.794 & 0.919 & 15.151 & 13.443 & 9.961 & 0.801 & 0.921 & 15.624 & 13.611 & 10.241 & 0.805 & 0.922 & 16.039 \\
Global & 13.841 & 9.805 & 0.888 & 0.944 & 25.278 & 13.824 & 9.903 & 0.889 & 0.945 & 24.735 & 13.749 & 9.775 & 0.890 & 0.945 & 25.717 & 13.953 & 9.787 & 0.887 & 0.944 & 33.938 & 13.877 & 9.969 & 0.888 & 0.945 & 24.747 & 13.761 & 9.775 & 0.890 & 0.945 & 25.720 & 13.927 & 9.867 & 0.887 & 0.944 & 32.250 \\
\bottomrule
\end{tabular}

In [ ]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
54               12.618396      12.136333      13.041554
55               17.293221      16.815952      16.968631
56               13.776978       13.86179      13.684032
57               10.447585       9.156381       9.319015
58               15.773875      14.343868      14.974158
59               12.301995      11.732671      12.257052
60               20.074287      18.458648      17.448155
61                17.16978      17.415894       18.06918
62               14.578574      13.080866      13.215677
63               20.154227      18.443311      18.674976
64               13.468333      12.232838      12.461553
65               13.184393      12.369117       12.45585
66               23.128865      22.630148       22.95425
67               14.297932      11.864619      12.157963
68               17.225934      17.929161      18.261454
69               12.012459      11.910321      11.671487
70               22.029528       20.65541      20.723371
71               14.043419      14.190309      14.249558
72               26.332983      25.496097      30.511844
73                 6.93833       9.093637       7.930279
Mean             15.842555      15.190869      15.551502
Global           25.278208       24.73463      25.717132

## Train storms

In [ ]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TRAIN_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)

  0%|          | 0/53 [00:00<?, ?it/s]

100%|██████████| 53/53 [00:44<00:00,  1.19it/s]

In [ ]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[len(summary_df), "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

display(summary_df.mean())

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'



for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

Storm Index             27.0
Equation 1_RMSE     14.79831
Equation 1_MAE     11.361231
Equation 1_R2       0.716058
Equation 1_CC       0.903088
Equation 1_BFE     17.548806
Equation 2_RMSE    15.140747
Equation 2_MAE     11.611798
Equation 2_R2       0.695146
Equation 2_CC       0.901443
Equation 2_BFE     17.681434
Equation 3_RMSE    14.994499
Equation 3_MAE     11.420535
Equation 3_R2       0.705673
Equation 3_CC       0.903823
Equation 3_BFE      17.66812
Equation 4_RMSE    14.903314
Equation 4_MAE     11.412277
Equation 4_R2       0.689535
Equation 4_CC       0.907816
Equation 4_BFE     16.511012
Equation 5_RMSE    15.236143
Equation 5_MAE     11.679358
Equation 5_R2       0.689152
Equation 5_CC        0.90072
Equation 5_BFE     17.731908
Equation 6_RMSE    14.998827
Equation 6_MAE     11.411055
Equation 6_R2       0.704817
Equation 6_CC       0.903443
Equation 6_BFE      17.71539
Equation 7_RMSE    15.135002
Equation 7_MAE     11.574196
Equation 7_R2       0.675934
Equation 7_CC       0.905595
Equation 7_BFE     16.701915
dtype: object

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_CC,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_CC,...,Equation 6_RMSE,Equation 6_MAE,Equation 6_R2,Equation 6_CC,Equation 6_BFE,Equation 7_RMSE,Equation 7_MAE,Equation 7_R2,Equation 7_CC,Equation 7_BFE
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,16.69703,14.045504,0.754609,0.895863,14.264534,16.757259,13.982998,0.752835,0.888442,...,16.086924,13.570816,0.772214,0.903459,12.887402,18.584191,15.525301,0.696004,0.874794,12.086484
2,3,18.563751,14.425571,0.115975,0.602333,18.089756,19.050206,14.731976,0.069037,0.612635,...,18.801806,14.500514,0.093157,0.613738,17.878054,21.427087,16.420962,-0.177767,0.592612,18.282762
3,4,11.467075,9.162138,0.873586,0.935606,12.277404,12.181117,9.550641,0.857352,0.931072,...,11.293233,8.908971,0.87739,0.939516,11.954189,11.914841,9.455888,0.863521,0.93696,10.758006
4,5,15.181822,12.164943,0.827508,0.922936,19.47891,15.825761,12.424307,0.812565,0.920574,...,15.765761,12.461815,0.813984,0.918462,20.555896,16.437194,13.257719,0.797803,0.920208,19.473229
5,6,18.57923,13.316745,0.769047,0.883514,27.046916,18.543568,13.511804,0.769933,0.885451,...,18.662434,13.279726,0.766974,0.881933,27.149181,18.091928,13.923127,0.781003,0.898138,24.875869
6,7,14.606604,10.395774,0.686383,0.914837,17.7651,16.45387,11.524124,0.602042,0.909021,...,16.81834,11.590346,0.584216,0.908764,20.755919,17.857359,12.964298,0.531256,0.882932,21.262446
7,8,10.557127,8.864373,0.805295,0.904136,8.777854,10.609987,8.71615,0.80334,0.901667,...,10.314539,8.494894,0.81414,0.906417,7.891186,10.368487,8.432769,0.812191,0.910651,6.395113
8,9,11.994192,9.861083,0.853669,0.945525,11.657361,11.936519,9.643098,0.855072,0.947607,...,11.556549,9.363383,0.864152,0.948941,11.449887,12.099101,9.407002,0.851098,0.954657,12.729879
9,10,11.041145,7.63761,0.763208,0.919024,9.339973,12.221125,8.251979,0.709891,0.919724,...,11.65861,7.944287,0.735983,0.917485,9.840167,13.265519,9.335378,0.658188,0.917989,11.860631
10,11,12.457191,8.740157,0.671203,0.853214,16.953492,12.844251,8.93082,0.650453,0.859984,...,12.628078,8.736982,0.66212,0.858108,17.186746,13.773263,9.503467,0.59806,0.870282,19.028314
11,12,22.083274,15.95806,0.553061,0.806426,37.120094,21.828841,16.15696,0.5633,0.798387,...,21.903943,15.809365,0.56029,0.813614,37.021096,18.158827,14.404553,0.697798,0.84819,27.012469
12,13,10.24144,7.962517,0.855678,0.931169,10.313544,10.798697,8.397662,0.839545,0.924466,...,10.245829,7.986702,0.855555,0.931469,10.314851,15.159627,10.53228,0.683782,0.91497,14.24505
13,14,14.187374,11.025203,0.777969,0.919765,18.732057,14.594481,11.556795,0.765044,0.918216,...,14.377404,11.230956,0.771981,0.919304,19.025738,14.024698,10.983213,0.783032,0.934413,14.109344
14,15,14.104057,11.20604,0.457162,0.824274,13.234203,14.783063,11.750415,0.403636,0.814333,...,14.131685,11.19436,0.455033,0.812276,13.649966,14.005951,11.05864,0.464687,0.838154,12.092972
15,16,20.482324,14.307795,0.802677,0.934481,24.290028,21.784384,15.396023,0.776792,0.932072,...,22.455248,15.206926,0.762833,0.937516,25.659935,24.088227,16.163815,0.727085,0.934446,28.260749
16,17,18.584791,14.193316,0.744808,0.906706,30.231303,18.938287,14.777566,0.735007,0.894341,...,18.851227,14.392973,0.737438,0.899945,30.566122,16.820387,14.02965,0.790962,0.893072,18.422696
17,18,12.984677,10.802915,0.913929,0.967763,11.614509,12.426091,10.299561,0.921175,0.963974,...,12.149521,10.131931,0.924645,0.967024,10.139398,11.036418,8.92675,0.93782,0.970373,8.239932
18,19,10.288726,7.911855,0.831528,0.926501,10.522836,10.813164,8.306826,0.813916,0.923201,...,10.173692,7.860395,0.835274,0.926162,10.532377,15.183466,10.846147,0.633102,0.919188,18.196671
19,20,13.019199,8.402419,0.884497,0.952131,20.769427,12.985479,8.55334,0.885095,0.94797,...,13.15366,8.44561,0.882099,0.948967,21.171358,9.777599,7.080037,0.934854,0.967222,11.474715
20,21,12.381922,8.436607,0.667078,0.884179,16.251296,13.025906,8.838961,0.631547,0.879629,...,12.596481,8.621106,0.65544,0.887002,16.562562,16.385172,10.247484,0.417001,0.862945,23.774299
21,22,12.575224,10.454924,0.882361,0.9671,13.867004,11.039739,9.06785,0.909335,0.968525,...,11.140533,9.121849,0.907672,0.970297,11.952434,10.460196,8.385975,0.918605,0.967489,10.508044
22,23,26.587852,22.237422,0.659858,0.952327,31.270327,24.823749,20.743395,0.703498,0.948248,...,25.412493,21.125727,0.689266,0.952074,30.013574,20.293108,17.26492,0.801852,0.953353,20.6035
23,24,7.883084,5.936293,0.912504,0.969829,6.411675,7.511846,5.759626,0.920551,0.968943,...,7.58751,5.735943,0.918943,0.969142,5.943566,7.808692,6.177983,0.914148,0.967352,6.239027
24,25,16.124324,12.460445,0.58182,0.82729,23.554169,16.366813,12.807213,0.569147,0.813146,...,16.456647,12.716286,0.564405,0.820992,24.251292,13.525465,11.106393,0.705758,0.862395,17.612313
25,26,8.217896,6.316892,0.84454,0.923503,10.617561,8.497683,6.456178,0.833775,0.923235,...,8.201735,6.123941,0.845151,0.925035,9.677834,8.869003,6.552897,0.81893,0.923133,9.050855
26,27,12.602067,9.530929,0.632743,0.931091,13.606785,12.243897,9.367614,0.653322,0.933885,...,13.228467,10.059149,0.595325,0.930173,14.352732,11.408455,9.210854,0.699018,0.934279,11.952577
27,28,14.909187,12.167023,0.464724,0.786065,21.722293,14.418762,11.622665,0.49936,0.777486,...,14.986703,12.224813,0.459143,0.773661,21.769095,13.278666,10.518508,0.575401,0.779347,13.678557
28,29,15.505038,12.455931,0.493822,0.832426,13.878768,15.334385,11.90745,0.504903,0.825828,...,14.780247,11.746676,0.540039,0.835286,13.940896,18.670107,11.950516,0.266075,0.858712,30.584978
29,30,11.323713,9.029774,0.730992,0.936513,10.07619,12.483472,9.718521,0.673068,0.930515,...,11.683208,9.205927,0.713641,0.932886,10.795659,12.722895,9.969644,0.660407,0.935306,13.255403
30,31,11.275985,9.388836,0.895276,0.952398,11.34209,11.287482,9.346927,0.895062,0.955342,...,11.748654,9.628105,0.886312,0.951196,12.956545,10.181083,7.949128,0.914626,0.965996,11.067242
31,32,14.290379,9.575067,0.965259,0.983153,18.78657,13.060974,9.114278,0.97098,0.985646,...,17.352296,9.866235,0.948777,0.979978,22.921264,14.202657,9.004524,0.965684,0.982855,18.31687
32,33,18.533405,15.086472,0.471869,0.859805,24.20408,20.139204,16.879109,0.376387,0.858217,...,18.950853,15.610706,0.44781,0.856744,24.476321,22.296456,18.618538,0.235632,0.862983,23.886269
33,34,12.201173,10.831534,0.579509,0.898689,9.293939,12.4224,11.082344,0.564123,0.910274,...,11.716129,10.413364,0.612277,0.908588,8.263407,10.494113,9.107637,0.68894,0.915312,7.927891
34,35,14.68832,12.287699,0.593069,0.856544,18.952069,15.422217,13.030591,0.551389,0.860704,...,15.017415,12.63576,0.57463,0.856159,19.281734,15.398783,12.979583,0.552751,0.899363,12.951393
35,36,28.659467,22.574138,0.511069,0.883573,30.553303,30.089087,23.455676,0.461073,0.881118,...,30.200903,23.657768,0.45706,0.881241,32.517786,28.630981,22.837781,0.51204,0.881826,31.438564
36,37,9.144766,7.06311,0.910134,0.957493,9.740969,9.728523,7.644965,0.898294,0.956656,...,9.521303,7.420972,0.902581,0.957967,9.274815,10.27083,8.114122,0.886639,0.951509,10.944152
37,38,25.524848,22.15187,0.877708,0.96057,25.141689,25.281067,21.975846,0.880033,0.96083,...,26.295595,22.467045,0.870212,0.958201,27.188561,24.677449,21.125521,0.885694,0.963876,24.378469
38,39,10.746117,8.659699,0.591942,0.783058,10.985215,10.752954,8.524081,0.591422,0.788421,...,10.276031,8.159609,0.626862,0.801605,10.407314,10.83173,8.294325,0.585414,0.81189,9.12878
39,40,16.853467,10.497031,0.804078,0.909786,34.101823,16.789992,10.484603,0.805551,0.907286,...,16.597843,10.323264,0.809976,0.913513,33.562719,13.031288,9.109308,0.882867,0.941812,21.745875
40,41,16.92353,13.043605,0.663961,0.893314,18.947224,18.258754,13.784803,0.608844,0.89388,...,18.073336,13.523862,0.616748,0.894635,20.746827,19.461903,14.694886,0.555596,0.893243,22.237935
41,42,12.794162,10.38568,0.834543,0.922717,15.540819,12.878873,10.412422,0.832345,0.919306,...,12.199618,9.865429,0.849563,0.928742,13.810024,12.305742,9.941716,0.846935,0.929487,14.202231
42,43,10.88501,8.260004,0.732451,0.938805,10.500608,11.889244,8.649849,0.680806,0.939456,...,11.369022,8.38033,0.708128,0.938524,10.846173,11.638953,8.435983,0.694104,0.934642,11.233556
43,44,18.036311,14.781125,0.673218,0.87117,19.135538,18.307139,15.186091,0.663331,0.871078,...,18.231988,14.878029,0.666089,0.87011,19.003226,18.914612,15.903429,0.640617,0.878074,18.212727
44,45,8.526011,6.086418,0.879565,0.942463,9.636083,7.868738,5.673444,0.897418,0.950162,...,7.829432,5.771827,0.89844,0.951242,9.106952,8.157418,5.568585,0.889753,0.948275,9.957293
45,46,8.031438,6.515819,0.893868,0.961022,10.469082,8.780462,6.556243,0.873149,0.96398,...,10.792384,7.471405,0.808357,0.962033,15.006154,8.994652,6.539395,0.866885,0.958821,12.311779
46,47,16.450943,12.433423,0.86795,0.984216,22.792878,16.039618,12.041293,0.874471,0.984392,...,14.539258,11.347612,0.896857,0.982183,18.319347,15.339013,11.826603,0.885197,0.981693,19.787063
47,48,16.21034,12.915322,0.608259,0.88621,19.879888,18.557161,15.367295,0.486622,0.878474,...,17.921918,14.695829,0.521168,0.881789,22.380865,19.614833,16.307022,0.426434,0.857826,23.337767
48,49,16.498199,11.642191,0.903383,0.962352,21.604283,16.568876,11.816349,0.902553,0.958421,...,15.544594,11.253821,0.914229,0.963529,20.612795,15.253612,11.156279,0.91741,0.960279,21.042001
49,50,20.905455,13.115377,0.921473,0.975787,33.169301,21.757961,13.412007,0.914937,0.975114,...,19.853638,12.68252,0.929176,0.973072,30.808632,17.513807,12.226999,0.944886,0.974312,25.980018
50,51,13.577366,9.256215,0.722198,0.867631,13.272339,14.640572,9.998694,0.676986,0.865528,...,13.99981,9.681925,0.704642,0.869319,14.190243,16.60733,11.34105,0.584372,0.841765,17.837305
51,52,12.130871,9.804211,0.761203,0.921798,10.949627,11.180537,9.04933,0.797153,0.919864,...,11.756363,9.441262,0.77572,0.914564,10.427611,10.968002,8.5302,0.804791,0.916886,9.918694
52,53,12.490572,9.845934,0.745208,0.888533,14.013245,13.435388,10.405225,0.705204,0.883208,...,12.499435,9.758172,0.744846,0.89495,12.662124,12.708033,9.799026,0.736259,0.89291,11.985801
53,NaN,23.700969,16.534183,-0.268345,0.846042,23.338672,26.199983,18.781307,-0.549913,0.846553,...,25.547511,18.058669,-0.473677,0.842927,25.255129,29.165882,20.384593,-0.920682,0.827314,29.304939
54,Mean,14.79831,11.361231,0.716058,0.903088,17.548806,15.140747,11.611798,0.695146,0.901443,...,14.998827,11.411055,0.704817,0.903443,17.71539,15.135002,11.574196,0.675934,0.905595,16.701915
55,Global,15.859985,11.567364,0.826243,0.909264,33.903381,16.186871,11.794442,0.819007,0.906188,...,16.083295,11.603322,0.821316,0.908079,34.540695,15.926741,11.618577,0.824777,0.914686,25.785812

In [ ]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
1                      NaN            NaN            NaN
2                14.264534      13.787673      12.802373
3                18.089756      17.540217       17.71867
4                12.277404      13.113295      12.283887
5                 19.47891      20.133902      20.383505
6                27.046916      26.864577      27.039299
7                  17.7651      20.157141       20.76359
8                 8.777854        7.42574       7.941341
9                11.657361      12.044789      11.498306
10                9.339973      10.355636       9.777223
11               16.953492      17.369521      17.199387
12               37.120094      36.207495      36.872599
13               10.313544      10.176471      10.318476
14               18.732057      18.457685      18.841078
15               13.234203      13.535272      13.539724
16               24.290028      25.374079      25.551939
17               30.231303      30.124984      30.235088
18               11.614509      10.166913      10.279634
19               10.522836      11.439362      10.578139
20               20.769427       19.75798      20.892424
21               16.251296      17.465248      16.772384
22               13.867004       11.61619      11.999154
23               31.270327      28.855115      30.105237
24                6.411675       5.981559       6.008523
25               23.554169      23.727648      23.934521
26               10.617561       9.461017       9.623659
27               13.606785      13.224624      14.131567
28               21.722293       20.56875      21.656185
29               13.878768       13.80734      13.891177
30                10.07619       11.76329      10.822309
31                11.34209      12.143529      12.861635
32                18.78657       16.88294      23.322161
33                24.20408      24.847468      24.297149
34                9.293939       8.049273       8.191677
35               18.952069      18.004341      19.098691
36               30.553303      32.275719      32.623128
37                9.740969       9.156201        9.07702
38               25.141689      25.436889      27.288363
39               10.985215      10.422193      10.317713
40               34.101823      34.232892      33.273248
41               18.947224       20.81965      20.696201
42               15.540819       16.70098      13.718999
43               10.500608      11.497765      10.948035
44               19.135538      19.670026      18.924751
45                9.636083       8.983365        9.05863
46               10.469082      12.043311       14.86354
47               22.792878      22.204335      18.039551
48               19.879888      23.057776      22.219499
49               21.604283      21.822146      20.893504
50               33.169301      34.582102      30.788633
51               13.272339      14.995951      14.170359
52               10.949627       9.619235      10.375051
53               14.013245      13.004478      12.726356
NaN              23.338672      26.159944      25.175045
Mean             17.548806      17.681434       17.66812
Global           33.903381      33.823759      34.580801

In [ ]:

storms = range(54, 74)
parent_folder = 'template-primitive-figures'

for storm_number in storms:
    # We use f-strings with double {{ }} to escape the LaTeX braces
    # and single { } for the Python variables.
    latex_code = f"""
\\begin{{figure}}[ht]
    \\centering
    \\includegraphics[width=\\textwidth]{{{parent_folder}/storm_{storm_number}.png}}
    \\caption{{Reconstruction of storm {storm_number} using the Equations generated from the templated symbolic regression with the primitive features}}\\label{{fig:template-primitive-storm-{storm_number}}}
\\end{{figure}}
"""
    print(latex_code)

\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_54.png}
    \caption{Reconstruction of storm 54 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-54}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_55.png}
    \caption{Reconstruction of storm 55 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-55}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_56.png}
    \caption{Reconstruction of storm 56 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-56}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_57.png}
    \caption{Reconstruction of storm 57 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-57}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_58.png}
    \caption{Reconstruction of storm 58 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-58}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_59.png}
    \caption{Reconstruction of storm 59 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-59}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_60.png}
    \caption{Reconstruction of storm 60 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-60}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_61.png}
    \caption{Reconstruction of storm 61 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-61}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_62.png}
    \caption{Reconstruction of storm 62 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-62}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_63.png}
    \caption{Reconstruction of storm 63 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-63}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_64.png}
    \caption{Reconstruction of storm 64 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-64}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_65.png}
    \caption{Reconstruction of storm 65 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-65}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_66.png}
    \caption{Reconstruction of storm 66 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-66}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_67.png}
    \caption{Reconstruction of storm 67 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-67}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_68.png}
    \caption{Reconstruction of storm 68 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-68}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_69.png}
    \caption{Reconstruction of storm 69 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-69}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_70.png}
    \caption{Reconstruction of storm 70 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-70}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_71.png}
    \caption{Reconstruction of storm 71 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-71}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_72.png}
    \caption{Reconstruction of storm 72 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-72}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-primitive-figures/storm_73.png}
    \caption{Reconstruction of storm 73 using the Equations generated from the templated symbolic regression with the primitive features}\label{fig:template-primitive-storm-73}
\end{figure}