# Test notebook

The purpose of this notebook is to test an equation and compare them with the baselines: Burton, MBR, and DDM1, 2 and 3. We will also plot each storm and get the metrics for the equation.

The only cell that we have to modify is the following one, where we can change the features, the mode (template or default) and the output directory for the plots.
Raw EQ is the equation that we want to test, the raw version generated from the train_script.py file.

In [1]:
%cd /mnt/data/symbolic-regression-dst-public-repo

/mnt/data/symbolic-regression-dst-public-repo

In [ ]:
import os

FEATURES = ["P_dyn", "VBs", "epsilon", "DST"]
MODE = "template"  # 'template' or 'default'
OUTPUT_DIR = "template_deriv_features"
RAW_EQS = [
    "g = (#2 * -0.0010713526) * sqrt(#1 + 1.32442); d = square((#1 * 0.01838707) - 0.5912093)",
    "g = #2 * (sqrt(#1 - -1.1162246) * -0.0010842164); d = square((#1 * -0.01812232) + 0.5913376)",
    "g = (sqrt(#1 - -1.1051167) * #2) * -0.0010888062; d = square((#1 * -0.018209398) + 0.59240085)",
]

output_folder = OUTPUT_DIR
# Count number of existing subfolders
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

import sympy as sp
from tqdm import tqdm

from sympy.printing import latex

# Internal module imports
import storm_dates
import baseline_models

# from evaluation_engine import UnifiedModel, simulate_storm, compute_features
from evaluation_engine import EquationModel, simulate_storm
from train_script import load_and_preprocess, compute_features

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

In [4]:
raw_data = load_and_preprocess()
data = compute_features(raw_data)

Reading from file ./data/all_timeline/ace_imf_1h_1998.csv
Reading from file ./data/all_timeline/ace_imf_1h_1999.csv
Reading from file ./data/all_timeline/ace_imf_1h_2000.csv
Reading from file ./data/all_timeline/ace_imf_1h_2001.csv
Reading from file ./data/all_timeline/ace_imf_1h_2002.csv
Reading from file ./data/all_timeline/ace_imf_1h_2003.csv
Reading from file ./data/all_timeline/ace_imf_1h_2004.csv
Reading from file ./data/all_timeline/ace_imf_1h_2005.csv
Reading from file ./data/all_timeline/ace_imf_1h_2006.csv
Reading from file ./data/all_timeline/ace_imf_1h_2007.csv
Reading from file ./data/all_timeline/ace_imf_1h_2008.csv
Reading from file ./data/all_timeline/ace_imf_1h_2009.csv
Reading from file ./data/all_timeline/ace_imf_1h_2010.csv
Reading from file ./data/all_timeline/ace_imf_1h_2011.csv
Reading from file ./data/all_timeline/ace_imf_1h_2012.csv
Reading from file ./data/all_timeline/ace_imf_1h_2013.csv
Reading from file ./data/all_timeline/ace_imf_1h_2014.csv
Reading from file ./data/all_timeline/ace_imf_1h_2015.csv
Reading from file ./data/all_timeline/ace_imf_1h_2016.csv
Reading from file ./data/all_timeline/ace_imf_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_1h_2024.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1998.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1999.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2000.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2001.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2002.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2003.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2004.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2005.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2006.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2007.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2008.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2009.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2010.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2011.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2012.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2013.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2014.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2015.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2016.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2024.csv

In [5]:
def predict_and_plot_storm(model, eqs, start, end, storm_df, storm_id, save_path):
    # 1. Generate Predictions
    y_true = storm_df[start:end]["DST"].values
    colors = ["blue", "yellow", "green", "orange", "purple", "cyan"]
    res_eqs = []
    string_title = f"Storm {storm_id} Reconstruction\n"
    metrics_info = []
    
    
    for eq_index, eq in enumerate(eqs):
        res_eq = simulate_storm(model[eq], storm_df)
        res_eq = res_eq[start:end]["DST_pred"].values
        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        metrics_info.append(m_eq)
        string_title += f"Evaluation for Equation {eq_index + 1} ({colors[eq_index]}): ${model[eq].latex_str()}$ \n"
    
        res_eqs.append(res_eq)

    # 2. Calculate Metrics
    
    # 3. Setup Figure (3 Columns)
    fig, axs = plt.subplots(1, 3, figsize=(24, 7), constrained_layout=True)
    fig.suptitle(
        string_title, fontsize=18
    )
    # Column 1: Time Series
    axs[0].plot(
        storm_df[start:end].index,
        y_true,
        color="black",
        label="Observed",
        alpha=0.6,
        linewidth=2,
    )
    
    for eq_index, res_eq in enumerate(res_eqs):
    
        axs[0].plot(
            storm_df[start:end].index,
            res_eqs[eq_index],
            color=colors[eq_index],
            linestyle="--",
            label=f"Equation {eq_index + 1}",
            linewidth=1.5,
        )
    
    axs[0].set_title(f"Storm {storm_id} Reconstruction", fontsize=18)
    axs[0].tick_params(axis='both', which='major', labelsize=14)
    axs[0].tick_params(axis='both', which='minor', labelsize=10)
    axs[0].legend(fontsize = 16)
    axs[0].grid(True)
    axs[0].set_xlim(start, end)
    axs[0].set_xlabel("Date", fontsize=16)
    axs[0].set_ylabel("Dst (nT)", fontsize=16)
    axs[0].xaxis.set_major_locator(MultipleLocator(2))
    
    diffs = []
    
    for eq_index, res_eq in enumerate(res_eqs):
        diff_eq = res_eq - y_true
        diffs.append(diff_eq)

        axs[1].plot(storm_df[start:end].index, diff_eq, color=colors[eq_index], label=f"Equation {eq_index + 1} Error")
    
    axs[1].axhline(0, color="black", linestyle="--")

    title_metrics = (
        f"Error Comparison\n"       
    )
    
    for eq_index, m_eq in enumerate(metrics_info):
        title_metrics += f"Eq {eq_index + 1}: MAE={m_eq['MAE']:.2f}, RMSE={m_eq['RMSE']:.2f}, R²={m_eq['R2']:.3f}, BFE={m_eq['BFE']:.3f}\n"
        
        
    axs[1].set_title(title_metrics, fontsize=18)
    axs[1].set_ylabel("Error (nT)", fontsize=16)
    axs[1].set_xlabel("Date", fontsize=16)
    axs[1].legend(fontsize=16)
    axs[1].grid(True)
    axs[1].set_xlim(start, end)
    axs[1].tick_params(axis='both', which='major', labelsize=14)
    axs[1].tick_params(axis='both', which='minor', labelsize=10)
    
    axs[1].xaxis.set_major_locator(MultipleLocator(2))

    # Column 3: BFE
    baseline_models.plot_evaluation_bfe_multi(
        axs[2],
        y_true,
        res_eqs,
        [f"Equation {i+1}" for i in range(len(eqs))],
        [colors[i] for i in range(len(eqs))],
        fontsize = 16   
    )

    plt.savefig(save_path)
    plt.close()

In [6]:
def save_prediction_data(model, eqs, start, end, storm_df, output_path):
    """
    Generates and saves a CSV with observed and predicted DST and dDST/dt.
    """
    # 1. Observed Data
    # Real dDST is calculated as the difference to the next hour
    real_dst = storm_df[start:end]["DST"].values
    real_ddst = storm_df[start:end]["DST"].diff().shift(-1).values

    # 2. Equation Predictions
    # We need the iterative predictions for DST
    pred_dst_eqs = []
    for eq_index, eq in enumerate(eqs):
        pred_dst_eq = simulate_storm(model[eq], storm_df)
        if model[eq].is_template:
            pred_dst_eq = pred_dst_eq[start:end][
                ["DST_pred", "dDST", "injection_component", "decay_component"]
            ]
        else:
            pred_dst_eq = pred_dst_eq[start:end][["DST_pred", "dDST"]]
        pred_dst_eqs.append(pred_dst_eq)
        
    # 3. Baseline Predictions (Burton & OBM)
    
    # 4. Construct Comprehensive DataFrame

    if model[eq].is_template:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Injection_Component": pred_dst_eq["injection_component"].values,
                "Decay_Component": pred_dst_eq["decay_component"].values,
                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values
            results_df[f"Injection_Component_{eq_index+1}"] = pred_dst_eq["injection_component"].values
            results_df[f"Decay_Component_{eq_index+1}"] = pred_dst_eq["decay_component"].values
        
    else:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values


    results_df.to_csv(output_path)
    return results_df

## Test storms

In [7]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TEST_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)
    
with open(os.path.join(OUTPUT_DIR, 'equation.txt'), 'a') as f:
    f.write(f'Equation: {RAW_EQ}\n')            
    f.write(f'LaTeX: {latex(models[RAW_EQ].latex_str())}\n')

  0%|          | 0/20 [00:00<?, ?it/s]

100%|██████████| 20/20 [00:10<00:00,  1.94it/s]

In [8]:
storms[0].columns

Index(['Observed_DST', 'Real_dDST_dt', 'Pred_DST_Equation',
       'Pred_dDST_dt_Equation', 'Injection_Component', 'Decay_Component',
       'Pred_DST_Equation_1', 'Pred_dDST_dt_Equation_1',
       'Injection_Component_1', 'Decay_Component_1', 'Pred_DST_Equation_2',
       'Pred_dDST_dt_Equation_2', 'Injection_Component_2', 'Decay_Component_2',
       'Pred_DST_Equation_3', 'Pred_dDST_dt_Equation_3',
       'Injection_Component_3', 'Decay_Component_3'],
      dtype='object')

In [9]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[storm_indices[storm_index], "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]


global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'

for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_CC,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_CC,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_CC,Equation 3_BFE
54,54,9.233124,7.312462,0.789594,0.921513,11.693279,9.133584,7.232591,0.794106,0.921149,11.626461,9.19187,7.301247,0.79147,0.920786,11.646322
55,55,17.619944,13.900554,0.743418,0.884941,19.805864,17.564804,13.841243,0.745022,0.885049,19.784708,17.584147,13.887456,0.74446,0.885318,19.750457
56,56,13.467562,11.239426,0.601852,0.888309,15.701511,13.524116,11.247863,0.598501,0.888208,15.825734,13.528827,11.279733,0.598222,0.888566,15.788001
57,57,9.583735,7.681486,0.766493,0.899371,12.352802,9.57895,7.65709,0.766726,0.899847,12.266801,9.542605,7.634365,0.768493,0.900465,12.214531
58,58,9.20222,6.327521,0.795389,0.92871,15.794959,9.21504,6.349188,0.794818,0.930432,15.791776,9.191613,6.313452,0.79586,0.931173,15.77743
59,59,12.03556,10.051573,0.854131,0.955656,9.436092,12.082922,10.088617,0.852981,0.955455,9.451668,11.975463,9.989224,0.855584,0.955646,9.409921
60,60,18.038553,11.834238,0.76698,0.931769,27.843956,18.391144,11.914897,0.757782,0.9305,28.591611,18.421335,11.915238,0.756986,0.930995,28.684397
61,61,10.809542,8.352739,0.93034,0.96779,14.671065,10.784213,8.343296,0.930666,0.96835,14.538597,10.823833,8.392287,0.930156,0.968559,14.457715
62,62,11.199501,8.94465,0.708396,0.888831,12.978502,11.196326,8.935398,0.708561,0.889372,13.001519,11.177927,8.930614,0.709518,0.888333,13.034045
63,63,15.00653,12.174898,0.836387,0.944846,18.12369,14.829444,12.014736,0.840226,0.945314,17.878158,14.927598,12.134237,0.838104,0.945052,17.99657
64,64,10.235709,8.131189,0.798251,0.916278,11.303154,10.152513,8.045995,0.801517,0.916507,11.235099,10.220983,8.114652,0.798831,0.916236,11.288269
65,65,14.047145,10.313727,0.644293,0.813849,16.854696,13.928607,10.1814,0.650271,0.818051,16.66573,13.929959,10.220691,0.650203,0.817507,16.694319
66,66,18.293417,15.513456,0.540808,0.79952,20.143055,18.150868,15.387749,0.547937,0.800748,19.933679,18.235791,15.467127,0.543697,0.800114,20.018216
67,67,11.283126,8.518414,0.773713,0.900549,16.163304,11.425037,8.652037,0.767986,0.897831,16.418319,11.439911,8.702166,0.767381,0.897492,16.490568
68,68,28.447981,20.788444,0.943887,0.982481,31.09989,28.982704,20.997377,0.941758,0.982367,31.808772,28.990226,21.059849,0.941728,0.982006,31.608551
69,69,10.981499,8.333531,0.788048,0.901146,12.13304,10.984833,8.318033,0.787919,0.900966,12.13267,11.026203,8.381396,0.786319,0.900204,12.184237
70,70,16.666453,11.931309,0.840258,0.943985,19.215112,16.757624,12.019966,0.838506,0.94339,19.217338,16.703958,11.945682,0.839538,0.943469,19.17545
71,71,11.745357,7.728071,0.897041,0.948448,13.233325,11.733005,7.723223,0.897257,0.948588,13.227865,11.685963,7.649427,0.89808,0.948982,13.158593
72,72,18.63777,13.404547,0.946696,0.977295,23.26821,18.600073,13.33805,0.946911,0.97765,23.274386,18.412621,13.265763,0.947976,0.977883,22.838691
73,73,11.391822,9.301493,0.776383,0.958837,10.669729,11.490369,9.390632,0.772497,0.958158,10.770909,11.369073,9.264521,0.777275,0.958206,10.64819
20,Mean,13.896328,10.589186,0.787118,0.917706,16.624262,13.925309,10.583969,0.787097,0.917897,16.67209,13.918995,10.592456,0.786994,0.91785,16.643224
21,Global,14.083431,10.264332,0.884497,0.941286,29.70386,14.123428,10.257987,0.88384,0.941048,30.130152,14.119428,10.263031,0.883905,0.940999,29.893946

In [10]:
print(summary_df.to_latex(index=False, float_format="%.3f").replace("_", " ").replace("Equation ", "Eq ").replace("Storm Index", "Storm"))

\begin{tabular}{llllllllllllllll}
\toprule
Storm & Eq 1 RMSE & Eq 1 MAE & Eq 1 R2 & Eq 1 CC & Eq 1 BFE & Eq 2 RMSE & Eq 2 MAE & Eq 2 R2 & Eq 2 CC & Eq 2 BFE & Eq 3 RMSE & Eq 3 MAE & Eq 3 R2 & Eq 3 CC & Eq 3 BFE \\
\midrule
54 & 9.233 & 7.312 & 0.790 & 0.922 & 11.693 & 9.134 & 7.233 & 0.794 & 0.921 & 11.626 & 9.192 & 7.301 & 0.791 & 0.921 & 11.646 \\
55 & 17.620 & 13.901 & 0.743 & 0.885 & 19.806 & 17.565 & 13.841 & 0.745 & 0.885 & 19.785 & 17.584 & 13.887 & 0.744 & 0.885 & 19.750 \\
56 & 13.468 & 11.239 & 0.602 & 0.888 & 15.702 & 13.524 & 11.248 & 0.599 & 0.888 & 15.826 & 13.529 & 11.280 & 0.598 & 0.889 & 15.788 \\
57 & 9.584 & 7.681 & 0.766 & 0.899 & 12.353 & 9.579 & 7.657 & 0.767 & 0.900 & 12.267 & 9.543 & 7.634 & 0.768 & 0.900 & 12.215 \\
58 & 9.202 & 6.328 & 0.795 & 0.929 & 15.795 & 9.215 & 6.349 & 0.795 & 0.930 & 15.792 & 9.192 & 6.313 & 0.796 & 0.931 & 15.777 \\
59 & 12.036 & 10.052 & 0.854 & 0.956 & 9.436 & 12.083 & 10.089 & 0.853 & 0.955 & 9.452 & 11.975 & 9.989 & 0.856 & 0.956 & 9.410 \\
60 & 18.039 & 11.834 & 0.767 & 0.932 & 27.844 & 18.391 & 11.915 & 0.758 & 0.930 & 28.592 & 18.421 & 11.915 & 0.757 & 0.931 & 28.684 \\
61 & 10.810 & 8.353 & 0.930 & 0.968 & 14.671 & 10.784 & 8.343 & 0.931 & 0.968 & 14.539 & 10.824 & 8.392 & 0.930 & 0.969 & 14.458 \\
62 & 11.200 & 8.945 & 0.708 & 0.889 & 12.979 & 11.196 & 8.935 & 0.709 & 0.889 & 13.002 & 11.178 & 8.931 & 0.710 & 0.888 & 13.034 \\
63 & 15.007 & 12.175 & 0.836 & 0.945 & 18.124 & 14.829 & 12.015 & 0.840 & 0.945 & 17.878 & 14.928 & 12.134 & 0.838 & 0.945 & 17.997 \\
64 & 10.236 & 8.131 & 0.798 & 0.916 & 11.303 & 10.153 & 8.046 & 0.802 & 0.917 & 11.235 & 10.221 & 8.115 & 0.799 & 0.916 & 11.288 \\
65 & 14.047 & 10.314 & 0.644 & 0.814 & 16.855 & 13.929 & 10.181 & 0.650 & 0.818 & 16.666 & 13.930 & 10.221 & 0.650 & 0.818 & 16.694 \\
66 & 18.293 & 15.513 & 0.541 & 0.800 & 20.143 & 18.151 & 15.388 & 0.548 & 0.801 & 19.934 & 18.236 & 15.467 & 0.544 & 0.800 & 20.018 \\
67 & 11.283 & 8.518 & 0.774 & 0.901 & 16.163 & 11.425 & 8.652 & 0.768 & 0.898 & 16.418 & 11.440 & 8.702 & 0.767 & 0.897 & 16.491 \\
68 & 28.448 & 20.788 & 0.944 & 0.982 & 31.100 & 28.983 & 20.997 & 0.942 & 0.982 & 31.809 & 28.990 & 21.060 & 0.942 & 0.982 & 31.609 \\
69 & 10.981 & 8.334 & 0.788 & 0.901 & 12.133 & 10.985 & 8.318 & 0.788 & 0.901 & 12.133 & 11.026 & 8.381 & 0.786 & 0.900 & 12.184 \\
70 & 16.666 & 11.931 & 0.840 & 0.944 & 19.215 & 16.758 & 12.020 & 0.839 & 0.943 & 19.217 & 16.704 & 11.946 & 0.840 & 0.943 & 19.175 \\
71 & 11.745 & 7.728 & 0.897 & 0.948 & 13.233 & 11.733 & 7.723 & 0.897 & 0.949 & 13.228 & 11.686 & 7.649 & 0.898 & 0.949 & 13.159 \\
72 & 18.638 & 13.405 & 0.947 & 0.977 & 23.268 & 18.600 & 13.338 & 0.947 & 0.978 & 23.274 & 18.413 & 13.266 & 0.948 & 0.978 & 22.839 \\
73 & 11.392 & 9.301 & 0.776 & 0.959 & 10.670 & 11.490 & 9.391 & 0.772 & 0.958 & 10.771 & 11.369 & 9.265 & 0.777 & 0.958 & 10.648 \\
Mean & 13.896 & 10.589 & 0.787 & 0.918 & 16.624 & 13.925 & 10.584 & 0.787 & 0.918 & 16.672 & 13.919 & 10.592 & 0.787 & 0.918 & 16.643 \\
Global & 14.083 & 10.264 & 0.884 & 0.941 & 29.704 & 14.123 & 10.258 & 0.884 & 0.941 & 30.130 & 14.119 & 10.263 & 0.884 & 0.941 & 29.894 \\
\bottomrule
\end{tabular}

In [11]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
54               11.693279      11.626461      11.646322
55               19.805864      19.784708      19.750457
56               15.701511      15.825734      15.788001
57               12.352802      12.266801      12.214531
58               15.794959      15.791776       15.77743
59                9.436092       9.451668       9.409921
60               27.843956      28.591611      28.684397
61               14.671065      14.538597      14.457715
62               12.978502      13.001519      13.034045
63                18.12369      17.878158       17.99657
64               11.303154      11.235099      11.288269
65               16.854696       16.66573      16.694319
66               20.143055      19.933679      20.018216
67               16.163304      16.418319      16.490568
68                31.09989      31.808772      31.608551
69                12.13304       12.13267      12.184237
70               19.215112      19.217338       19.17545
71               13.233325      13.227865      13.158593
72                23.26821      23.274386      22.838691
73               10.669729      10.770909       10.64819
Mean             16.624262       16.67209      16.643224
Global            29.70386      30.130152      29.893946

## Train storms

In [12]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TRAIN_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)

100%|██████████| 53/53 [00:27<00:00,  1.94it/s]

In [13]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[len(summary_df), "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

display(summary_df.mean())

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'



for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

Storm Index             27.0
Equation 1_RMSE    15.355053
Equation 1_MAE     11.864027
Equation 1_R2       0.670004
Equation 1_CC       0.903158
Equation 1_BFE     16.721042
Equation 2_RMSE    15.368584
Equation 2_MAE     11.854889
Equation 2_R2       0.667983
Equation 2_CC       0.903389
Equation 2_BFE     16.720738
Equation 3_RMSE    15.354028
Equation 3_MAE     11.854797
Equation 3_R2       0.669695
Equation 3_CC        0.90333
Equation 3_BFE     16.701925
dtype: object

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_CC,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_CC,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_CC,Equation 3_BFE
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,20.311104,17.228935,0.636882,0.872754,16.914765,20.41542,17.287926,0.633143,0.872032,17.159075,20.50151,17.406734,0.630042,0.871133,17.186395
2,3,22.853433,17.524685,-0.339788,0.576194,19.522754,23.023223,17.644304,-0.35977,0.576921,19.584744,22.949039,17.583713,-0.351021,0.577078,19.519541
3,4,10.945926,8.580534,0.884815,0.951926,8.673134,10.957405,8.588848,0.884574,0.952284,8.530354,10.970735,8.601882,0.884293,0.951741,8.577101
4,5,17.264341,14.163394,0.776941,0.92104,19.999154,17.264461,14.17047,0.776938,0.921216,20.062491,17.250677,14.201701,0.777294,0.920853,19.919848
5,6,18.852171,14.79155,0.762212,0.906563,24.45929,18.811398,14.733568,0.763239,0.907146,24.423398,18.759678,14.761246,0.764539,0.907565,24.314309
6,7,15.491444,12.383221,0.647235,0.883265,16.831797,15.56861,12.437606,0.643712,0.88261,16.892376,15.509408,12.420285,0.646417,0.881884,16.838156
7,8,10.424613,8.619225,0.810152,0.907597,7.077286,10.349696,8.514791,0.812871,0.909175,6.958053,10.366637,8.549774,0.812258,0.908852,6.963698
8,9,12.357561,9.129631,0.844668,0.962511,13.438339,12.348562,9.06949,0.844894,0.962723,13.511569,12.318126,9.071194,0.845658,0.962683,13.3791
9,10,12.641394,9.441574,0.689595,0.916927,11.659186,12.848755,9.606697,0.679328,0.916641,11.848807,12.746874,9.512244,0.684394,0.916899,11.756749
10,11,12.986007,8.945656,0.642695,0.883562,16.730255,13.167944,9.129455,0.632613,0.883457,16.903683,13.10189,9.048726,0.63629,0.883702,16.865924
11,12,17.777983,14.008877,0.710341,0.855589,26.270907,17.635931,13.889577,0.714952,0.857306,25.925077,17.673546,13.937022,0.713735,0.856657,25.975088
12,13,15.138977,10.537508,0.684643,0.923842,14.556872,15.423069,10.749001,0.672696,0.924011,14.987409,15.37071,10.673392,0.674915,0.923136,14.88391
13,14,13.114163,10.315685,0.81029,0.930383,13.956623,13.183197,10.365769,0.808287,0.931175,13.880265,13.097099,10.289789,0.810783,0.931514,13.804643
14,15,12.620035,9.709724,0.565386,0.832784,10.789926,12.659675,9.763482,0.562652,0.83349,10.832844,12.589261,9.707776,0.567503,0.833997,10.791586
15,16,24.331685,15.734112,0.72154,0.939248,28.604129,24.422557,15.710118,0.719456,0.939299,28.750387,24.238151,15.656607,0.723677,0.939604,28.562406
16,17,18.058294,15.602327,0.759062,0.878748,20.218096,17.911454,15.408335,0.762964,0.879704,19.65737,17.987535,15.514808,0.760946,0.878985,19.765498
17,18,10.746015,8.613669,0.941049,0.970422,8.72395,10.757077,8.612557,0.940928,0.970506,8.647994,10.757807,8.628539,0.94092,0.970404,8.692143
18,19,16.374439,11.574767,0.573286,0.92171,19.753865,16.619654,11.744547,0.56041,0.921592,20.074546,16.520208,11.663311,0.565655,0.921591,19.94984
19,20,9.95969,7.426013,0.932405,0.966078,12.35856,9.955044,7.392319,0.932468,0.966261,12.518032,9.956186,7.404101,0.932452,0.966211,12.368266
20,21,14.888919,9.395645,0.518615,0.867135,21.246899,15.124204,9.543456,0.503281,0.866752,21.62572,15.100402,9.500141,0.504843,0.86625,21.610459
21,22,9.802891,7.64353,0.928513,0.968611,10.095872,9.801715,7.622855,0.92853,0.968357,10.077976,9.902124,7.736535,0.927058,0.968161,10.171866
22,23,18.830464,15.862477,0.829386,0.953075,18.853817,18.609144,15.665744,0.833373,0.953511,18.574609,18.751746,15.806645,0.830809,0.95337,18.729877
23,24,9.107749,7.671152,0.883207,0.960707,6.628105,9.036556,7.588418,0.885026,0.960595,6.635631,9.04728,7.605525,0.884753,0.960923,6.611248
24,25,14.35788,12.294548,0.668425,0.844946,17.187633,14.206173,12.122897,0.675395,0.846512,16.925401,14.280122,12.192558,0.672007,0.845487,16.958725
25,26,9.41031,6.992532,0.796153,0.917667,9.491384,9.461191,6.99825,0.793943,0.91741,9.46721,9.404658,6.973014,0.796398,0.917859,9.454812
26,27,12.384871,10.406967,0.645293,0.934308,12.453508,12.175843,10.216659,0.657165,0.93437,12.236252,12.266547,10.306916,0.652038,0.934239,12.320022
27,28,13.607318,10.828731,0.554123,0.757949,13.959117,13.529681,10.701636,0.559196,0.759462,13.665535,13.586454,10.784683,0.555489,0.758484,13.730883
28,29,19.470931,13.315848,0.201764,0.856368,30.656843,19.59868,13.252233,0.191255,0.857225,31.038336,19.568882,13.268127,0.193713,0.856576,30.976568
29,30,11.942214,9.192781,0.700803,0.939338,12.732275,12.102971,9.344426,0.692694,0.939656,12.914533,12.008569,9.254564,0.697469,0.939448,12.828943
30,31,9.337974,7.291203,0.92818,0.966807,9.691332,9.35323,7.301035,0.927945,0.967007,9.69358,9.273229,7.256395,0.929173,0.967189,9.577676
31,32,15.609431,9.501997,0.95855,0.979367,20.931314,15.638687,9.44893,0.958394,0.979322,20.943639,15.80976,9.588228,0.957479,0.978871,21.392639
32,33,23.92173,20.113851,0.120135,0.855645,24.285756,24.083709,20.270848,0.108179,0.85538,24.416108,23.884269,20.073615,0.122889,0.85617,24.29429
33,34,9.114932,6.982195,0.765329,0.899542,9.063739,9.190791,7.044341,0.761406,0.898882,8.996398,9.1268,6.970962,0.764717,0.899271,8.948968
34,35,15.942655,13.172056,0.5206,0.876076,14.025393,16.06576,13.288257,0.513168,0.876681,13.960019,15.937853,13.174381,0.520889,0.877999,13.864574
35,36,28.246896,22.556821,0.525044,0.886755,32.422193,28.115121,22.437969,0.529465,0.887209,32.339815,27.970485,22.362976,0.534294,0.887095,32.181407
36,37,10.662728,8.439706,0.877823,0.944347,13.061146,10.728479,8.489741,0.876312,0.944118,13.14858,10.66496,8.434044,0.877772,0.944361,13.073083
37,38,25.755425,21.87411,0.875489,0.964878,27.041172,25.744731,21.815837,0.875592,0.964938,27.364223,25.779678,21.859896,0.875254,0.964806,27.209306
38,39,9.784509,7.489449,0.661704,0.840115,8.443613,9.779177,7.440512,0.662072,0.841031,8.328543,9.792603,7.464799,0.661144,0.840879,8.342699
39,40,12.065927,8.919628,0.899579,0.949894,15.677446,12.067663,8.924596,0.89955,0.949681,15.420885,12.11103,8.968903,0.898827,0.949544,15.440537
40,41,19.595755,14.542755,0.549462,0.895432,22.016985,19.72256,14.595719,0.543612,0.895767,22.187176,19.613053,14.548022,0.548666,0.895813,22.064121
41,42,12.546054,10.065134,0.840898,0.934474,14.785678,12.408265,9.961183,0.844374,0.934959,14.545242,12.481826,10.042109,0.842523,0.934854,14.603313
42,43,11.626897,8.707636,0.694737,0.92715,10.984635,11.628109,8.685807,0.694674,0.92704,11.003559,11.567132,8.677521,0.697868,0.927126,10.937565
43,44,20.807765,18.047997,0.565076,0.881841,18.154835,20.630382,17.882149,0.57246,0.882765,18.042133,20.707596,17.953589,0.569253,0.883221,17.954512
44,45,11.132171,8.554404,0.794685,0.929769,12.414853,11.028203,8.453849,0.798502,0.929685,12.378706,11.08076,8.518278,0.796577,0.929749,12.378273
45,46,12.048088,10.427684,0.761166,0.916581,11.794551,11.889725,10.27111,0.767404,0.916592,11.596526,11.878306,10.274992,0.76785,0.91722,11.474876
46,47,16.208337,12.415134,0.871816,0.981507,21.414591,15.988791,12.215488,0.875265,0.981565,21.068963,16.089216,12.367619,0.873693,0.981684,21.164146
47,48,20.632796,17.295313,0.365355,0.830277,22.587535,20.713207,17.362553,0.360399,0.830694,22.767765,20.595339,17.247952,0.367658,0.83094,22.672599
48,49,15.636589,11.808773,0.913211,0.959152,20.90254,15.548138,11.76217,0.91419,0.959253,20.822804,15.690485,11.825907,0.912612,0.958753,21.060633
49,50,18.530128,13.026618,0.938304,0.972052,26.553988,18.393991,12.960932,0.939207,0.972029,26.346289,18.570352,13.104313,0.938036,0.971693,26.716568
50,51,16.044348,11.519595,0.612074,0.861295,16.441168,16.139397,11.611428,0.607464,0.86061,16.587104,16.07669,11.51705,0.610508,0.859807,16.501241
51,52,11.827717,8.800787,0.772989,0.896052,10.892424,11.847464,8.782465,0.772231,0.895725,10.946071,11.849517,8.790851,0.772152,0.896967,10.967047
52,53,12.128097,9.344117,0.759781,0.897955,11.054408,12.119086,9.336613,0.760138,0.898829,11.04325,12.052427,9.30073,0.762769,0.898649,11.066455
53,NaN,28.558032,19.961159,-0.841458,0.819146,27.729589,28.741021,20.090172,-0.865132,0.818436,27.942067,28.578275,19.919536,-0.844069,0.818557,27.807879
54,Mean,15.355053,11.864027,0.670004,0.903158,16.721042,15.368584,11.854889,0.667983,0.903389,16.720738,15.354028,11.854797,0.669695,0.90333,16.701925
55,Global,16.116764,11.874496,0.820571,0.913255,26.939251,16.12485,11.859661,0.820391,0.913601,26.981917,16.10937,11.8633,0.820736,0.91344,27.044119

In [14]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
1                      NaN            NaN            NaN
2                16.914765      17.159075      17.186395
3                19.522754      19.584744      19.519541
4                 8.673134       8.530354       8.577101
5                19.999154      20.062491      19.919848
6                 24.45929      24.423398      24.314309
7                16.831797      16.892376      16.838156
8                 7.077286       6.958053       6.963698
9                13.438339      13.511569        13.3791
10               11.659186      11.848807      11.756749
11               16.730255      16.903683      16.865924
12               26.270907      25.925077      25.975088
13               14.556872      14.987409       14.88391
14               13.956623      13.880265      13.804643
15               10.789926      10.832844      10.791586
16               28.604129      28.750387      28.562406
17               20.218096       19.65737      19.765498
18                 8.72395       8.647994       8.692143
19               19.753865      20.074546       19.94984
20                12.35856      12.518032      12.368266
21               21.246899       21.62572      21.610459
22               10.095872      10.077976      10.171866
23               18.853817      18.574609      18.729877
24                6.628105       6.635631       6.611248
25               17.187633      16.925401      16.958725
26                9.491384        9.46721       9.454812
27               12.453508      12.236252      12.320022
28               13.959117      13.665535      13.730883
29               30.656843      31.038336      30.976568
30               12.732275      12.914533      12.828943
31                9.691332        9.69358       9.577676
32               20.931314      20.943639      21.392639
33               24.285756      24.416108       24.29429
34                9.063739       8.996398       8.948968
35               14.025393      13.960019      13.864574
36               32.422193      32.339815      32.181407
37               13.061146       13.14858      13.073083
38               27.041172      27.364223      27.209306
39                8.443613       8.328543       8.342699
40               15.677446      15.420885      15.440537
41               22.016985      22.187176      22.064121
42               14.785678      14.545242      14.603313
43               10.984635      11.003559      10.937565
44               18.154835      18.042133      17.954512
45               12.414853      12.378706      12.378273
46               11.794551      11.596526      11.474876
47               21.414591      21.068963      21.164146
48               22.587535      22.767765      22.672599
49                20.90254      20.822804      21.060633
50               26.553988      26.346289      26.716568
51               16.441168      16.587104      16.501241
52               10.892424      10.946071      10.967047
53               11.054408       11.04325      11.066455
NaN              27.729589      27.942067      27.807879
Mean             16.721042      16.720738      16.701925
Global           26.939251      26.981917      27.044119

In [15]:

storms = range(54, 74)
parent_folder = 'template-derived-figures'

for storm_number in storms:
    # We use f-strings with double {{ }} to escape the LaTeX braces
    # and single { } for the Python variables.
    latex_code = f"""
\\begin{{figure}}[ht]
    \\centering
    \\includegraphics[width=\\textwidth]{{{parent_folder}/storm_{storm_number}.png}}
    \\caption{{Reconstruction of storm {storm_number} using the Equations generated from the templated symbolic regression with the derived features}}\\label{{fig:template-storm-{storm_number}}}
\\end{{figure}}
"""
    print(latex_code)

\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_54.png}
    \caption{Reconstruction of storm 54 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-54}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_55.png}
    \caption{Reconstruction of storm 55 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-55}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_56.png}
    \caption{Reconstruction of storm 56 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-56}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_57.png}
    \caption{Reconstruction of storm 57 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-57}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_58.png}
    \caption{Reconstruction of storm 58 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-58}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_59.png}
    \caption{Reconstruction of storm 59 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-59}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_60.png}
    \caption{Reconstruction of storm 60 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-60}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_61.png}
    \caption{Reconstruction of storm 61 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-61}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_62.png}
    \caption{Reconstruction of storm 62 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-62}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_63.png}
    \caption{Reconstruction of storm 63 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-63}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_64.png}
    \caption{Reconstruction of storm 64 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-64}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_65.png}
    \caption{Reconstruction of storm 65 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-65}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_66.png}
    \caption{Reconstruction of storm 66 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-66}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_67.png}
    \caption{Reconstruction of storm 67 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-67}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_68.png}
    \caption{Reconstruction of storm 68 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-68}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_69.png}
    \caption{Reconstruction of storm 69 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-69}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_70.png}
    \caption{Reconstruction of storm 70 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-70}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_71.png}
    \caption{Reconstruction of storm 71 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-71}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_72.png}
    \caption{Reconstruction of storm 72 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-72}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_73.png}
    \caption{Reconstruction of storm 73 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-73}
\end{figure}