# Test notebook

The purpose of this notebook is to test an equation and compare them with the baselines: Burton, MBR, and DDM1, 2 and 3. We will also plot each storm and get the metrics for the equation.

The only cell that we have to modify is the following one, where we can change the features, the mode (template or default) and the output directory for the plots.
Raw EQ is the equation that we want to test, the raw version generated from the train_script.py file.

In [1]:
import os

FEATURES = ["P_dyn", "VBs", "epsilon", "DST"]
MODE = "template"  # 'template' or 'default'
OUTPUT_DIR = "template_deriv_features_review"
RAW_EQS = [
    "g = (#2 * -0.0010713526) * sqrt(#1 + 1.32442); d = square((#1 * 0.01838707) - 0.5912093)",
    "g = #2 * (sqrt(#1 - -1.1162246) * -0.0010842164); d = square((#1 * -0.01812232) + 0.5913376)",
    "g = (sqrt(#1 - -1.1051167) * #2) * -0.0010888062; d = square((#1 * -0.018209398) + 0.59240085)",
]

start_eq_number = 15

output_folder = OUTPUT_DIR
# Count number of existing subfolders
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

import sympy as sp
from tqdm import tqdm

from sympy.printing import latex

# Internal module imports
import storm_dates
import baseline_models

# from evaluation_engine import UnifiedModel, simulate_storm, compute_features
from evaluation_engine import EquationModel, simulate_storm
from train_script import load_and_preprocess, compute_features

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

/mnt/data/symbolic-regression-dst-public-repo/.venv/lib/python3.12/site-packages/spacepy/time.py:2448: UserWarning: Leapseconds may be out of date. Use spacepy.toolbox.update(leapsecs=True)
  _read_leaps()

In [3]:
raw_data = load_and_preprocess()
data = compute_features(raw_data)

In [4]:
def predict_and_plot_storm(
    model, eqs, start, end, storm_df, storm_id, save_path, eq_start_index=0
):
    # 1. Generate Predictions
    y_true = storm_df[start:end]["DST"].values
    colors = ["blue", "yellow", "green", "orange", "purple", "cyan", "magenta"]
    res_eqs = []

    metrics_info = []

    for eq_index, eq in enumerate(eqs):
        res_eq = simulate_storm(model[eq], storm_df)
        res_eq = res_eq[start:end]["DST_pred"].values
        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        metrics_info.append(m_eq)
        # string_title += f"Evaluation for Equation {eq_index + 1} ({colors[eq_index]}): ${model[eq].latex_str()}$ \n"

        res_eqs.append(res_eq)

    # 2. Calculate Metrics

    # 3. Setup Figure (3 Columns)
    fig, axs = plt.subplots(1, 3, figsize=(24, 9), constrained_layout=True)

    # Column 1: Time Series
    axs[0].plot(
        storm_df[start:end].index,
        y_true,
        color="black",
        label="Observed",
        alpha=0.6,
        linewidth=2,
    )

    for eq_index, res_eq in enumerate(res_eqs):

        axs[0].plot(
            storm_df[start:end].index,
            res_eqs[eq_index],
            color=colors[eq_index],
            linestyle="--",
            # label=f"Equation {eq_index + eq_start_index}",
            label=None,
            linewidth=1.5,
        )

    axs[0].tick_params(axis="both", which="major", labelsize=20)
    axs[0].tick_params(axis="both", which="minor", labelsize=18)
    axs[0].legend(fontsize=20)
    axs[0].set_ylabel("Dst (nT)", fontsize=20)
    axs[0].set_xlabel("Date", fontsize=20)
    axs[0].grid(True)
    axs[0].set_xlim(start, end)
    axs[0].set_title("Storm Reconstruction", fontsize=24)

    axs[0].xaxis.set_major_locator(MultipleLocator(2))
    
    if len(axs[0].xaxis.get_ticklabels()) > 6:    
        for label in axs[0].xaxis.get_ticklabels()[1::2]:
            label.set_visible(False)

    diffs = []

    for eq_index, res_eq in enumerate(res_eqs):
        diff_eq = res_eq - y_true
        diffs.append(diff_eq)

        # axs[1].plot(storm_df[start:end].index, diff_eq, color=colors[eq_index], label=f"Equation {eq_index + eq_start_index} Error")
        axs[1].plot(
            storm_df[start:end].index, diff_eq, color=colors[eq_index], label=None
        )

    axs[1].axhline(0, color="black", linestyle="--")

    title_metrics = f"Error Comparison\n"

    for eq_index, m_eq in enumerate(metrics_info):
        title_metrics += f"Eq {eq_index + eq_start_index} ({colors[eq_index]}): MAE={m_eq['MAE']:.2f}, RMSE={m_eq['RMSE']:.2f}, R²={m_eq['R2']:.3f}, BFE={m_eq['BFE']:.3f}\n"

    # axs[1].set_title(title_metrics, fontsize=18)
    axs[1].set_title("Equation error", fontsize=24)
    axs[1].set_ylabel("Error (nT)", fontsize=20)
    axs[1].set_xlabel("Date", fontsize=20)
    axs[1].grid(True)
    axs[1].set_xlim(start, end)
    axs[1].tick_params(axis="both", which="major", labelsize=20)
    axs[1].tick_params(axis="both", which="minor", labelsize=18)
    
    axs[1].xaxis.set_major_locator(MultipleLocator(2))

    if len(axs[1].xaxis.get_ticklabels()) > 6:    
        for label in axs[1].xaxis.get_ticklabels()[1::2]:
            label.set_visible(False)


    # Column 3: BFE
    baseline_models.plot_evaluation_bfe_multi(
        axs[2],
        y_true,
        res_eqs,
        [f"Equation {i+ eq_start_index}" for i in range(len(eqs))],
        [colors[i] for i in range(len(eqs))],
        fontsize=20,
        plot_legend=False,
    )

    string_title = f"Storm {storm_id} Reconstruction\n{title_metrics}"
    fig.suptitle(string_title, fontsize=24)
    plt.savefig(save_path)
    plt.close()

In [5]:
def save_prediction_data(model, eqs, start, end, storm_df, output_path):
    """
    Generates and saves a CSV with observed and predicted DST and dDST/dt.
    """
    # 1. Observed Data
    # Real dDST is calculated as the difference to the next hour
    real_dst = storm_df[start:end]["DST"].values
    real_ddst = storm_df[start:end]["DST"].diff().shift(-1).values

    # 2. Equation Predictions
    # We need the iterative predictions for DST
    pred_dst_eqs = []
    for eq_index, eq in enumerate(eqs):
        pred_dst_eq = simulate_storm(model[eq], storm_df)
        if model[eq].is_template:
            pred_dst_eq = pred_dst_eq[start:end][
                ["DST_pred", "dDST", "injection_component", "decay_component"]
            ]
        else:
            pred_dst_eq = pred_dst_eq[start:end][["DST_pred", "dDST"]]
        pred_dst_eqs.append(pred_dst_eq)
        
    # 3. Baseline Predictions (Burton & OBM)
    
    # 4. Construct Comprehensive DataFrame

    if model[eq].is_template:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Injection_Component": pred_dst_eq["injection_component"].values,
                "Decay_Component": pred_dst_eq["decay_component"].values,
                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values
            results_df[f"Injection_Component_{eq_index+1}"] = pred_dst_eq["injection_component"].values
            results_df[f"Decay_Component_{eq_index+1}"] = pred_dst_eq["decay_component"].values
        
    else:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values


    results_df.to_csv(output_path)
    return results_df

## Test storms

In [6]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TEST_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
        eq_start_index=start_eq_number
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)
    
with open(os.path.join(OUTPUT_DIR, 'equation.txt'), 'a') as f:
    f.write(f'Equation: {RAW_EQ}\n')            
    f.write(f'LaTeX: {latex(models[RAW_EQ].latex_str())}\n')

  0%|          | 0/20 [00:00<?, ?it/s]

100%|██████████| 20/20 [00:08<00:00,  2.30it/s]

In [7]:
storms[0].columns

Index(['Observed_DST', 'Real_dDST_dt', 'Pred_DST_Equation',
       'Pred_dDST_dt_Equation', 'Injection_Component', 'Decay_Component',
       'Pred_DST_Equation_1', 'Pred_dDST_dt_Equation_1',
       'Injection_Component_1', 'Decay_Component_1', 'Pred_DST_Equation_2',
       'Pred_dDST_dt_Equation_2', 'Injection_Component_2', 'Decay_Component_2',
       'Pred_DST_Equation_3', 'Pred_dDST_dt_Equation_3',
       'Injection_Component_3', 'Decay_Component_3'],
      dtype='object')

In [8]:
metrics = ["RMSE", "MAE", "R2", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[storm_indices[storm_index], "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]


global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'

for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_BFE
54,54,9.08245,7.150428,0.796405,11.620567,9.133584,7.232591,0.794106,11.626461,9.19187,7.301247,0.79147,11.646322
55,55,17.429458,13.783357,0.748936,19.558619,17.564804,13.841243,0.745022,19.784708,17.584147,13.887456,0.74446,19.750457
56,56,13.276276,10.962537,0.613082,15.586261,13.524116,11.247863,0.598501,15.825734,13.528827,11.279733,0.598222,15.788001
57,57,9.5797,7.665862,0.76669,12.124595,9.57895,7.65709,0.766726,12.266801,9.542605,7.634365,0.768493,12.214531
58,58,9.165543,6.390252,0.797016,15.584912,9.21504,6.349188,0.794818,15.791776,9.191613,6.313452,0.79586,15.77743
59,59,12.207318,10.24129,0.849938,9.432197,12.082922,10.088617,0.852981,9.451668,11.975463,9.989224,0.855584,9.409921
60,60,17.617883,11.828793,0.777722,26.807645,18.391144,11.914897,0.757782,28.591611,18.421335,11.915238,0.756986,28.684397
61,61,10.679534,8.252146,0.932006,14.5531,10.784213,8.343296,0.930666,14.538597,10.823833,8.392287,0.930156,14.457715
62,62,11.394979,9.122644,0.698127,12.820999,11.196326,8.935398,0.708561,13.001519,11.177927,8.930614,0.709518,13.034045
63,63,14.975924,12.167919,0.837054,18.193426,14.829444,12.014736,0.840226,17.878158,14.927598,12.134237,0.838104,17.99657
64,64,10.1307,8.022478,0.802369,11.183879,10.152513,8.045995,0.801517,11.235099,10.220983,8.114652,0.798831,11.288269
65,65,14.249835,10.390993,0.633954,16.794854,13.928607,10.1814,0.650271,16.66573,13.929959,10.220691,0.650203,16.694319
66,66,18.264381,15.416668,0.542265,20.120807,18.150868,15.387749,0.547937,19.933679,18.235791,15.467127,0.543697,20.018216
67,67,11.028895,8.25183,0.783796,15.547703,11.425037,8.652037,0.767986,16.418319,11.439911,8.702166,0.767381,16.490568
68,68,27.917544,20.658547,0.94596,30.007003,28.982704,20.997377,0.941758,31.808772,28.990226,21.059849,0.941728,31.608551
69,69,10.957599,8.249883,0.788969,12.099412,10.984833,8.318033,0.787919,12.13267,11.026203,8.381396,0.786319,12.184237
70,70,16.846867,12.100777,0.836781,19.17936,16.757624,12.019966,0.838506,19.217338,16.703958,11.945682,0.839538,19.17545
71,71,11.688103,7.816167,0.898042,13.278875,11.733005,7.723223,0.897257,13.227865,11.685963,7.649427,0.89808,13.158593
72,72,18.315026,13.270134,0.948526,22.36054,18.600073,13.33805,0.946911,23.274386,18.412621,13.265763,0.947976,22.838691
73,73,11.560103,9.467041,0.769727,10.804701,11.490369,9.390632,0.772497,10.770909,11.369073,9.264521,0.777275,10.64819
20,Mean,13.818406,10.560487,0.788368,16.382973,13.925309,10.583969,0.787097,16.67209,13.918995,10.592456,0.786994,16.643224
21,Global,14.012626,10.2502,0.885655,28.790562,14.123428,10.257987,0.88384,30.130152,14.119428,10.263031,0.883905,29.893946

In [9]:
print(summary_df.to_latex(index=False, float_format="%.3f").replace("_", " ").replace("Equation ", "Eq ").replace("Storm Index", "Storm"))

\begin{tabular}{lllllllllllll}
\toprule
Storm & Eq 1 RMSE & Eq 1 MAE & Eq 1 R2 & Eq 1 BFE & Eq 2 RMSE & Eq 2 MAE & Eq 2 R2 & Eq 2 BFE & Eq 3 RMSE & Eq 3 MAE & Eq 3 R2 & Eq 3 BFE \\
\midrule
54 & 9.082 & 7.150 & 0.796 & 11.621 & 9.134 & 7.233 & 0.794 & 11.626 & 9.192 & 7.301 & 0.791 & 11.646 \\
55 & 17.429 & 13.783 & 0.749 & 19.559 & 17.565 & 13.841 & 0.745 & 19.785 & 17.584 & 13.887 & 0.744 & 19.750 \\
56 & 13.276 & 10.963 & 0.613 & 15.586 & 13.524 & 11.248 & 0.599 & 15.826 & 13.529 & 11.280 & 0.598 & 15.788 \\
57 & 9.580 & 7.666 & 0.767 & 12.125 & 9.579 & 7.657 & 0.767 & 12.267 & 9.543 & 7.634 & 0.768 & 12.215 \\
58 & 9.166 & 6.390 & 0.797 & 15.585 & 9.215 & 6.349 & 0.795 & 15.792 & 9.192 & 6.313 & 0.796 & 15.777 \\
59 & 12.207 & 10.241 & 0.850 & 9.432 & 12.083 & 10.089 & 0.853 & 9.452 & 11.975 & 9.989 & 0.856 & 9.410 \\
60 & 17.618 & 11.829 & 0.778 & 26.808 & 18.391 & 11.915 & 0.758 & 28.592 & 18.421 & 11.915 & 0.757 & 28.684 \\
61 & 10.680 & 8.252 & 0.932 & 14.553 & 10.784 & 8.343 & 0.931 & 14.539 & 10.824 & 8.392 & 0.930 & 14.458 \\
62 & 11.395 & 9.123 & 0.698 & 12.821 & 11.196 & 8.935 & 0.709 & 13.002 & 11.178 & 8.931 & 0.710 & 13.034 \\
63 & 14.976 & 12.168 & 0.837 & 18.193 & 14.829 & 12.015 & 0.840 & 17.878 & 14.928 & 12.134 & 0.838 & 17.997 \\
64 & 10.131 & 8.022 & 0.802 & 11.184 & 10.153 & 8.046 & 0.802 & 11.235 & 10.221 & 8.115 & 0.799 & 11.288 \\
65 & 14.250 & 10.391 & 0.634 & 16.795 & 13.929 & 10.181 & 0.650 & 16.666 & 13.930 & 10.221 & 0.650 & 16.694 \\
66 & 18.264 & 15.417 & 0.542 & 20.121 & 18.151 & 15.388 & 0.548 & 19.934 & 18.236 & 15.467 & 0.544 & 20.018 \\
67 & 11.029 & 8.252 & 0.784 & 15.548 & 11.425 & 8.652 & 0.768 & 16.418 & 11.440 & 8.702 & 0.767 & 16.491 \\
68 & 27.918 & 20.659 & 0.946 & 30.007 & 28.983 & 20.997 & 0.942 & 31.809 & 28.990 & 21.060 & 0.942 & 31.609 \\
69 & 10.958 & 8.250 & 0.789 & 12.099 & 10.985 & 8.318 & 0.788 & 12.133 & 11.026 & 8.381 & 0.786 & 12.184 \\
70 & 16.847 & 12.101 & 0.837 & 19.179 & 16.758 & 12.020 & 0.839 & 19.217 & 16.704 & 11.946 & 0.840 & 19.175 \\
71 & 11.688 & 7.816 & 0.898 & 13.279 & 11.733 & 7.723 & 0.897 & 13.228 & 11.686 & 7.649 & 0.898 & 13.159 \\
72 & 18.315 & 13.270 & 0.949 & 22.361 & 18.600 & 13.338 & 0.947 & 23.274 & 18.413 & 13.266 & 0.948 & 22.839 \\
73 & 11.560 & 9.467 & 0.770 & 10.805 & 11.490 & 9.391 & 0.772 & 10.771 & 11.369 & 9.265 & 0.777 & 10.648 \\
Mean & 13.818 & 10.560 & 0.788 & 16.383 & 13.925 & 10.584 & 0.787 & 16.672 & 13.919 & 10.592 & 0.787 & 16.643 \\
Global & 14.013 & 10.250 & 0.886 & 28.791 & 14.123 & 10.258 & 0.884 & 30.130 & 14.119 & 10.263 & 0.884 & 29.894 \\
\bottomrule
\end{tabular}

In [10]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
54               11.620567      11.626461      11.646322
55               19.558619      19.784708      19.750457
56               15.586261      15.825734      15.788001
57               12.124595      12.266801      12.214531
58               15.584912      15.791776       15.77743
59                9.432197       9.451668       9.409921
60               26.807645      28.591611      28.684397
61                 14.5531      14.538597      14.457715
62               12.820999      13.001519      13.034045
63               18.193426      17.878158       17.99657
64               11.183879      11.235099      11.288269
65               16.794854       16.66573      16.694319
66               20.120807      19.933679      20.018216
67               15.547703      16.418319      16.490568
68               30.007003      31.808772      31.608551
69               12.099412       12.13267      12.184237
70                19.17936      19.217338       19.17545
71               13.278875      13.227865      13.158593
72                22.36054      23.274386      22.838691
73               10.804701      10.770909       10.64819
Mean             16.382973       16.67209      16.643224
Global           28.790562      30.130152      29.893946

## Train storms

In [11]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TRAIN_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
        eq_start_index=start_eq_number
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)

100%|██████████| 53/53 [00:23<00:00,  2.30it/s]

In [12]:
metrics = ["RMSE", "MAE", "R2", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[len(summary_df), "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

display(summary_df.mean())

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'



for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

Storm Index             27.0
Equation 1_RMSE    15.372218
Equation 1_MAE     11.877795
Equation 1_R2       0.670062
Equation 1_BFE     16.737971
Equation 2_RMSE    15.368584
Equation 2_MAE     11.854889
Equation 2_R2       0.667983
Equation 2_BFE     16.720738
Equation 3_RMSE    15.354028
Equation 3_MAE     11.854797
Equation 3_R2       0.669695
Equation 3_BFE     16.701925
dtype: object

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_BFE
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,20.213585,17.117328,0.640361,16.822423,20.41542,17.287926,0.633143,17.159075,20.50151,17.406734,0.630042,17.186395
2,3,22.835546,17.477713,-0.337692,19.405386,23.023223,17.644304,-0.35977,19.584744,22.949039,17.583713,-0.351021,19.519541
3,4,11.215986,8.793026,0.879061,8.793067,10.957405,8.588848,0.884574,8.530354,10.970735,8.601882,0.884293,8.577101
4,5,17.213986,14.144183,0.77824,19.953851,17.264461,14.17047,0.776938,20.062491,17.250677,14.201701,0.777294,19.919848
5,6,18.665306,14.714571,0.766902,24.272886,18.811398,14.733568,0.763239,24.423398,18.759678,14.761246,0.764539,24.314309
6,7,15.532397,12.371153,0.645368,16.965733,15.56861,12.437606,0.643712,16.892376,15.509408,12.420285,0.646417,16.838156
7,8,10.465127,8.609895,0.808674,7.050362,10.349696,8.514791,0.812871,6.958053,10.366637,8.549774,0.812258,6.963698
8,9,12.263987,9.014927,0.847011,13.26364,12.348562,9.06949,0.844894,13.511569,12.318126,9.071194,0.845658,13.3791
9,10,12.576511,9.406606,0.692773,11.592131,12.848755,9.606697,0.679328,11.848807,12.746874,9.512244,0.684394,11.756749
10,11,13.05019,9.008404,0.639154,16.813556,13.167944,9.129455,0.632613,16.903683,13.10189,9.048726,0.63629,16.865924
11,12,17.947936,14.182177,0.704777,26.471161,17.635931,13.889577,0.714952,25.925077,17.673546,13.937022,0.713735,25.975088
12,13,15.112173,10.515101,0.685759,14.319192,15.423069,10.749001,0.672696,14.987409,15.37071,10.673392,0.674915,14.88391
13,14,13.265907,10.45822,0.805874,14.029323,13.183197,10.365769,0.808287,13.880265,13.097099,10.289789,0.810783,13.804643
14,15,12.811257,9.830699,0.552116,10.835162,12.659675,9.763482,0.562652,10.832844,12.589261,9.707776,0.567503,10.791586
15,16,24.010947,15.68995,0.728833,28.174916,24.422557,15.710118,0.719456,28.750387,24.238151,15.656607,0.723677,28.562406
16,17,18.188904,15.714046,0.755564,20.651944,17.911454,15.408335,0.762964,19.65737,17.987535,15.514808,0.760946,19.765498
17,18,10.833286,8.694169,0.940088,8.830035,10.757077,8.612557,0.940928,8.647994,10.757807,8.628539,0.94092,8.692143
18,19,16.210249,11.523015,0.581801,19.58233,16.619654,11.744547,0.56041,20.074546,16.520208,11.663311,0.565655,19.94984
19,20,10.024904,7.477991,0.931517,11.930764,9.955044,7.392319,0.932468,12.518032,9.956186,7.404101,0.932452,12.368266
20,21,14.931826,9.410059,0.515837,21.315414,15.124204,9.543456,0.503281,21.62572,15.100402,9.500141,0.504843,21.610459
21,22,9.843541,7.701065,0.927919,10.033816,9.801715,7.622855,0.92853,10.077976,9.902124,7.736535,0.927058,10.171866
22,23,18.91417,15.961274,0.827865,19.050654,18.609144,15.665744,0.833373,18.574609,18.751746,15.806645,0.830809,18.729877
23,24,8.975684,7.551262,0.88657,6.60202,9.036556,7.588418,0.885026,6.635631,9.04728,7.605525,0.884753,6.611248
24,25,14.394709,12.308746,0.666722,17.235002,14.206173,12.122897,0.675395,16.925401,14.280122,12.192558,0.672007,16.958725
25,26,9.437518,6.978002,0.794973,9.320807,9.461191,6.99825,0.793943,9.46721,9.404658,6.973014,0.796398,9.454812
26,27,12.264311,10.297215,0.652165,12.357459,12.175843,10.216659,0.657165,12.236252,12.266547,10.306916,0.652038,12.320022
27,28,13.612072,10.824294,0.553811,14.074261,13.529681,10.701636,0.559196,13.665535,13.586454,10.784683,0.555489,13.730883
28,29,19.343489,13.190657,0.212179,30.167217,19.59868,13.252233,0.191255,31.038336,19.568882,13.268127,0.193713,30.976568
29,30,12.014108,9.250668,0.69719,12.881471,12.102971,9.344426,0.692694,12.914533,12.008569,9.254564,0.697469,12.828943
30,31,9.278657,7.244824,0.92909,9.642171,9.35323,7.301035,0.927945,9.69358,9.273229,7.256395,0.929173,9.577676
31,32,16.044902,9.759153,0.956205,22.056034,15.638687,9.44893,0.958394,20.943639,15.80976,9.588228,0.957479,21.392639
32,33,23.88012,20.097481,0.123193,24.338882,24.083709,20.270848,0.108179,24.416108,23.884269,20.073615,0.122889,24.29429
33,34,9.214245,7.137838,0.760187,8.867133,9.190791,7.044341,0.761406,8.996398,9.1268,6.970962,0.764717,8.948968
34,35,16.058226,13.277662,0.513625,13.927815,16.06576,13.288257,0.513168,13.960019,15.937853,13.174381,0.520889,13.864574
35,36,28.252618,22.559199,0.524852,32.481128,28.115121,22.437969,0.529465,32.339815,27.970485,22.362976,0.534294,32.181407
36,37,10.612487,8.420242,0.878972,12.769259,10.728479,8.489741,0.876312,13.14858,10.66496,8.434044,0.877772,13.073083
37,38,25.550866,21.7106,0.877459,26.452305,25.744731,21.815837,0.875592,27.364223,25.779678,21.859896,0.875254,27.209306
38,39,9.853031,7.514463,0.656949,8.446984,9.779177,7.440512,0.662072,8.328543,9.792603,7.464799,0.661144,8.342699
39,40,12.055164,8.903145,0.899758,15.941908,12.067663,8.924596,0.89955,15.420885,12.11103,8.968903,0.898827,15.440537
40,41,19.549865,14.523449,0.551569,22.016213,19.72256,14.595719,0.543612,22.187176,19.613053,14.548022,0.548666,22.064121
41,42,12.493841,10.052664,0.84222,14.915449,12.408265,9.961183,0.844374,14.545242,12.481826,10.042109,0.842523,14.603313
42,43,11.64885,8.642364,0.693583,10.957704,11.628109,8.685807,0.694674,11.003559,11.567132,8.677521,0.697868,10.937565
43,44,20.687618,17.953281,0.570084,18.079162,20.630382,17.882149,0.57246,18.042133,20.707596,17.953589,0.569253,17.954512
44,45,10.927737,8.406674,0.802157,12.185143,11.028203,8.453849,0.798502,12.378706,11.08076,8.518278,0.796577,12.378273
45,46,11.907718,10.299125,0.766699,11.907872,11.889725,10.27111,0.767404,11.596526,11.878306,10.274992,0.76785,11.474876
46,47,16.195311,12.425902,0.872022,21.487387,15.988791,12.215488,0.875265,21.068963,16.089216,12.367619,0.873693,21.164146
47,48,20.768864,17.433618,0.356957,22.781677,20.713207,17.362553,0.360399,22.767765,20.595339,17.247952,0.367658,22.672599
48,49,16.043305,12.029262,0.908637,21.449219,15.548138,11.76217,0.91419,20.822804,15.690485,11.825907,0.912612,21.060633
49,50,18.984824,13.264342,0.935239,27.664018,18.393991,12.960932,0.939207,26.346289,18.570352,13.104313,0.938036,26.716568
50,51,16.205058,11.617331,0.604264,16.590475,16.139397,11.611428,0.607464,16.587104,16.07669,11.51705,0.610508,16.501241
51,52,11.61586,8.659121,0.781049,10.613207,11.847464,8.782465,0.772231,10.946071,11.849517,8.790851,0.772152,10.967047
52,53,12.288652,9.469239,0.753379,11.05381,12.119086,9.336613,0.760138,11.04325,12.052427,9.30073,0.762769,11.066455
53,NaN,28.440146,19.905758,-0.826286,27.691534,28.741021,20.090172,-0.865132,27.942067,28.578275,19.919536,-0.844069,27.807879
54,Mean,15.372218,11.877795,0.670062,16.737971,15.368584,11.854889,0.667983,16.720738,15.354028,11.854797,0.669695,16.701925
55,Global,16.131842,11.892542,0.820235,27.224719,16.12485,11.859661,0.820391,26.981917,16.10937,11.8633,0.820736,27.044119

In [13]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
1                      NaN            NaN            NaN
2                16.822423      17.159075      17.186395
3                19.405386      19.584744      19.519541
4                 8.793067       8.530354       8.577101
5                19.953851      20.062491      19.919848
6                24.272886      24.423398      24.314309
7                16.965733      16.892376      16.838156
8                 7.050362       6.958053       6.963698
9                 13.26364      13.511569        13.3791
10               11.592131      11.848807      11.756749
11               16.813556      16.903683      16.865924
12               26.471161      25.925077      25.975088
13               14.319192      14.987409       14.88391
14               14.029323      13.880265      13.804643
15               10.835162      10.832844      10.791586
16               28.174916      28.750387      28.562406
17               20.651944       19.65737      19.765498
18                8.830035       8.647994       8.692143
19                19.58233      20.074546       19.94984
20               11.930764      12.518032      12.368266
21               21.315414       21.62572      21.610459
22               10.033816      10.077976      10.171866
23               19.050654      18.574609      18.729877
24                 6.60202       6.635631       6.611248
25               17.235002      16.925401      16.958725
26                9.320807        9.46721       9.454812
27               12.357459      12.236252      12.320022
28               14.074261      13.665535      13.730883
29               30.167217      31.038336      30.976568
30               12.881471      12.914533      12.828943
31                9.642171        9.69358       9.577676
32               22.056034      20.943639      21.392639
33               24.338882      24.416108       24.29429
34                8.867133       8.996398       8.948968
35               13.927815      13.960019      13.864574
36               32.481128      32.339815      32.181407
37               12.769259       13.14858      13.073083
38               26.452305      27.364223      27.209306
39                8.446984       8.328543       8.342699
40               15.941908      15.420885      15.440537
41               22.016213      22.187176      22.064121
42               14.915449      14.545242      14.603313
43               10.957704      11.003559      10.937565
44               18.079162      18.042133      17.954512
45               12.185143      12.378706      12.378273
46               11.907872      11.596526      11.474876
47               21.487387      21.068963      21.164146
48               22.781677      22.767765      22.672599
49               21.449219      20.822804      21.060633
50               27.664018      26.346289      26.716568
51               16.590475      16.587104      16.501241
52               10.613207      10.946071      10.967047
53                11.05381       11.04325      11.066455
NaN              27.691534      27.942067      27.807879
Mean             16.737971      16.720738      16.701925
Global           27.224719      26.981917      27.044119

In [14]:

storms = range(54, 74)
parent_folder = 'template-derived-figures'

for storm_number in storms:
    # We use f-strings with double {{ }} to escape the LaTeX braces
    # and single { } for the Python variables.
    latex_code = f"""
\\begin{{figure}}[ht]
    \\centering
    \\includegraphics[width=\\textwidth]{{{parent_folder}/storm_{storm_number}.png}}
    \\caption{{Reconstruction of storm {storm_number} using the Equations generated from the templated symbolic regression with the derived features}}\\label{{fig:template-storm-{storm_number}}}
\\end{{figure}}
"""
    print(latex_code)

\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_54.png}
    \caption{Reconstruction of storm 54 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-54}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_55.png}
    \caption{Reconstruction of storm 55 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-55}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_56.png}
    \caption{Reconstruction of storm 56 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-56}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_57.png}
    \caption{Reconstruction of storm 57 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-57}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_58.png}
    \caption{Reconstruction of storm 58 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-58}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_59.png}
    \caption{Reconstruction of storm 59 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-59}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_60.png}
    \caption{Reconstruction of storm 60 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-60}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_61.png}
    \caption{Reconstruction of storm 61 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-61}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_62.png}
    \caption{Reconstruction of storm 62 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-62}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_63.png}
    \caption{Reconstruction of storm 63 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-63}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_64.png}
    \caption{Reconstruction of storm 64 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-64}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_65.png}
    \caption{Reconstruction of storm 65 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-65}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_66.png}
    \caption{Reconstruction of storm 66 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-66}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_67.png}
    \caption{Reconstruction of storm 67 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-67}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_68.png}
    \caption{Reconstruction of storm 68 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-68}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_69.png}
    \caption{Reconstruction of storm 69 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-69}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_70.png}
    \caption{Reconstruction of storm 70 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-70}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_71.png}
    \caption{Reconstruction of storm 71 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-71}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_72.png}
    \caption{Reconstruction of storm 72 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-72}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{template-derived-figures/storm_73.png}
    \caption{Reconstruction of storm 73 using the Equations generated from the templated symbolic regression with the derived features}\label{fig:template-storm-73}
\end{figure}