# Test notebook

The purpose of this notebook is to test an equation and compare them with the baselines: Burton, MBR, and DDM1, 2 and 3. We will also plot each storm and get the metrics for the equation.

The only cell that we have to modify is the following one, where we can change the features, the mode (template or default) and the output directory for the plots.
Raw EQ is the equation that we want to test, the raw version generated from the train_script.py file.

In [2]:
import os

FEATURES = ["Vp", "Np", "Bzsouth", "Bmag", "DST"]
MODE = "default"  # 'template' or 'default'
OUTPUT_DIR = "unconstrained_primitive_features"
RAW_EQS = [
    "((Vp * ((Bzsouth + 1.4056387) * ((DST * (0.0010231906 / (-1.9690949 - Np))) - 0.04994203))) - (DST - (Np + 26.93975))) / (51.730183 / sqrt(sqrt(Np * Bmag)))",
    "(DST * -0.052771024) - ((((Vp + (Bzsouth * Np)) + (DST / 0.44165215)) * 0.0024323284) * Bzsouth)",
    "((DST - Np) * -0.04895255) + (Bzsouth * ((((DST * 2.4618247) + Vp) + (Bzsouth * Np)) * -0.0025749283))",
]

output_folder = OUTPUT_DIR
# Count number of existing subfolders
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import sympy as sp
from tqdm import tqdm

from sympy.printing import latex

# Internal module imports
import storm_dates
import baseline_models

# from evaluation_engine import UnifiedModel, simulate_storm, compute_features
from evaluation_engine import EquationModel, simulate_storm
from train_script import load_and_preprocess, compute_features

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

In [4]:
raw_data = load_and_preprocess()
data = compute_features(raw_data)

Reading from file ./data/all_timeline/ace_imf_1h_1998.csv
Reading from file ./data/all_timeline/ace_imf_1h_1999.csv
Reading from file ./data/all_timeline/ace_imf_1h_2000.csv
Reading from file ./data/all_timeline/ace_imf_1h_2001.csv
Reading from file ./data/all_timeline/ace_imf_1h_2002.csv
Reading from file ./data/all_timeline/ace_imf_1h_2003.csv
Reading from file ./data/all_timeline/ace_imf_1h_2004.csv
Reading from file ./data/all_timeline/ace_imf_1h_2005.csv
Reading from file ./data/all_timeline/ace_imf_1h_2006.csv
Reading from file ./data/all_timeline/ace_imf_1h_2007.csv
Reading from file ./data/all_timeline/ace_imf_1h_2008.csv
Reading from file ./data/all_timeline/ace_imf_1h_2009.csv
Reading from file ./data/all_timeline/ace_imf_1h_2010.csv
Reading from file ./data/all_timeline/ace_imf_1h_2011.csv
Reading from file ./data/all_timeline/ace_imf_1h_2012.csv
Reading from file ./data/all_timeline/ace_imf_1h_2013.csv
Reading from file ./data/all_timeline/ace_imf_1h_2014.csv
Reading from file ./data/all_timeline/ace_imf_1h_2015.csv
Reading from file ./data/all_timeline/ace_imf_1h_2016.csv
Reading from file ./data/all_timeline/ace_imf_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_1h_2024.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1998.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1999.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2000.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2001.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2002.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2003.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2004.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2005.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2006.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2007.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2008.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2009.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2010.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2011.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2012.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2013.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2014.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2015.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2016.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2024.csv

In [5]:
def predict_and_plot_storm(model, eqs, start, end, storm_df, storm_id, save_path):
    # 1. Generate Predictions
    y_true = storm_df[start:end]["DST"].values
    colors = ["blue", "yellow", "green", "orange", "purple", "cyan"]
    res_eqs = []
    string_title = f"Storm {storm_id} Reconstruction\n"
    metrics_info = []
    
    
    for eq_index, eq in enumerate(eqs):
        res_eq = simulate_storm(model[eq], storm_df)
        res_eq = res_eq[start:end]["DST_pred"].values
        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        metrics_info.append(m_eq)
        string_title += f"Evaluation for Equation {eq_index + 1} ({colors[eq_index]}): ${model[eq].latex_str()}$ \n"
    
        res_eqs.append(res_eq)

    # 2. Calculate Metrics
    
    # 3. Setup Figure (3 Columns)
    fig, axs = plt.subplots(1, 3, figsize=(24, 7), constrained_layout=True)
    fig.suptitle(
        string_title, fontsize=18
    )
    # Column 1: Time Series
    axs[0].plot(
        storm_df[start:end].index,
        y_true,
        color="black",
        label="Observed",
        alpha=0.6,
        linewidth=2,
    )
    
    for eq_index, res_eq in enumerate(res_eqs):
    
        axs[0].plot(
            storm_df[start:end].index,
            res_eqs[eq_index],
            color=colors[eq_index],
            linestyle="--",
            label=f"Equation {eq_index + 1}",
            linewidth=1.5,
        )
    
    axs[0].set_title(f"Storm {storm_id} Reconstruction", fontsize=18)
    axs[0].tick_params(axis='both', which='major', labelsize=14)
    axs[0].tick_params(axis='both', which='minor', labelsize=10)
    axs[0].legend(fontsize = 16)
    axs[0].grid(True)
    axs[0].set_xlim(start, end)
    axs[0].set_xlabel("Date", fontsize=16)
    axs[0].set_ylabel("Dst (nT)", fontsize=16)
    axs[0].xaxis.set_major_locator(MultipleLocator(2))
    
    diffs = []
    
    for eq_index, res_eq in enumerate(res_eqs):
        diff_eq = res_eq - y_true
        diffs.append(diff_eq)

        axs[1].plot(storm_df[start:end].index, diff_eq, color=colors[eq_index], label=f"Equation {eq_index + 1} Error")
    
    axs[1].axhline(0, color="black", linestyle="--")

    title_metrics = (
        f"Error Comparison\n"       
    )
    
    for eq_index, m_eq in enumerate(metrics_info):
        title_metrics += f"Eq {eq_index + 1}: MAE={m_eq['MAE']:.2f}, RMSE={m_eq['RMSE']:.2f}, R²={m_eq['R2']:.3f}, BFE={m_eq['BFE']:.3f}\n"
        
        
    axs[1].set_title(title_metrics, fontsize=18)
    axs[1].set_ylabel("Error (nT)", fontsize=16)
    axs[1].set_xlabel("Date", fontsize=16)
    axs[1].legend(fontsize=16)
    axs[1].grid(True)
    axs[1].set_xlim(start, end)
    axs[1].tick_params(axis='both', which='major', labelsize=14)
    axs[1].tick_params(axis='both', which='minor', labelsize=10)
    
    axs[1].xaxis.set_major_locator(MultipleLocator(2))

    # Column 3: BFE
    baseline_models.plot_evaluation_bfe_multi(
        axs[2],
        y_true,
        res_eqs,
        [f"Equation {i+1}" for i in range(len(eqs))],
        [colors[i] for i in range(len(eqs))],
        fontsize = 16   
    )

    plt.savefig(save_path)
    plt.close()

In [6]:
def save_prediction_data(model, eqs, start, end, storm_df, output_path):
    """
    Generates and saves a CSV with observed and predicted DST and dDST/dt.
    """
    # 1. Observed Data
    # Real dDST is calculated as the difference to the next hour
    real_dst = storm_df[start:end]["DST"].values
    real_ddst = storm_df[start:end]["DST"].diff().shift(-1).values

    # 2. Equation Predictions
    # We need the iterative predictions for DST
    pred_dst_eqs = []
    for eq_index, eq in enumerate(eqs):
        pred_dst_eq = simulate_storm(model[eq], storm_df)
        if model[eq].is_template:
            pred_dst_eq = pred_dst_eq[start:end][
                ["DST_pred", "dDST", "injection_component", "decay_component"]
            ]
        else:
            pred_dst_eq = pred_dst_eq[start:end][["DST_pred", "dDST"]]
        pred_dst_eqs.append(pred_dst_eq)
        
    # 3. Baseline Predictions (Burton & OBM)
    
    # 4. Construct Comprehensive DataFrame

    if model[eq].is_template:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Injection_Component": pred_dst_eq["injection_component"].values,
                "Decay_Component": pred_dst_eq["decay_component"].values,
                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values
            results_df[f"Injection_Component_{eq_index+1}"] = pred_dst_eq["injection_component"].values
            results_df[f"Decay_Component_{eq_index+1}"] = pred_dst_eq["decay_component"].values
        
    else:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values


    results_df.to_csv(output_path)
    return results_df

## Test storms

In [7]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TEST_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)
    
with open(os.path.join(OUTPUT_DIR, 'equation.txt'), 'a') as f:
    f.write(f'Equation: {RAW_EQ}\n')            
    f.write(f'LaTeX: {latex(models[RAW_EQ].latex_str())}\n')

  0%|          | 0/20 [00:00<?, ?it/s]

100%|██████████| 20/20 [00:10<00:00,  1.83it/s]

In [8]:
storms[0].columns

Index(['Observed_DST', 'Real_dDST_dt', 'Pred_DST_Equation_1',
       'Pred_dDST_dt_Equation_1', 'Pred_DST_Equation_2',
       'Pred_dDST_dt_Equation_2', 'Pred_DST_Equation_3',
       'Pred_dDST_dt_Equation_3'],
      dtype='object')

In [9]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[storm_indices[storm_index], "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]


global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'

for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_CC,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_CC,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_CC,Equation 3_BFE
54,54,9.175878,6.119586,0.792195,0.920165,11.065619,11.584564,8.861792,0.668777,0.916186,16.183557,12.20025,9.334337,0.632634,0.936198,15.866722
55,55,14.872851,11.446008,0.817188,0.923973,15.957827,16.239771,13.384107,0.78204,0.898516,16.825083,16.101688,13.040237,0.785731,0.90866,16.417254
56,56,16.062623,10.935829,0.433631,0.869626,19.312422,10.638671,8.541751,0.751549,0.878178,12.855017,11.068902,8.716594,0.731048,0.876615,13.648058
57,57,9.185713,7.11477,0.785486,0.900055,8.332227,9.657408,7.793181,0.762889,0.897258,8.811508,10.061079,8.250151,0.742653,0.880514,8.561342
58,58,8.457673,6.020012,0.827159,0.93963,13.607761,9.012639,6.801491,0.803732,0.929342,13.49815,8.466631,6.227716,0.826793,0.926282,13.938754
59,59,18.584858,15.73909,0.652185,0.933319,11.690355,13.676323,11.806723,0.811649,0.955219,11.506934,14.562744,12.563,0.786442,0.952266,11.121084
60,60,23.884502,17.550124,0.591472,0.925036,35.776495,17.859016,14.196446,0.771596,0.938111,20.259943,18.325205,14.755451,0.759516,0.936895,19.979894
61,61,15.668521,9.179435,0.853639,0.96264,25.50768,11.921536,9.179378,0.915271,0.960524,16.534556,11.826668,8.773574,0.916614,0.964248,16.32869
62,62,12.475285,10.340246,0.638176,0.911868,10.320134,13.974277,11.807244,0.546,0.834528,12.899981,13.45665,11.220634,0.579011,0.850906,12.298406
63,63,10.747254,7.476902,0.916083,0.97747,16.02663,17.041824,13.962885,0.788997,0.90157,21.014232,16.558724,13.501615,0.80079,0.91456,21.085079
64,64,8.405894,6.355707,0.863936,0.932605,9.422682,9.881356,7.913788,0.811978,0.912468,11.854581,9.71032,7.79948,0.81843,0.91827,11.413945
65,65,15.353722,12.148841,0.575045,0.777127,19.357769,16.516854,11.8464,0.50822,0.793905,13.718376,16.140402,11.536368,0.530382,0.786924,13.079389
66,66,15.705417,11.808696,0.661543,0.886919,21.213558,20.919272,16.088243,0.399522,0.719837,26.436026,21.019108,15.917066,0.393777,0.74829,26.715097
67,67,8.764607,6.759319,0.863458,0.956724,11.203738,9.506853,7.259771,0.839353,0.943796,11.65657,9.433217,7.443122,0.841832,0.952702,11.263004
68,68,21.683751,15.933038,0.967399,0.98485,21.877896,23.370638,18.995258,0.96213,0.98415,23.227678,21.083482,16.91222,0.969179,0.986203,20.970041
69,69,11.823839,8.938792,0.754285,0.880454,12.992782,12.433506,9.529751,0.728292,0.870571,13.330385,11.134872,8.820648,0.782086,0.898256,12.451084
70,70,18.157469,13.536019,0.810398,0.937705,19.353599,21.145949,15.651357,0.74285,0.934009,23.784731,19.433971,14.306828,0.782802,0.937561,23.071657
71,71,12.620079,9.902699,0.881134,0.952767,14.511539,13.000616,9.582093,0.873858,0.947085,15.369796,13.143878,10.038738,0.871063,0.947137,15.486503
72,72,30.306243,22.817292,0.859059,0.962329,37.041639,26.311762,16.567637,0.893764,0.949476,31.583442,26.718778,17.017419,0.890451,0.950216,32.485097
73,73,10.719242,8.162253,0.802008,0.962466,10.374919,11.873904,9.665259,0.757056,0.954341,10.326332,10.250782,7.983305,0.818935,0.956423,8.856075
20,Mean,14.632771,10.914233,0.767274,0.924886,17.247364,14.828337,11.471728,0.755976,0.905953,16.583844,14.534868,11.207925,0.763008,0.911456,16.251859
21,Global,15.078288,10.592556,0.867602,0.936457,30.521661,15.268438,11.297473,0.864242,0.932799,26.809367,14.907471,11.032238,0.870585,0.935225,26.059121

In [10]:
print(summary_df.loc[summary_df["Storm Index"].isin([57, 68, 'Mean'])].to_latex(index=False, float_format="%.3f"))

\begin{tabular}{llllllllllllllll}
\toprule
Storm Index & Equation 1_RMSE & Equation 1_MAE & Equation 1_R2 & Equation 1_CC & Equation 1_BFE & Equation 2_RMSE & Equation 2_MAE & Equation 2_R2 & Equation 2_CC & Equation 2_BFE & Equation 3_RMSE & Equation 3_MAE & Equation 3_R2 & Equation 3_CC & Equation 3_BFE \\
\midrule
57 & 9.186 & 7.115 & 0.785 & 0.900 & 8.332 & 9.657 & 7.793 & 0.763 & 0.897 & 8.812 & 10.061 & 8.250 & 0.743 & 0.881 & 8.561 \\
68 & 21.684 & 15.933 & 0.967 & 0.985 & 21.878 & 23.371 & 18.995 & 0.962 & 0.984 & 23.228 & 21.083 & 16.912 & 0.969 & 0.986 & 20.970 \\
Mean & 14.633 & 10.914 & 0.767 & 0.925 & 17.247 & 14.828 & 11.472 & 0.756 & 0.906 & 16.584 & 14.535 & 11.208 & 0.763 & 0.911 & 16.252 \\
\bottomrule
\end{tabular}

In [11]:
print(summary_df.to_latex(index=False, float_format="%.3f").replace("_", " ").replace("Equation ", "Eq ").replace("Storm Index", "Storm"))

\begin{tabular}{llllllllllllllll}
\toprule
Storm & Eq 1 RMSE & Eq 1 MAE & Eq 1 R2 & Eq 1 CC & Eq 1 BFE & Eq 2 RMSE & Eq 2 MAE & Eq 2 R2 & Eq 2 CC & Eq 2 BFE & Eq 3 RMSE & Eq 3 MAE & Eq 3 R2 & Eq 3 CC & Eq 3 BFE \\
\midrule
54 & 9.176 & 6.120 & 0.792 & 0.920 & 11.066 & 11.585 & 8.862 & 0.669 & 0.916 & 16.184 & 12.200 & 9.334 & 0.633 & 0.936 & 15.867 \\
55 & 14.873 & 11.446 & 0.817 & 0.924 & 15.958 & 16.240 & 13.384 & 0.782 & 0.899 & 16.825 & 16.102 & 13.040 & 0.786 & 0.909 & 16.417 \\
56 & 16.063 & 10.936 & 0.434 & 0.870 & 19.312 & 10.639 & 8.542 & 0.752 & 0.878 & 12.855 & 11.069 & 8.717 & 0.731 & 0.877 & 13.648 \\
57 & 9.186 & 7.115 & 0.785 & 0.900 & 8.332 & 9.657 & 7.793 & 0.763 & 0.897 & 8.812 & 10.061 & 8.250 & 0.743 & 0.881 & 8.561 \\
58 & 8.458 & 6.020 & 0.827 & 0.940 & 13.608 & 9.013 & 6.801 & 0.804 & 0.929 & 13.498 & 8.467 & 6.228 & 0.827 & 0.926 & 13.939 \\
59 & 18.585 & 15.739 & 0.652 & 0.933 & 11.690 & 13.676 & 11.807 & 0.812 & 0.955 & 11.507 & 14.563 & 12.563 & 0.786 & 0.952 & 11.121 \\
60 & 23.885 & 17.550 & 0.591 & 0.925 & 35.776 & 17.859 & 14.196 & 0.772 & 0.938 & 20.260 & 18.325 & 14.755 & 0.760 & 0.937 & 19.980 \\
61 & 15.669 & 9.179 & 0.854 & 0.963 & 25.508 & 11.922 & 9.179 & 0.915 & 0.961 & 16.535 & 11.827 & 8.774 & 0.917 & 0.964 & 16.329 \\
62 & 12.475 & 10.340 & 0.638 & 0.912 & 10.320 & 13.974 & 11.807 & 0.546 & 0.835 & 12.900 & 13.457 & 11.221 & 0.579 & 0.851 & 12.298 \\
63 & 10.747 & 7.477 & 0.916 & 0.977 & 16.027 & 17.042 & 13.963 & 0.789 & 0.902 & 21.014 & 16.559 & 13.502 & 0.801 & 0.915 & 21.085 \\
64 & 8.406 & 6.356 & 0.864 & 0.933 & 9.423 & 9.881 & 7.914 & 0.812 & 0.912 & 11.855 & 9.710 & 7.799 & 0.818 & 0.918 & 11.414 \\
65 & 15.354 & 12.149 & 0.575 & 0.777 & 19.358 & 16.517 & 11.846 & 0.508 & 0.794 & 13.718 & 16.140 & 11.536 & 0.530 & 0.787 & 13.079 \\
66 & 15.705 & 11.809 & 0.662 & 0.887 & 21.214 & 20.919 & 16.088 & 0.400 & 0.720 & 26.436 & 21.019 & 15.917 & 0.394 & 0.748 & 26.715 \\
67 & 8.765 & 6.759 & 0.863 & 0.957 & 11.204 & 9.507 & 7.260 & 0.839 & 0.944 & 11.657 & 9.433 & 7.443 & 0.842 & 0.953 & 11.263 \\
68 & 21.684 & 15.933 & 0.967 & 0.985 & 21.878 & 23.371 & 18.995 & 0.962 & 0.984 & 23.228 & 21.083 & 16.912 & 0.969 & 0.986 & 20.970 \\
69 & 11.824 & 8.939 & 0.754 & 0.880 & 12.993 & 12.434 & 9.530 & 0.728 & 0.871 & 13.330 & 11.135 & 8.821 & 0.782 & 0.898 & 12.451 \\
70 & 18.157 & 13.536 & 0.810 & 0.938 & 19.354 & 21.146 & 15.651 & 0.743 & 0.934 & 23.785 & 19.434 & 14.307 & 0.783 & 0.938 & 23.072 \\
71 & 12.620 & 9.903 & 0.881 & 0.953 & 14.512 & 13.001 & 9.582 & 0.874 & 0.947 & 15.370 & 13.144 & 10.039 & 0.871 & 0.947 & 15.487 \\
72 & 30.306 & 22.817 & 0.859 & 0.962 & 37.042 & 26.312 & 16.568 & 0.894 & 0.949 & 31.583 & 26.719 & 17.017 & 0.890 & 0.950 & 32.485 \\
73 & 10.719 & 8.162 & 0.802 & 0.962 & 10.375 & 11.874 & 9.665 & 0.757 & 0.954 & 10.326 & 10.251 & 7.983 & 0.819 & 0.956 & 8.856 \\
Mean & 14.633 & 10.914 & 0.767 & 0.925 & 17.247 & 14.828 & 11.472 & 0.756 & 0.906 & 16.584 & 14.535 & 11.208 & 0.763 & 0.911 & 16.252 \\
Global & 15.078 & 10.593 & 0.868 & 0.936 & 30.522 & 15.268 & 11.297 & 0.864 & 0.933 & 26.809 & 14.907 & 11.032 & 0.871 & 0.935 & 26.059 \\
\bottomrule
\end{tabular}

In [12]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
54               11.065619      16.183557      15.866722
55               15.957827      16.825083      16.417254
56               19.312422      12.855017      13.648058
57                8.332227       8.811508       8.561342
58               13.607761       13.49815      13.938754
59               11.690355      11.506934      11.121084
60               35.776495      20.259943      19.979894
61                25.50768      16.534556       16.32869
62               10.320134      12.899981      12.298406
63                16.02663      21.014232      21.085079
64                9.422682      11.854581      11.413945
65               19.357769      13.718376      13.079389
66               21.213558      26.436026      26.715097
67               11.203738       11.65657      11.263004
68               21.877896      23.227678      20.970041
69               12.992782      13.330385      12.451084
70               19.353599      23.784731      23.071657
71               14.511539      15.369796      15.486503
72               37.041639      31.583442      32.485097
73               10.374919      10.326332       8.856075
Mean             17.247364      16.583844      16.251859
Global           30.521661      26.809367      26.059121

## Train storms

In [13]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TRAIN_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)

100%|██████████| 53/53 [00:28<00:00,  1.84it/s]

In [14]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[len(summary_df), "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

display(summary_df.mean())

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'



for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

Storm Index             27.0
Equation 1_RMSE     14.12022
Equation 1_MAE     10.798336
Equation 1_R2         0.7267
Equation 1_CC       0.909381
Equation 1_BFE       15.7291
Equation 2_RMSE    15.357771
Equation 2_MAE     11.953384
Equation 2_R2       0.683637
Equation 2_CC       0.891039
Equation 2_BFE     17.487093
Equation 3_RMSE    15.044167
Equation 3_MAE     11.824347
Equation 3_R2       0.701096
Equation 3_CC       0.895962
Equation 3_BFE     16.978854
dtype: object

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_CC,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_CC,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_CC,Equation 3_BFE
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,18.87628,15.678699,0.686373,0.859641,12.499886,16.692631,14.354029,0.754738,0.903678,12.914465,16.031464,13.73,0.773782,0.911157,12.396209
2,3,14.904854,11.632073,0.430113,0.71217,13.510849,18.519789,13.607535,0.120157,0.659589,16.679975,15.908807,12.51582,0.350755,0.673083,15.619399
3,4,14.095054,10.472318,0.809004,0.915002,15.053016,14.573592,11.443779,0.795815,0.924415,15.278006,12.524202,9.529419,0.849204,0.929801,13.192964
4,5,12.221424,9.863888,0.88822,0.943603,14.181651,15.974642,13.347459,0.809022,0.908592,19.67448,15.218147,12.666556,0.826682,0.919367,18.935738
5,6,15.77485,11.789898,0.833506,0.919287,20.371621,19.997275,15.04671,0.732447,0.866692,27.009672,20.378345,15.070956,0.722153,0.867898,26.766279
6,7,11.510856,8.753509,0.805233,0.920595,13.49761,15.61764,12.296356,0.641465,0.876607,17.135952,12.161474,9.718818,0.782593,0.915574,13.449344
7,8,11.753034,10.168218,0.758685,0.88125,12.380359,11.05971,9.018924,0.786316,0.891599,7.604727,12.051644,10.678982,0.746266,0.877783,9.168755
8,9,11.590136,8.993729,0.863362,0.963313,12.730152,10.171241,7.923095,0.894769,0.956686,10.066102,11.067485,8.751505,0.875407,0.959191,10.693658
9,10,7.75973,5.96097,0.883042,0.941369,7.846018,12.83273,8.2616,0.680128,0.903992,10.932851,9.713326,6.646768,0.816737,0.926262,8.12111
10,11,12.2273,9.081851,0.683226,0.849871,16.127453,13.080624,8.544735,0.637469,0.870877,18.785914,10.77317,7.077217,0.754091,0.878465,14.604487
11,12,19.442475,14.192824,0.653563,0.864052,32.216929,21.857664,16.206717,0.562146,0.800213,35.401398,22.89392,17.236183,0.519646,0.814494,37.58824
12,13,11.342942,8.739419,0.822964,0.929177,9.041338,11.788597,9.513038,0.80878,0.900488,10.749819,11.435988,9.270891,0.820048,0.905982,10.874261
13,14,13.918209,11.125828,0.786314,0.926887,17.276261,14.43547,11.668626,0.770136,0.92039,17.284004,13.193678,10.625222,0.807982,0.919791,17.241006
14,15,13.170199,10.185393,0.526667,0.828677,11.901193,13.418971,10.810997,0.508616,0.774651,14.435872,13.417331,10.564453,0.508736,0.772342,14.550571
15,16,22.902431,15.534207,0.753293,0.935515,26.803506,21.492503,15.562002,0.782734,0.926155,23.894286,21.230032,15.562303,0.788008,0.926893,23.256615
16,17,16.905229,12.776302,0.788848,0.939688,26.949501,20.425033,16.955366,0.691768,0.859055,28.577389,19.603238,16.181008,0.716072,0.898404,27.930723
17,18,10.470778,8.20392,0.94403,0.972689,9.77392,11.412867,9.255691,0.933506,0.969344,10.368194,12.20242,9.990232,0.923987,0.970566,11.674388
18,19,12.046033,8.806889,0.769064,0.921438,13.792362,10.272973,8.3888,0.832044,0.915056,10.556008,10.344628,8.263168,0.829693,0.914094,10.266964
19,20,11.557551,8.082112,0.908976,0.954369,13.56454,13.73453,9.232483,0.871456,0.942694,19.985152,13.319297,8.830381,0.879111,0.947194,19.494463
20,21,15.164446,9.779656,0.500634,0.798739,21.600007,15.78566,10.986614,0.458883,0.857653,22.184803,13.548314,9.01412,0.601401,0.85873,18.902464
21,22,10.195429,8.202636,0.922673,0.970841,10.551285,12.370539,9.953799,0.886159,0.973865,14.764067,12.662591,10.603602,0.88072,0.972436,14.864032
22,23,19.797478,17.009984,0.811412,0.960346,21.053587,22.847645,18.859317,0.748825,0.947907,27.181591,24.309009,20.486444,0.715666,0.945259,28.324496
23,24,9.261367,6.530768,0.879234,0.953753,7.075979,8.028396,6.033195,0.909249,0.959296,6.728965,9.835308,7.472644,0.863802,0.955757,7.390566
24,25,9.684086,7.102062,0.84916,0.934456,14.543527,19.575272,15.888313,0.383666,0.717269,26.620336,19.511585,15.088451,0.38767,0.755835,25.959558
25,26,9.044125,7.426064,0.811709,0.917313,9.111573,9.135255,6.819155,0.807896,0.91358,9.297456,9.368147,7.825822,0.797976,0.90856,9.911551
26,27,12.718142,9.939776,0.625946,0.935544,13.519281,17.498803,14.52092,0.291885,0.904507,18.375124,18.859048,15.910571,0.177518,0.915431,19.543617
27,28,16.927197,13.046251,0.310014,0.744507,25.961848,17.104924,14.333683,0.295449,0.679994,22.854206,18.800652,15.473404,0.148831,0.658178,26.71761
28,29,16.026587,12.042834,0.459196,0.75961,17.588593,14.491203,11.401659,0.557853,0.81795,14.660821,15.382901,12.406752,0.501765,0.798621,15.979371
29,30,12.235795,9.791826,0.685912,0.943802,11.410037,11.546615,8.232901,0.720298,0.8941,11.06274,10.135424,7.414431,0.784488,0.915273,9.172876
30,31,10.818658,8.460108,0.903598,0.953329,10.900279,10.968959,9.153793,0.900901,0.952202,11.007485,11.42586,9.139279,0.892473,0.951684,10.437889
31,32,22.496057,14.377355,0.913907,0.978631,35.723651,19.16133,12.570043,0.93754,0.97636,31.342221,19.058299,12.966208,0.938209,0.974215,30.856028
32,33,20.114583,16.767603,0.37791,0.878305,22.382459,17.601948,14.118765,0.523621,0.860163,23.377719,17.041957,13.542958,0.55345,0.863121,22.956787
33,34,9.800442,8.636324,0.728703,0.927085,7.835354,9.710887,7.341702,0.733639,0.914424,6.593158,9.345441,7.675634,0.753309,0.923222,6.943716
34,35,15.763345,13.277113,0.531324,0.868225,16.745217,14.795637,12.762459,0.587101,0.886305,17.790308,14.308049,11.879535,0.613867,0.866374,18.676198
35,36,17.545864,14.420478,0.816743,0.922717,15.162006,28.89985,23.136798,0.502832,0.871183,28.788817,29.79006,23.736898,0.471732,0.877258,29.662032
36,37,9.906489,7.757546,0.894539,0.961668,9.274908,10.989319,8.852519,0.870225,0.945135,10.606267,9.778936,8.027378,0.897238,0.94997,9.84078
37,38,25.881059,21.845149,0.874271,0.954783,28.021031,28.376305,24.574418,0.848859,0.93882,32.038336,29.610394,25.704967,0.835427,0.940671,31.006278
38,39,11.768724,9.457291,0.510584,0.756767,11.998915,10.158923,7.601133,0.635318,0.818274,9.582034,11.483807,9.252625,0.533995,0.810021,11.370675
39,40,12.309642,8.990816,0.895481,0.951728,16.688398,15.976354,10.999187,0.82394,0.920655,29.880048,15.393871,10.457118,0.836544,0.922748,27.786917
40,41,21.148503,14.969413,0.475232,0.914851,24.627534,18.080943,13.625714,0.616425,0.890408,19.90797,15.855433,12.337913,0.705039,0.908082,17.138878
41,42,11.914407,9.291346,0.856515,0.931777,15.130422,12.507086,10.066902,0.841885,0.93443,14.658983,12.664126,10.139188,0.837889,0.938606,14.879048
42,43,13.455834,9.57457,0.591147,0.948192,13.648082,10.803533,8.016959,0.736441,0.928467,10.698434,10.91308,7.993311,0.731069,0.940068,10.180479
43,44,18.116836,13.700332,0.670294,0.875399,19.561639,22.066797,18.472264,0.510851,0.855946,19.560642,22.787602,19.514211,0.478373,0.850528,20.9133
44,45,7.453746,5.539695,0.907953,0.961123,8.858389,9.569686,7.725846,0.848276,0.928378,10.090599,9.111074,7.319153,0.862469,0.940006,9.633369
45,46,6.597455,5.194652,0.928384,0.969744,6.873013,10.147259,8.429135,0.830583,0.937477,11.946508,10.648914,9.350839,0.813418,0.945492,10.724841
46,47,10.993807,8.632018,0.941027,0.97689,11.852645,15.873885,13.119098,0.877052,0.964116,17.048107,15.634097,12.62466,0.880738,0.971219,17.08208
47,48,17.776336,13.612109,0.528915,0.822305,13.30293,21.229397,18.250388,0.328123,0.834716,25.800223,19.497818,16.600235,0.433257,0.814093,19.779685
48,49,12.855478,9.829043,0.941338,0.971445,16.041513,11.361616,8.280829,0.954179,0.977149,12.132095,11.14558,8.261655,0.955905,0.978411,10.974497
49,50,16.026181,10.187179,0.953851,0.979911,19.472377,14.371658,9.442647,0.962888,0.984148,18.700372,14.266006,9.426151,0.963432,0.985149,18.379122
50,51,12.172601,9.228473,0.776709,0.913268,11.949536,16.013768,10.977873,0.613551,0.845455,15.403776,13.279856,9.183718,0.734239,0.886412,12.6583
51,52,12.736081,10.386474,0.736782,0.910593,11.503522,12.003328,9.528056,0.766198,0.911955,10.778691,13.047416,10.741461,0.723756,0.906375,11.361811
52,53,11.710069,9.119628,0.776055,0.912096,10.373306,12.237379,9.829417,0.755433,0.882532,13.318946,12.464392,10.036921,0.746275,0.879453,12.922744
53,NaN,25.485461,18.143193,-0.466527,0.858856,23.781271,25.313226,18.185888,-0.446772,0.829486,24.699805,22.907225,16.172231,-0.184814,0.850389,21.122502
54,Mean,14.12022,10.798336,0.7267,0.909381,15.7291,15.357771,11.953384,0.683637,0.891039,17.487093,15.044167,11.824347,0.701096,0.895962,16.978854
55,Global,14.88078,10.906157,0.847037,0.922072,28.66396,16.328299,12.09745,0.81583,0.904899,32.734697,16.12661,11.977824,0.820352,0.909232,32.528093

In [15]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
1                      NaN            NaN            NaN
2                12.499886      12.914465      12.396209
3                13.510849      16.679975      15.619399
4                15.053016      15.278006      13.192964
5                14.181651       19.67448      18.935738
6                20.371621      27.009672      26.766279
7                 13.49761      17.135952      13.449344
8                12.380359       7.604727       9.168755
9                12.730152      10.066102      10.693658
10                7.846018      10.932851        8.12111
11               16.127453      18.785914      14.604487
12               32.216929      35.401398       37.58824
13                9.041338      10.749819      10.874261
14               17.276261      17.284004      17.241006
15               11.901193      14.435872      14.550571
16               26.803506      23.894286      23.256615
17               26.949501      28.577389      27.930723
18                 9.77392      10.368194      11.674388
19               13.792362      10.556008      10.266964
20                13.56454      19.985152      19.494463
21               21.600007      22.184803      18.902464
22               10.551285      14.764067      14.864032
23               21.053587      27.181591      28.324496
24                7.075979       6.728965       7.390566
25               14.543527      26.620336      25.959558
26                9.111573       9.297456       9.911551
27               13.519281      18.375124      19.543617
28               25.961848      22.854206       26.71761
29               17.588593      14.660821      15.979371
30               11.410037       11.06274       9.172876
31               10.900279      11.007485      10.437889
32               35.723651      31.342221      30.856028
33               22.382459      23.377719      22.956787
34                7.835354       6.593158       6.943716
35               16.745217      17.790308      18.676198
36               15.162006      28.788817      29.662032
37                9.274908      10.606267        9.84078
38               28.021031      32.038336      31.006278
39               11.998915       9.582034      11.370675
40               16.688398      29.880048      27.786917
41               24.627534       19.90797      17.138878
42               15.130422      14.658983      14.879048
43               13.648082      10.698434      10.180479
44               19.561639      19.560642        20.9133
45                8.858389      10.090599       9.633369
46                6.873013      11.946508      10.724841
47               11.852645      17.048107       17.08208
48                13.30293      25.800223      19.779685
49               16.041513      12.132095      10.974497
50               19.472377      18.700372      18.379122
51               11.949536      15.403776        12.6583
52               11.503522      10.778691      11.361811
53               10.373306      13.318946      12.922744
NaN              23.781271      24.699805      21.122502
Mean               15.7291      17.487093      16.978854
Global            28.66396      32.734697      32.528093

In [16]:

storms = range(54, 74)
parent_folder = 'unconstrained-derived-figures'

for storm_number in storms:
    # We use f-strings with double {{ }} to escape the LaTeX braces
    # and single { } for the Python variables.
    latex_code = f"""
\\begin{{figure}}[ht]
    \\centering
    \\includegraphics[width=\\textwidth]{{{parent_folder}/storm_{storm_number}.png}}
    \\caption{{Reconstruction of storm {storm_number} using the Equations generated from the unconstrained symbolic regression with the derived features}}\\label{{fig:unconstrained-storm-{storm_number}}}
\\end{{figure}}
"""
    print(latex_code)

\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_54.png}
    \caption{Reconstruction of storm 54 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-54}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_55.png}
    \caption{Reconstruction of storm 55 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-55}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_56.png}
    \caption{Reconstruction of storm 56 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-56}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_57.png}
    \caption{Reconstruction of storm 57 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-57}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_58.png}
    \caption{Reconstruction of storm 58 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-58}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_59.png}
    \caption{Reconstruction of storm 59 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-59}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_60.png}
    \caption{Reconstruction of storm 60 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-60}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_61.png}
    \caption{Reconstruction of storm 61 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-61}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_62.png}
    \caption{Reconstruction of storm 62 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-62}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_63.png}
    \caption{Reconstruction of storm 63 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-63}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_64.png}
    \caption{Reconstruction of storm 64 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-64}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_65.png}
    \caption{Reconstruction of storm 65 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-65}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_66.png}
    \caption{Reconstruction of storm 66 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-66}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_67.png}
    \caption{Reconstruction of storm 67 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-67}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_68.png}
    \caption{Reconstruction of storm 68 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-68}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_69.png}
    \caption{Reconstruction of storm 69 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-69}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_70.png}
    \caption{Reconstruction of storm 70 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-70}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_71.png}
    \caption{Reconstruction of storm 71 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-71}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_72.png}
    \caption{Reconstruction of storm 72 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-72}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_73.png}
    \caption{Reconstruction of storm 73 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-73}
\end{figure}