# Test notebook

The purpose of this notebook is to test an equation and compare them with the baselines: Burton, MBR, and DDM1, 2 and 3. We will also plot each storm and get the metrics for the equation.

The only cell that we have to modify is the following one, where we can change the features, the mode (template or default) and the output directory for the plots.
Raw EQ is the equation that we want to test, the raw version generated from the train_script.py file.

In [1]:
import os

FEATURES = ["P_dyn", "VBs", "epsilon", "DST"]
MODE = "default"  # 'template' or 'default'
OUTPUT_DIR = "unconstrained_derived_features_review"
RAW_EQS = [
    "((sqrt(P_dyn - -0.887826) * VBs) - square(0.6033792 * (DST + -22.420992))) / (DST + -825.26373)",
    "(VBs * (sqrt(P_dyn + square((DST * -0.008792949) + -1.9299145)) * -0.0009785303)) + square((DST * 0.01791331) + -0.60905385)",
    "square(0.5820395 + (DST * -0.018421166)) - ((sqrt(P_dyn + 1.1339003) * VBs) * 0.001091036)",
    "((VBs * -0.0011102495) * sqrt(P_dyn + 1.0975075)) + (0.00036096844 * square(DST + -29.48951))",
]

start_eq_number = 4

output_folder = OUTPUT_DIR
# Count number of existing subfolders
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import sympy as sp
from tqdm import tqdm

from sympy.printing import latex

# Internal module imports
import storm_dates
import baseline_models

# from evaluation_engine import UnifiedModel, simulate_storm, compute_features
from evaluation_engine import EquationModel, simulate_storm
from train_script import load_and_preprocess, compute_features

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

/mnt/data/symbolic-regression-dst-public-repo/.venv/lib/python3.12/site-packages/spacepy/time.py:2448: UserWarning: Leapseconds may be out of date. Use spacepy.toolbox.update(leapsecs=True)
  _read_leaps()

In [3]:
raw_data = load_and_preprocess()
data = compute_features(raw_data)

In [4]:
def predict_and_plot_storm(
    model, eqs, start, end, storm_df, storm_id, save_path, eq_start_index=0
):
    # 1. Generate Predictions
    y_true = storm_df[start:end]["DST"].values
    colors = ["blue", "yellow", "green", "orange", "purple", "cyan", "magenta"]
    res_eqs = []

    metrics_info = []

    for eq_index, eq in enumerate(eqs):
        res_eq = simulate_storm(model[eq], storm_df)
        res_eq = res_eq[start:end]["DST_pred"].values
        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        metrics_info.append(m_eq)
        # string_title += f"Evaluation for Equation {eq_index + 1} ({colors[eq_index]}): ${model[eq].latex_str()}$ \n"

        res_eqs.append(res_eq)

    # 2. Calculate Metrics

    # 3. Setup Figure (3 Columns)
    fig, axs = plt.subplots(1, 3, figsize=(24, 9), constrained_layout=True)

    # Column 1: Time Series
    axs[0].plot(
        storm_df[start:end].index,
        y_true,
        color="black",
        label="Observed",
        alpha=0.6,
        linewidth=2,
    )

    for eq_index, res_eq in enumerate(res_eqs):

        axs[0].plot(
            storm_df[start:end].index,
            res_eqs[eq_index],
            color=colors[eq_index],
            linestyle="--",
            # label=f"Equation {eq_index + eq_start_index}",
            label=None,
            linewidth=1.5,
        )

    axs[0].tick_params(axis="both", which="major", labelsize=20)
    axs[0].tick_params(axis="both", which="minor", labelsize=18)
    axs[0].legend(fontsize=20)
    axs[0].set_ylabel("Dst (nT)", fontsize=20)
    axs[0].set_xlabel("Date", fontsize=20)
    axs[0].grid(True)
    axs[0].set_xlim(start, end)
    axs[0].set_title("Storm Reconstruction", fontsize=24)

    axs[0].xaxis.set_major_locator(MultipleLocator(2))
    
    if len(axs[0].xaxis.get_ticklabels()) > 6:    
        for label in axs[0].xaxis.get_ticklabels()[1::2]:
            label.set_visible(False)

    diffs = []

    for eq_index, res_eq in enumerate(res_eqs):
        diff_eq = res_eq - y_true
        diffs.append(diff_eq)

        # axs[1].plot(storm_df[start:end].index, diff_eq, color=colors[eq_index], label=f"Equation {eq_index + eq_start_index} Error")
        axs[1].plot(
            storm_df[start:end].index, diff_eq, color=colors[eq_index], label=None
        )

    axs[1].axhline(0, color="black", linestyle="--")

    title_metrics = f"Error Comparison\n"

    for eq_index, m_eq in enumerate(metrics_info):
        title_metrics += f"Eq {eq_index + eq_start_index} ({colors[eq_index]}): MAE={m_eq['MAE']:.2f}, RMSE={m_eq['RMSE']:.2f}, R²={m_eq['R2']:.3f}, BFE={m_eq['BFE']:.3f}\n"

    # axs[1].set_title(title_metrics, fontsize=18)
    axs[1].set_title("Equation error", fontsize=24)
    axs[1].set_ylabel("Error (nT)", fontsize=20)
    axs[1].set_xlabel("Date", fontsize=20)
    axs[1].grid(True)
    axs[1].set_xlim(start, end)
    axs[1].tick_params(axis="both", which="major", labelsize=20)
    axs[1].tick_params(axis="both", which="minor", labelsize=18)
    
    axs[1].xaxis.set_major_locator(MultipleLocator(2))

    if len(axs[1].xaxis.get_ticklabels()) > 6:    
        for label in axs[1].xaxis.get_ticklabels()[1::2]:
            label.set_visible(False)


    # Column 3: BFE
    baseline_models.plot_evaluation_bfe_multi(
        axs[2],
        y_true,
        res_eqs,
        [f"Equation {i+ eq_start_index}" for i in range(len(eqs))],
        [colors[i] for i in range(len(eqs))],
        fontsize=20,
        plot_legend=False,
    )

    string_title = f"Storm {storm_id} Reconstruction\n{title_metrics}"
    fig.suptitle(string_title, fontsize=24)
    plt.savefig(save_path)
    plt.close()

In [5]:
def save_prediction_data(model, eqs, start, end, storm_df, output_path):
    """
    Generates and saves a CSV with observed and predicted DST and dDST/dt.
    """
    # 1. Observed Data
    # Real dDST is calculated as the difference to the next hour
    real_dst = storm_df[start:end]["DST"].values
    real_ddst = storm_df[start:end]["DST"].diff().shift(-1).values

    # 2. Equation Predictions
    # We need the iterative predictions for DST
    pred_dst_eqs = []
    for eq_index, eq in enumerate(eqs):
        pred_dst_eq = simulate_storm(model[eq], storm_df)
        if model[eq].is_template:
            pred_dst_eq = pred_dst_eq[start:end][
                ["DST_pred", "dDST", "injection_component", "decay_component"]
            ]
        else:
            pred_dst_eq = pred_dst_eq[start:end][["DST_pred", "dDST"]]
        pred_dst_eqs.append(pred_dst_eq)
        
    # 3. Baseline Predictions (Burton & OBM)
    
    # 4. Construct Comprehensive DataFrame

    if model[eq].is_template:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Injection_Component": pred_dst_eq["injection_component"].values,
                "Decay_Component": pred_dst_eq["decay_component"].values,
                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values
            results_df[f"Injection_Component_{eq_index+1}"] = pred_dst_eq["injection_component"].values
            results_df[f"Decay_Component_{eq_index+1}"] = pred_dst_eq["decay_component"].values
        
    else:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,                
            }
        ).set_index("Timestamp")
        
        for eq_index, pred_dst_eq in enumerate(pred_dst_eqs):
            results_df[f"Pred_DST_Equation_{eq_index+1}"] = pred_dst_eq["DST_pred"].values
            results_df[f"Pred_dDST_dt_Equation_{eq_index+1}"] = pred_dst_eq["dDST"].values


    results_df.to_csv(output_path)
    return results_df

## Test storms

In [6]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TEST_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
        eq_start_index=start_eq_number
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)
    
with open(os.path.join(OUTPUT_DIR, 'equation.txt'), 'a') as f:
    f.write(f'Equation: {RAW_EQ}\n')            
    f.write(f'LaTeX: {latex(models[RAW_EQ].latex_str())}\n')

  0%|          | 0/20 [00:00<?, ?it/s]

100%|██████████| 20/20 [00:09<00:00,  2.17it/s]

In [7]:
storms[0].columns

Index(['Observed_DST', 'Real_dDST_dt', 'Pred_DST_Equation_1',
       'Pred_dDST_dt_Equation_1', 'Pred_DST_Equation_2',
       'Pred_dDST_dt_Equation_2', 'Pred_DST_Equation_3',
       'Pred_dDST_dt_Equation_3', 'Pred_DST_Equation_4',
       'Pred_dDST_dt_Equation_4'],
      dtype='object')

In [8]:
metrics = ["RMSE", "MAE", "R2", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[storm_indices[storm_index], "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]


global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'

for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_BFE,Equation 4_RMSE,Equation 4_MAE,Equation 4_R2,Equation 4_BFE
54,54,8.06495,6.12139,0.839467,11.308646,8.314912,6.188954,0.829362,11.418362,9.008634,7.113426,0.799701,11.571721,8.779165,6.908173,0.809775,11.484946
55,55,15.909189,12.481491,0.790824,18.405616,16.489959,12.970961,0.775273,18.668759,17.375463,13.731527,0.750489,19.559242,17.007616,13.515262,0.760942,19.159893
56,56,12.654988,9.273064,0.648448,15.835122,12.133223,9.310718,0.676839,14.531033,13.363784,11.014805,0.607965,15.721662,13.103475,10.590417,0.623089,15.541541
57,57,10.005577,7.705164,0.745485,10.435467,10.129723,8.054942,0.739129,11.340401,9.540979,7.609833,0.768572,12.025851,9.483605,7.530154,0.771347,11.574112
58,58,9.828411,7.555463,0.766595,14.806299,9.42175,7.334547,0.78551,14.755529,9.19216,6.387633,0.795836,15.625816,9.198578,6.490953,0.795551,15.365378
59,59,13.734735,11.745709,0.810036,9.730955,13.851601,11.906246,0.80679,10.250493,12.169085,10.187595,0.850877,9.420286,12.340322,10.402339,0.84665,9.42057
60,60,19.322303,13.056422,0.732634,29.309573,17.574061,12.932002,0.778826,24.013474,18.267135,11.955447,0.761037,28.250562,18.338374,12.103383,0.75917,28.23741
61,61,10.938646,7.963481,0.928666,14.228484,12.772821,8.617351,0.902738,17.511873,10.704728,8.287751,0.931685,14.32901,10.645508,8.227253,0.932438,13.88645
62,62,12.965947,10.539221,0.609154,12.92504,13.310303,11.044571,0.588118,12.626724,11.35094,9.076804,0.700456,12.9414,11.64289,9.345714,0.684849,12.910975
63,63,13.845406,10.90738,0.860726,17.904959,15.512114,12.493567,0.825177,20.096805,14.785816,12.000925,0.841164,17.960444,14.659398,11.92777,0.843869,18.078444
64,64,9.289149,7.05152,0.833839,10.507357,9.9318,7.740701,0.810053,11.165151,10.060064,7.944993,0.805115,11.159736,9.893781,7.756044,0.811505,11.042577
65,65,14.800386,10.436659,0.605123,15.900504,16.275888,11.645217,0.522465,17.600035,14.033175,10.197968,0.645,16.576042,14.164707,10.196208,0.638315,16.427183
66,66,16.903656,13.666191,0.607928,18.624153,17.966969,14.870027,0.557051,20.191221,18.102178,15.282932,0.550359,19.894517,17.959402,15.043487,0.557424,19.766725
67,67,11.494214,8.583674,0.765167,15.538606,10.545972,7.83615,0.802315,13.115315,11.315927,8.546311,0.772396,16.146075,11.253346,8.495227,0.774906,15.908651
68,68,24.45052,18.647833,0.958549,24.482359,25.056073,19.164553,0.956471,25.587948,28.616194,20.917918,0.943222,30.78771,28.428597,21.074004,0.943964,29.89179
69,69,11.506433,8.35398,0.7673,12.459194,11.110808,8.203819,0.783027,12.165712,11.001064,8.271008,0.787292,12.135229,11.079425,8.242489,0.784251,12.196959
70,70,19.571329,14.621507,0.779721,20.840222,18.575476,13.663729,0.801568,21.490292,16.946393,12.185875,0.834847,19.225159,17.37165,12.555278,0.826454,19.343381
71,71,11.555552,8.322122,0.900342,13.533011,11.495403,8.147307,0.901377,13.166581,11.652619,7.737422,0.89866,13.214889,11.517407,7.754826,0.900999,13.190531
72,72,16.533743,11.844475,0.958052,18.783611,17.477443,11.768847,0.953126,17.462536,18.093639,13.082546,0.949763,22.066654,17.26402,12.543123,0.954264,19.846252
73,73,13.047068,11.055034,0.706678,11.829332,12.78079,11.076743,0.718528,11.474466,11.555921,9.455685,0.769894,10.799526,11.685373,9.577903,0.764709,10.837809
20,Mean,13.82111,10.496589,0.780737,15.869426,14.036355,10.748548,0.775687,15.931636,13.856795,10.54942,0.788216,16.470577,13.790832,10.514,0.789224,16.205579
21,Global,14.186202,10.359382,0.882805,25.030568,14.302649,10.564052,0.880873,26.399514,14.068879,10.237833,0.884735,29.233605,14.038001,10.22544,0.885241,28.140158

In [9]:
print(summary_df.to_latex(index=False, float_format="%.3f").replace("_", " ").replace("Equation ", "Eq ").replace("Storm Index", "Storm"))

\begin{tabular}{lllllllllllllllll}
\toprule
Storm & Eq 1 RMSE & Eq 1 MAE & Eq 1 R2 & Eq 1 BFE & Eq 2 RMSE & Eq 2 MAE & Eq 2 R2 & Eq 2 BFE & Eq 3 RMSE & Eq 3 MAE & Eq 3 R2 & Eq 3 BFE & Eq 4 RMSE & Eq 4 MAE & Eq 4 R2 & Eq 4 BFE \\
\midrule
54 & 8.065 & 6.121 & 0.839 & 11.309 & 8.315 & 6.189 & 0.829 & 11.418 & 9.009 & 7.113 & 0.800 & 11.572 & 8.779 & 6.908 & 0.810 & 11.485 \\
55 & 15.909 & 12.481 & 0.791 & 18.406 & 16.490 & 12.971 & 0.775 & 18.669 & 17.375 & 13.732 & 0.750 & 19.559 & 17.008 & 13.515 & 0.761 & 19.160 \\
56 & 12.655 & 9.273 & 0.648 & 15.835 & 12.133 & 9.311 & 0.677 & 14.531 & 13.364 & 11.015 & 0.608 & 15.722 & 13.103 & 10.590 & 0.623 & 15.542 \\
57 & 10.006 & 7.705 & 0.745 & 10.435 & 10.130 & 8.055 & 0.739 & 11.340 & 9.541 & 7.610 & 0.769 & 12.026 & 9.484 & 7.530 & 0.771 & 11.574 \\
58 & 9.828 & 7.555 & 0.767 & 14.806 & 9.422 & 7.335 & 0.786 & 14.756 & 9.192 & 6.388 & 0.796 & 15.626 & 9.199 & 6.491 & 0.796 & 15.365 \\
59 & 13.735 & 11.746 & 0.810 & 9.731 & 13.852 & 11.906 & 0.807 & 10.250 & 12.169 & 10.188 & 0.851 & 9.420 & 12.340 & 10.402 & 0.847 & 9.421 \\
60 & 19.322 & 13.056 & 0.733 & 29.310 & 17.574 & 12.932 & 0.779 & 24.013 & 18.267 & 11.955 & 0.761 & 28.251 & 18.338 & 12.103 & 0.759 & 28.237 \\
61 & 10.939 & 7.963 & 0.929 & 14.228 & 12.773 & 8.617 & 0.903 & 17.512 & 10.705 & 8.288 & 0.932 & 14.329 & 10.646 & 8.227 & 0.932 & 13.886 \\
62 & 12.966 & 10.539 & 0.609 & 12.925 & 13.310 & 11.045 & 0.588 & 12.627 & 11.351 & 9.077 & 0.700 & 12.941 & 11.643 & 9.346 & 0.685 & 12.911 \\
63 & 13.845 & 10.907 & 0.861 & 17.905 & 15.512 & 12.494 & 0.825 & 20.097 & 14.786 & 12.001 & 0.841 & 17.960 & 14.659 & 11.928 & 0.844 & 18.078 \\
64 & 9.289 & 7.052 & 0.834 & 10.507 & 9.932 & 7.741 & 0.810 & 11.165 & 10.060 & 7.945 & 0.805 & 11.160 & 9.894 & 7.756 & 0.812 & 11.043 \\
65 & 14.800 & 10.437 & 0.605 & 15.901 & 16.276 & 11.645 & 0.522 & 17.600 & 14.033 & 10.198 & 0.645 & 16.576 & 14.165 & 10.196 & 0.638 & 16.427 \\
66 & 16.904 & 13.666 & 0.608 & 18.624 & 17.967 & 14.870 & 0.557 & 20.191 & 18.102 & 15.283 & 0.550 & 19.895 & 17.959 & 15.043 & 0.557 & 19.767 \\
67 & 11.494 & 8.584 & 0.765 & 15.539 & 10.546 & 7.836 & 0.802 & 13.115 & 11.316 & 8.546 & 0.772 & 16.146 & 11.253 & 8.495 & 0.775 & 15.909 \\
68 & 24.451 & 18.648 & 0.959 & 24.482 & 25.056 & 19.165 & 0.956 & 25.588 & 28.616 & 20.918 & 0.943 & 30.788 & 28.429 & 21.074 & 0.944 & 29.892 \\
69 & 11.506 & 8.354 & 0.767 & 12.459 & 11.111 & 8.204 & 0.783 & 12.166 & 11.001 & 8.271 & 0.787 & 12.135 & 11.079 & 8.242 & 0.784 & 12.197 \\
70 & 19.571 & 14.622 & 0.780 & 20.840 & 18.575 & 13.664 & 0.802 & 21.490 & 16.946 & 12.186 & 0.835 & 19.225 & 17.372 & 12.555 & 0.826 & 19.343 \\
71 & 11.556 & 8.322 & 0.900 & 13.533 & 11.495 & 8.147 & 0.901 & 13.167 & 11.653 & 7.737 & 0.899 & 13.215 & 11.517 & 7.755 & 0.901 & 13.191 \\
72 & 16.534 & 11.844 & 0.958 & 18.784 & 17.477 & 11.769 & 0.953 & 17.463 & 18.094 & 13.083 & 0.950 & 22.067 & 17.264 & 12.543 & 0.954 & 19.846 \\
73 & 13.047 & 11.055 & 0.707 & 11.829 & 12.781 & 11.077 & 0.719 & 11.474 & 11.556 & 9.456 & 0.770 & 10.800 & 11.685 & 9.578 & 0.765 & 10.838 \\
Mean & 13.821 & 10.497 & 0.781 & 15.869 & 14.036 & 10.749 & 0.776 & 15.932 & 13.857 & 10.549 & 0.788 & 16.471 & 13.791 & 10.514 & 0.789 & 16.206 \\
Global & 14.186 & 10.359 & 0.883 & 25.031 & 14.303 & 10.564 & 0.881 & 26.400 & 14.069 & 10.238 & 0.885 & 29.234 & 14.038 & 10.225 & 0.885 & 28.140 \\
\bottomrule
\end{tabular}

## Train storms

In [10]:
storms = []
storm_indices = []
models = {}

for RAW_EQ in RAW_EQS:
    model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
    models[RAW_EQ] = model
    
    
test_storms = storm_dates.TRAIN_STORMS_SYMBOLIC_REGRESSION

for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        models,
        RAW_EQS,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
        eq_start_index=start_eq_number
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            models, RAW_EQS, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)

100%|██████████| 53/53 [00:24<00:00,  2.16it/s]

In [11]:
metrics = ["RMSE", "MAE", "R2", "BFE"]
equations = [f"Equation {i+1}" for i in range(len(RAW_EQS))]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    summary_df.loc[len(summary_df), "Storm Index"] = storm_indices[storm_index]


for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    
    for eq_index in range(len(RAW_EQS)):
    
        res_eq = storm[f"Pred_DST_Equation_{eq_index+1}"].values
    

        m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)
        
        for metric in metrics:
            summary_df.loc[storm_indices[storm_index], f"Equation {eq_index+1}_{metric}"] = m_eq[metric]
        
        

display(summary_df.mean())

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values

summary_df.loc[len(summary_df), "Storm Index"] = 'Global'



for eq_index in range(len(RAW_EQS)):
    res_eq = global_data[f"Pred_DST_Equation_{eq_index+1}"].values
    m_eq = baseline_models.get_all_metrics_dict(y_true, res_eq)    
    for metric in metrics:
        summary_df.loc[len(summary_df) - 1, f"Equation {eq_index+1}_{metric}"] = m_eq[metric]


display(summary_df)

Storm Index             27.0
Equation 1_RMSE    15.375558
Equation 1_MAE     11.806516
Equation 1_R2       0.658267
Equation 1_BFE     16.483959
Equation 2_RMSE    15.077207
Equation 2_MAE     11.723353
Equation 2_R2       0.682034
Equation 2_BFE     16.163217
Equation 3_RMSE    15.357253
Equation 3_MAE     11.845362
Equation 3_R2       0.669276
Equation 3_BFE     16.708428
Equation 4_RMSE    15.348624
Equation 4_MAE     11.827608
Equation 4_R2       0.670913
Equation 4_BFE     16.711568
dtype: object

,Storm Index,Equation 1_RMSE,Equation 1_MAE,Equation 1_R2,Equation 1_BFE,Equation 2_RMSE,Equation 2_MAE,Equation 2_R2,Equation 2_BFE,Equation 3_RMSE,Equation 3_MAE,Equation 3_R2,Equation 3_BFE,Equation 4_RMSE,Equation 4_MAE,Equation 4_R2,Equation 4_BFE
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,19.786739,16.400743,0.655389,15.526419,18.468655,15.276102,0.699772,12.785224,20.411017,17.281744,0.633301,17.116085,20.476528,17.339641,0.630943,17.161798
2,3,24.346791,18.600828,-0.520606,19.658886,22.82749,17.445611,-0.336748,19.382111,23.038908,17.613517,-0.361623,19.490141,23.145761,17.607503,-0.374283,19.351253
3,4,13.452537,10.641707,0.82602,9.648251,12.931327,10.120103,0.839241,10.238934,11.205866,8.788781,0.87928,8.65772,11.678748,9.191319,0.868876,9.007216
4,5,16.036288,13.357608,0.807545,18.572799,14.384549,12.036484,0.845149,15.224579,17.156375,14.143412,0.779722,19.860439,16.943843,14.076565,0.785146,19.434656
5,6,17.171628,13.695961,0.802716,22.417481,17.058017,14.035711,0.805318,20.990618,18.551237,14.629868,0.769743,24.116157,18.032454,14.408473,0.782441,23.473429
6,7,15.884376,12.542644,0.629113,16.641476,14.009766,11.214961,0.711489,13.625485,15.55178,12.414511,0.644482,16.91186,15.524904,12.379606,0.64571,16.883632
7,8,10.388805,7.64808,0.811454,6.639697,11.149353,8.950824,0.782838,7.69351,10.340096,8.462847,0.813218,6.909967,10.29514,8.310868,0.814839,6.795484
8,9,10.93844,7.767137,0.878296,11.907346,10.509656,7.829536,0.88765,10.549047,12.183747,8.905623,0.849007,13.225507,11.855093,8.601406,0.857043,12.745111
9,10,13.705285,10.513525,0.63515,12.40907,12.12071,9.275784,0.714639,10.81744,12.796081,9.575812,0.681952,11.798232,12.776926,9.578499,0.682904,11.766988
10,11,15.301308,11.466448,0.503928,19.469273,13.179697,9.340128,0.631957,16.25735,13.267183,9.229339,0.627055,17.057575,13.534994,9.494859,0.611846,17.424563
11,12,18.12695,14.248768,0.698858,25.472262,19.196294,15.262391,0.66228,28.531491,17.73795,13.994631,0.711644,25.999424,17.86935,14.133631,0.707356,26.008432
12,13,16.704633,12.035339,0.616042,15.342755,14.399409,10.347887,0.714702,12.049933,15.458511,10.755102,0.67119,14.856913,15.648864,10.870179,0.663042,14.778065
13,14,15.234805,12.194845,0.743974,14.311066,14.431583,11.584041,0.77026,15.210475,13.283604,10.453912,0.805356,13.872992,13.507362,10.631141,0.798743,13.827108
14,15,14.439244,11.269566,0.431054,12.018502,14.151732,10.942868,0.453486,11.724363,12.777473,9.846265,0.554475,10.867242,12.991581,10.003434,0.539419,10.9422
15,16,21.655286,14.613239,0.77943,25.658683,20.605676,14.565422,0.800294,24.665073,23.961953,15.559042,0.729938,28.214698,23.097646,15.237867,0.749069,27.210194
16,17,17.674036,14.323566,0.769206,19.262782,18.518174,15.748793,0.746634,23.24324,17.994057,15.46488,0.760773,19.883494,18.089333,15.488973,0.758233,20.256547
17,18,11.280203,8.927066,0.935043,9.735506,11.860843,9.581903,0.928183,11.442744,10.807588,8.674195,0.940372,8.756613,10.965195,8.798833,0.93862,8.972098
18,19,16.50718,12.379992,0.56634,19.581184,14.579344,11.052407,0.661717,16.909046,16.481443,11.702587,0.567691,19.927518,16.326702,11.70725,0.575771,19.766335
19,20,10.396177,7.683459,0.92635,10.766247,10.423442,7.760163,0.925963,10.187604,9.988751,7.412619,0.93201,12.0624,10.081443,7.444062,0.930742,11.268702
20,21,17.511285,11.625032,0.334111,24.774533,14.593798,9.448267,0.53751,20.329527,15.252439,9.611859,0.494822,21.837949,15.614038,9.841157,0.470585,22.401762
21,22,10.882131,8.453508,0.911906,11.480094,11.355255,8.993465,0.904079,13.152115,9.941427,7.764216,0.926478,10.152014,10.272024,8.065046,0.921507,10.381124
22,23,17.671325,14.825172,0.849744,18.449608,19.507158,16.436072,0.816903,20.609934,18.683672,15.756951,0.832035,18.762224,18.766249,15.850454,0.830547,19.02532
23,24,7.7438,6.178202,0.915569,6.57483,8.585094,7.288462,0.896227,6.746923,8.878402,7.432855,0.889015,6.573965,8.564838,7.113077,0.896716,6.478454
24,25,13.503693,11.011038,0.706704,16.170674,14.56926,12.317286,0.658591,17.887996,14.207076,12.098508,0.675354,16.887627,14.162091,12.012308,0.677407,16.824135
25,26,10.315288,7.538043,0.755061,9.055348,10.006256,7.213008,0.769517,9.132799,9.455607,6.954924,0.794186,9.332487,9.463595,6.877319,0.793838,9.11385
26,27,10.250663,8.355927,0.757009,10.540118,11.710389,9.667371,0.682876,12.114072,12.049472,10.102809,0.664245,12.132847,11.758786,9.829228,0.680249,11.880234
27,28,13.216451,10.041535,0.579371,13.318502,13.480847,10.577035,0.562373,15.404712,13.539936,10.704488,0.558528,13.706493,13.540069,10.680374,0.558519,13.70311
28,29,18.825305,11.809192,0.253823,28.41335,18.246732,12.559972,0.298984,26.727669,19.479673,13.085563,0.201047,30.670148,19.310191,12.745552,0.214889,30.128018
29,30,13.453355,10.982231,0.620293,14.118808,12.090192,9.586647,0.693343,12.124668,12.135677,9.382955,0.691031,12.999919,12.238214,9.504865,0.685788,13.168557
30,31,9.399965,7.357874,0.927223,9.65085,8.638821,6.943068,0.938532,9.250877,9.238678,7.221017,0.9297,9.543856,9.052614,7.089965,0.932503,9.247104
31,32,16.055206,9.439765,0.956148,22.060968,14.688736,9.388987,0.963295,20.301534,16.107714,9.735737,0.955861,22.211325,17.121632,10.337828,0.950129,24.936044
32,33,24.128559,20.417163,0.104854,25.217434,22.823955,19.25756,0.199037,24.427219,23.926441,20.135895,0.119788,24.401506,23.648671,19.89035,0.140107,24.389574
33,34,10.677076,8.652746,0.677999,8.176327,10.453835,8.81458,0.691323,8.792478,9.256456,7.142211,0.757985,8.844634,9.406744,7.323513,0.750062,8.573279
34,35,17.81054,15.176189,0.401684,13.561501,17.13303,14.262208,0.446338,14.518147,16.123693,13.35026,0.509651,13.805768,16.259627,13.519583,0.501348,13.510561
35,36,25.091774,20.191747,0.625222,28.249049,23.516745,19.26071,0.670795,24.614367,27.839366,22.259867,0.53865,32.0938,27.164878,21.800975,0.560734,31.447408
36,37,11.248547,8.97353,0.86403,12.605789,10.60197,8.503562,0.879212,12.182564,10.672773,8.452973,0.877593,12.925295,10.613286,8.408298,0.878954,12.589311
37,38,22.91299,19.468333,0.901455,24.470831,23.674251,20.455106,0.894798,22.290552,25.510772,21.611035,0.877843,26.733383,25.152437,21.324527,0.881251,26.277819
38,39,10.782357,7.634641,0.589185,8.726819,10.329406,7.764367,0.622975,8.806761,9.83451,7.444624,0.658238,8.325975,9.950903,7.443799,0.6501,8.392209
39,40,12.376804,9.037434,0.894337,15.471779,12.142118,8.82182,0.898307,18.256305,12.092966,8.939331,0.899128,15.565932,12.189116,9.005345,0.897518,15.79133
40,41,19.990308,14.873602,0.531136,22.190803,18.554612,13.940375,0.596065,19.800768,19.622578,14.536663,0.548227,22.108278,19.463897,14.440258,0.555505,21.960866
41,42,11.193718,9.052207,0.873349,13.589121,12.252333,9.794618,0.84826,16.04812,12.346887,9.955126,0.845909,14.617155,12.204876,9.911024,0.849434,14.678545
42,43,11.326597,8.033653,0.710302,11.183925,10.730259,7.740027,0.740004,10.233375,11.556671,8.584303,0.698414,10.925036,11.383264,8.384488,0.707396,10.786938
43,44,18.288985,15.479784,0.663998,16.05235,20.322464,17.161923,0.585127,16.794099,20.476478,17.738756,0.578815,17.813199,20.113705,17.375045,0.593606,17.267496
44,45,9.297513,6.840662,0.856783,11.208935,10.048588,7.587705,0.83271,11.256009,10.842798,8.310497,0.805221,12.191897,10.492181,8.011945,0.817614,11.881968
45,46,9.384884,7.718305,0.855084,10.250209,10.839093,9.337725,0.806694,10.151624,11.636385,10.052417,0.77721,11.476166,11.070483,9.541246,0.798353,11.066098
46,47,15.239969,11.173827,0.886675,20.947265,17.05053,12.164717,0.858149,24.233598,15.995709,12.265204,0.875157,21.151352,15.981622,12.325204,0.875377,21.257567
47,48,21.966089,18.39199,0.280684,24.460908,21.375484,17.856771,0.318844,22.402835,20.755291,17.396172,0.357797,22.893254,20.827619,17.436488,0.353314,23.13514
48,49,16.401541,12.223741,0.904512,20.864455,16.823152,12.545582,0.899539,21.206786,15.954346,11.979147,0.909648,21.42003,16.705431,12.367476,0.90094,22.473842
49,50,19.052176,13.30585,0.934778,29.345825,20.105069,13.368788,0.92737,31.080259,18.854691,13.237461,0.936124,27.484683,19.74886,13.749414,0.929921,29.629934
50,51,17.800812,12.852201,0.522488,17.728692,17.097972,12.223093,0.559451,16.240321,16.258563,11.65845,0.601646,16.671805,16.497948,11.753324,0.589829,16.824501
51,52,11.16992,8.26939,0.797538,10.445057,11.133224,8.382722,0.798866,9.954775,11.70522,8.676818,0.777667,10.798225,11.493755,8.507297,0.785628,10.618438
52,53,12.808986,9.916624,0.732052,11.715577,13.067544,10.177755,0.721125,12.437291,12.168022,9.385478,0.758197,11.071339,12.212864,9.445603,0.756412,11.150941
53,NaN,28.095267,20.133668,-0.782262,27.539831,26.738088,19.125261,-0.614232,25.611129,28.540383,19.930912,-0.839182,27.832141,28.188694,19.646747,-0.794135,27.647834
54,Mean,15.375558,11.806516,0.658267,16.483959,15.077207,11.723353,0.682034,16.163217,15.357253,11.845362,0.669276,16.708428,15.348624,11.827608,0.670913,16.711568
55,Global,15.992245,11.790142,0.823333,27.72868,15.688541,11.739306,0.82998,28.323376,16.103912,11.853411,0.820857,27.234583,16.078151,11.840199,0.82143,27.959122

In [12]:
display(summary_df[['Storm Index', 'Equation 1_BFE', 'Equation 2_BFE', 'Equation 3_BFE']].set_index('Storm Index'))

            Equation 1_BFE Equation 2_BFE Equation 3_BFE
Storm Index
1                      NaN            NaN            NaN
2                15.526419      12.785224      17.116085
3                19.658886      19.382111      19.490141
4                 9.648251      10.238934        8.65772
5                18.572799      15.224579      19.860439
6                22.417481      20.990618      24.116157
7                16.641476      13.625485       16.91186
8                 6.639697        7.69351       6.909967
9                11.907346      10.549047      13.225507
10                12.40907       10.81744      11.798232
11               19.469273       16.25735      17.057575
12               25.472262      28.531491      25.999424
13               15.342755      12.049933      14.856913
14               14.311066      15.210475      13.872992
15               12.018502      11.724363      10.867242
16               25.658683      24.665073      28.214698
17               19.262782       23.24324      19.883494
18                9.735506      11.442744       8.756613
19               19.581184      16.909046      19.927518
20               10.766247      10.187604        12.0624
21               24.774533      20.329527      21.837949
22               11.480094      13.152115      10.152014
23               18.449608      20.609934      18.762224
24                 6.57483       6.746923       6.573965
25               16.170674      17.887996      16.887627
26                9.055348       9.132799       9.332487
27               10.540118      12.114072      12.132847
28               13.318502      15.404712      13.706493
29                28.41335      26.727669      30.670148
30               14.118808      12.124668      12.999919
31                 9.65085       9.250877       9.543856
32               22.060968      20.301534      22.211325
33               25.217434      24.427219      24.401506
34                8.176327       8.792478       8.844634
35               13.561501      14.518147      13.805768
36               28.249049      24.614367        32.0938
37               12.605789      12.182564      12.925295
38               24.470831      22.290552      26.733383
39                8.726819       8.806761       8.325975
40               15.471779      18.256305      15.565932
41               22.190803      19.800768      22.108278
42               13.589121       16.04812      14.617155
43               11.183925      10.233375      10.925036
44                16.05235      16.794099      17.813199
45               11.208935      11.256009      12.191897
46               10.250209      10.151624      11.476166
47               20.947265      24.233598      21.151352
48               24.460908      22.402835      22.893254
49               20.864455      21.206786       21.42003
50               29.345825      31.080259      27.484683
51               17.728692      16.240321      16.671805
52               10.445057       9.954775      10.798225
53               11.715577      12.437291      11.071339
NaN              27.539831      25.611129      27.832141
Mean             16.483959      16.163217      16.708428
Global            27.72868      28.323376      27.234583

In [13]:

storms = range(54, 74)
parent_folder = 'unconstrained-derived-figures'

for storm_number in storms:
    # We use f-strings with double {{ }} to escape the LaTeX braces
    # and single { } for the Python variables.
    latex_code = f"""
\\begin{{figure}}[ht]
    \\centering
    \\includegraphics[width=\\textwidth]{{{parent_folder}/storm_{storm_number}.png}}
    \\caption{{Reconstruction of storm {storm_number} using the Equations generated from the unconstrained symbolic regression with the derived features}}\\label{{fig:unconstrained-storm-{storm_number}}}
\\end{{figure}}
"""
    print(latex_code)

\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_54.png}
    \caption{Reconstruction of storm 54 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-54}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_55.png}
    \caption{Reconstruction of storm 55 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-55}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_56.png}
    \caption{Reconstruction of storm 56 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-56}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_57.png}
    \caption{Reconstruction of storm 57 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-57}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_58.png}
    \caption{Reconstruction of storm 58 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-58}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_59.png}
    \caption{Reconstruction of storm 59 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-59}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_60.png}
    \caption{Reconstruction of storm 60 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-60}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_61.png}
    \caption{Reconstruction of storm 61 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-61}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_62.png}
    \caption{Reconstruction of storm 62 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-62}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_63.png}
    \caption{Reconstruction of storm 63 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-63}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_64.png}
    \caption{Reconstruction of storm 64 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-64}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_65.png}
    \caption{Reconstruction of storm 65 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-65}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_66.png}
    \caption{Reconstruction of storm 66 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-66}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_67.png}
    \caption{Reconstruction of storm 67 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-67}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_68.png}
    \caption{Reconstruction of storm 68 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-68}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_69.png}
    \caption{Reconstruction of storm 69 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-69}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_70.png}
    \caption{Reconstruction of storm 70 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-70}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_71.png}
    \caption{Reconstruction of storm 71 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-71}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_72.png}
    \caption{Reconstruction of storm 72 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-72}
\end{figure}


\begin{figure}[ht]
    \centering
    \includegraphics[width=\textwidth]{unconstrained-derived-figures/storm_73.png}
    \caption{Reconstruction of storm 73 using the Equations generated from the unconstrained symbolic regression with the derived features}\label{fig:unconstrained-storm-73}
\end{figure}