# Test notebook

The purpose of this notebook is to test an equation and compare them with the baselines: Burton, MBR, and DDM1, 2 and 3. We will also plot each storm and get the metrics for the equation.

The only cell that we have to modify is the following one, where we can change the features, the mode (template or default) and the output directory for the plots.
Raw EQ is the equation that we want to test, the raw version generated from the train_script.py file.

In [2]:
import os

FEATURES = ["P_dyn", "VBs", "epsilon", "DST"]
MODE = "template"  # 'template' or 'default'
OUTPUT_DIR = "comparison_template_deriv_against_baselines_newv"
RAW_EQ = "g = (#2 * -0.0010713526) * sqrt(#1 + 1.32442); d = square((#1 * 0.01838707) - 0.5912093)"

output_folder = OUTPUT_DIR
# Count number of existing subfolders
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

import sympy as sp
from tqdm import tqdm

from sympy.printing import latex

# Internal module imports
import storm_dates
import baseline_models

# from evaluation_engine import UnifiedModel, simulate_storm, compute_features
from evaluation_engine import EquationModel, simulate_storm
from train_script import load_and_preprocess, compute_features

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

/mnt/data/symbolic-regression-dst-public-repo/.venv/lib/python3.12/site-packages/spacepy/time.py:2448: UserWarning: Leapseconds may be out of date. Use spacepy.toolbox.update(leapsecs=True)
  _read_leaps()

In [4]:
raw_data = load_and_preprocess(save_prepared_data=True)
data = compute_features(raw_data)

Reading from file ./data/all_timeline/ace_imf_1h_1998.csv
Reading from file ./data/all_timeline/ace_imf_1h_1999.csv
Reading from file ./data/all_timeline/ace_imf_1h_2000.csv
Reading from file ./data/all_timeline/ace_imf_1h_2001.csv
Reading from file ./data/all_timeline/ace_imf_1h_2002.csv
Reading from file ./data/all_timeline/ace_imf_1h_2003.csv
Reading from file ./data/all_timeline/ace_imf_1h_2004.csv
Reading from file ./data/all_timeline/ace_imf_1h_2005.csv
Reading from file ./data/all_timeline/ace_imf_1h_2006.csv
Reading from file ./data/all_timeline/ace_imf_1h_2007.csv
Reading from file ./data/all_timeline/ace_imf_1h_2008.csv
Reading from file ./data/all_timeline/ace_imf_1h_2009.csv
Reading from file ./data/all_timeline/ace_imf_1h_2010.csv
Reading from file ./data/all_timeline/ace_imf_1h_2011.csv
Reading from file ./data/all_timeline/ace_imf_1h_2012.csv
Reading from file ./data/all_timeline/ace_imf_1h_2013.csv
Reading from file ./data/all_timeline/ace_imf_1h_2014.csv
Reading from file ./data/all_timeline/ace_imf_1h_2015.csv
Reading from file ./data/all_timeline/ace_imf_1h_2016.csv
Reading from file ./data/all_timeline/ace_imf_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_1h_2024.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_imf_provisional_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1998.csv
Reading from file ./data/all_timeline/ace_swepam_1h_1999.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2000.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2001.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2002.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2003.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2004.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2005.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2006.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2007.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2008.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2009.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2010.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2011.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2012.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2013.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2014.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2015.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2016.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_1h_2024.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2017.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2018.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2019.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2020.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2021.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2022.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2023.csv
Reading from file ./data/all_timeline/ace_swepam_provisional_1h_2024.csv

In [5]:
def predict_and_plot_storm(model, start, end, storm_df, storm_id, save_path):
    # 1. Generate Predictions
    y_true = storm_df[start:end]["DST"].values

    res_eq = simulate_storm(model, storm_df)
    res_burton = baseline_models.burton_prediction(storm_df)
    res_obm = baseline_models.obm_prediction(storm_df)
    ddm1 = baseline_models.ddm1_prediction(storm_df)
    ddm2 = baseline_models.ddm2_prediction(storm_df)
    ddm3 = baseline_models.ddm3_prediction(storm_df)

    res_eq = res_eq[start:end]["DST_pred"].values
    res_burton = res_burton[start:end]["DST_pred"].values
    res_obm = res_obm[start:end]["DST_pred"].values
    res_ddm1 = ddm1[start:end]["DST_pred"].values
    res_ddm2 = ddm2[start:end]["DST_pred"].values
    res_ddm3 = ddm3[start:end]["DST_pred"].values

    # 2. Calculate Metrics
    m_eq = baseline_models.get_all_metrics(y_true, res_eq)
    m_burton = baseline_models.get_all_metrics(y_true, res_burton)
    m_obm = baseline_models.get_all_metrics(y_true, res_obm)
    m_ddm1 = baseline_models.get_all_metrics(y_true, res_ddm1)
    m_ddm2 = baseline_models.get_all_metrics(y_true, res_ddm2)
    m_ddm3 = baseline_models.get_all_metrics(y_true, res_ddm3)

    # 3. Setup Figure (3 Columns)
    fig, axs = plt.subplots(1, 3, figsize=(24, 8), constrained_layout=True)
    fig.suptitle(
        rf"Evaluation for Equation: ${model.latex_str()}$", fontsize=18, wrap=True
    )
    # Column 1: Time Series
    axs[0].plot(
        storm_df[start:end].index,
        y_true,
        color="black",
        label="Observed",
        alpha=0.6,
        linewidth=2,
    )
    axs[0].plot(
        storm_df[start:end].index,
        res_eq,
        color="blue",
        linestyle="--",
        label="Equation",
        linewidth=1.5,
    )
    axs[0].plot(
        storm_df[start:end].index,
        res_burton,
        color="yellow",
        linestyle="--",
        label="Burton",
        linewidth=1.5,
    )
    axs[0].plot(
        storm_df[start:end].index,
        res_obm,
        color="green",
        linestyle="--",
        label="OBM",
        linewidth=1.5,
    )
    
    axs[0].plot(
        storm_df[start:end].index,
        res_ddm1,
        color="orange",
        linestyle="--",
        label="DDM1",
        linewidth=1.5,
    )
    axs[0].plot(
        storm_df[start:end].index,
        res_ddm2,
        color="purple",
        linestyle="--",
        label="DDM2",
        linewidth=1.5,
    )
    axs[0].plot(
        storm_df[start:end].index,
        res_ddm3,
        color="cyan",
        linestyle="--",
        label="DDM3",
        linewidth=1.5,
    )
    
    axs[0].set_title(f"Storm {storm_id} Reconstruction", fontsize=18)
    axs[0].tick_params(axis='both', which='major', labelsize=14)
    axs[0].tick_params(axis='both', which='minor', labelsize=10)
    axs[0].legend(fontsize = 16)
    axs[0].grid(True)
    axs[0].set_xlim(start, end)
    axs[0].set_xlabel("Date", fontsize=16)
    axs[0].set_ylabel("Dst (nT)", fontsize=16)
    axs[0].xaxis.set_major_locator(MultipleLocator(2))

    # Column 2: Prediction Error
    diff_eq = res_eq - y_true
    diff_burton = res_burton - y_true
    diff_obm = res_obm - y_true
    diff_ddm1 = res_ddm1 - y_true
    diff_ddm2 = res_ddm2 - y_true
    diff_ddm3 = res_ddm3 - y_true


    axs[1].plot(storm_df[start:end].index, diff_eq, color="blue", label="Eq Error")
    axs[1].plot(
        storm_df[start:end].index, diff_burton, color="yellow", label="Burton Error"
    )
    axs[1].plot(storm_df[start:end].index, diff_obm, color="green", label="OBM Error")
    axs[1].plot(storm_df[start:end].index, diff_ddm1, color="orange", label="DDM1 Error")
    axs[1].plot(storm_df[start:end].index, diff_ddm2, color="purple", label="DDM2 Error")
    axs[1].plot(storm_df[start:end].index, diff_ddm3, color="cyan", label="DDM3 Error")
    axs[1].axhline(0, color="black", linestyle="--")
    axs[1].set_title("Prediction Error", fontsize=18)
    axs[1].set_ylabel("Error (nT)", fontsize=16)
    axs[1].set_xlabel("Date", fontsize=16)

    title_metrics = (
        f"Error Comparison\n"
        f"Eq: RMSE {m_eq[0]:.2f} | MAE {m_eq[1]:.2f} | R2 {m_eq[2]:.2f} | CC {m_eq[3]:.2f} | BFE {m_eq[4]:.2f}\n"
        f"Burton: RMSE {m_burton[0]:.2f} | MAE {m_burton[1]:.2f} | R2 {m_burton[2]:.2f} | CC {m_burton[3]:.2f} | BFE {m_burton[4]:.2f}\n"
        f"OBM: RMSE {m_obm[0]:.2f} | MAE {m_obm[1]:.2f} | R2 {m_obm[2]:.2f} | CC {m_obm[3]:.2f} | BFE {m_obm[4]:.2f}\n"
        f"DDM1: RMSE {m_ddm1[0]:.2f} | MAE {m_ddm1[1]:.2f} | R2 {m_ddm1[2]:.2f} | CC {m_ddm1[3]:.2f} | BFE {m_ddm1[4]:.2f}\n"
        f"DDM2: RMSE {m_ddm2[0]:.2f} | MAE {m_ddm2[1]:.2f} | R2 {m_ddm2[2]:.2f} | CC {m_ddm2[3]:.2f} | BFE {m_ddm2[4]:.2f}\n"
        f"DDM3: RMSE {m_ddm3[0]:.2f} | MAE {m_ddm3[1]:.2f} | R2 {m_ddm3[2]:.2f} | CC {m_ddm3[3]:.2f} | BFE {m_ddm3[4]:.2f}"
    )
    axs[1].set_title(title_metrics, fontsize=18)
    axs[1].set_ylabel("Error (nT)", fontsize=16)
    axs[1].set_xlabel("Date", fontsize=16)
    axs[1].legend(fontsize=16)
    axs[1].grid(True)
    axs[1].set_xlim(start, end)
    axs[1].tick_params(axis='both', which='major', labelsize=14)
    axs[1].tick_params(axis='both', which='minor', labelsize=10)
    
    axs[1].xaxis.set_major_locator(MultipleLocator(2))

    # Column 3: BFE
    baseline_models.plot_evaluation_bfe_multi(
        axs[2],
        y_true,
        [res_eq, res_burton, res_obm, res_ddm1, res_ddm2, res_ddm3],
        ["Equation", "Burton", "OBM", "DDM1", "DDM2", "DDM3"],
        ["blue", "yellow", "green", "orange", "purple", "cyan"],
        fontsize = 16   
    )

    plt.savefig(save_path)
    plt.close()

In [6]:
def save_prediction_data(model, start, end, storm_df, output_path):
    """
    Generates and saves a CSV with observed and predicted DST and dDST/dt.
    """
    # 1. Observed Data
    # Real dDST is calculated as the difference to the next hour
    real_dst = storm_df[start:end]["DST"].values
    real_ddst = storm_df[start:end]["DST"].diff().shift(-1).values

    # 2. Equation Predictions
    # We need the iterative predictions for DST
    pred_dst_eq = simulate_storm(model, storm_df)
    if model.is_template:
        pred_dst_eq = pred_dst_eq[start:end][
            ["DST_pred", "dDST", "injection_component", "decay_component"]
        ]
    else:
        pred_dst_eq = pred_dst_eq[start:end][["DST_pred", "dDST"]]
    # 3. Baseline Predictions (Burton & OBM)
    pred_dst_burton = baseline_models.burton_prediction(storm_df)
    pred_dst_burton = pred_dst_burton[start:end][["DST_pred", "dDST"]]
    pred_dst_burton.columns = ["DST_pred_burton", "dDST_burton"]
    pred_dst_burton = pred_dst_burton[start:end][["DST_pred_burton", "dDST_burton"]]
    pred_dst_obm = baseline_models.obm_prediction(storm_df)
    pred_dst_obm = pred_dst_obm[start:end][["DST_pred", "dDST"]]
    pred_dst_obm.columns = ["DST_pred_obm", "dDST_obm"]
    pred_dst_obm = pred_dst_obm[start:end][["DST_pred_obm", "dDST_obm"]]
    pred_dst_ddm1 = baseline_models.ddm1_prediction(storm_df)    
    pred_dst_ddm1.columns = ["DST_pred_ddm1", "dDST_ddm1"]
    pred_dst_ddm1 = pred_dst_ddm1[start:end][["DST_pred_ddm1", "dDST_ddm1"]]
    pred_dst_ddm2 = baseline_models.ddm2_prediction(storm_df)
    pred_dst_ddm2.columns = ["DST_pred_ddm2", "dDST_ddm2"]
    pred_dst_ddm2 = pred_dst_ddm2[start:end][["DST_pred_ddm2", "dDST_ddm2"]]
    pred_dst_ddm3 = baseline_models.ddm3_prediction(storm_df)
    pred_dst_ddm3.columns = ["DST_pred_ddm3", "dDST_ddm3"]
    pred_dst_ddm3 = pred_dst_ddm3[start:end][["DST_pred_ddm3", "dDST_ddm3"]]


    # 4. Construct Comprehensive DataFrame

    if model.is_template:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Injection_Component": pred_dst_eq["injection_component"].values,
                "Decay_Component": pred_dst_eq["decay_component"].values,
                "Pred_DST_Burton": pred_dst_burton["DST_pred_burton"].values,
                "Pred_dDST_dt_Burton": pred_dst_burton["dDST_burton"].values,
                "Pred_DST_OBM": pred_dst_obm["DST_pred_obm"].values,
                "Pred_dDST_dt_OBM": pred_dst_obm["dDST_obm"].values,
                "Pred_DST_DDM1": pred_dst_ddm1["DST_pred_ddm1"].values,
                "Pred_dDST_dt_DDM1": pred_dst_ddm1["dDST_ddm1"].values,
                "Pred_DST_DDM2": pred_dst_ddm2["DST_pred_ddm2"].values,
                "Pred_dDST_dt_DDM2": pred_dst_ddm2["dDST_ddm2"].values,
                "Pred_DST_DDM3": pred_dst_ddm3["DST_pred_ddm3"].values,
                "Pred_dDST_dt_DDM3": pred_dst_ddm3["dDST_ddm3"].values,
            }
        ).set_index("Timestamp")
    else:
        results_df = pd.DataFrame(
            {
                "Timestamp": storm_df[start:end].index,
                "Observed_DST": real_dst,
                "Real_dDST_dt": real_ddst,
                "Pred_DST_Equation": pred_dst_eq["DST_pred"].values,
                "Pred_dDST_dt_Equation": pred_dst_eq["dDST"].values,
                "Pred_DST_Burton": pred_dst_burton["DST_pred_burton"].values,
                "Pred_dDST_dt_Burton": pred_dst_burton["dDST_burton"].values,
                "Pred_DST_OBM": pred_dst_obm["DST_pred_obm"].values,
                "Pred_dDST_dt_OBM": pred_dst_obm["dDST_obm"].values,
                "Pred_DST_DDM1": pred_dst_ddm1["DST_pred_ddm1"].values,
                "Pred_dDST_dt_DDM1": pred_dst_ddm1["dDST_ddm1"].values,
                "Pred_DST_DDM2": pred_dst_ddm2["DST_pred_ddm2"].values,
                "Pred_dDST_dt_DDM2": pred_dst_ddm2["dDST_ddm2"].values,
                "Pred_DST_DDM3": pred_dst_ddm3["DST_pred_ddm3"].values,
                "Pred_dDST_dt_DDM3": pred_dst_ddm3["dDST_ddm3"].values,

            }
        ).set_index("Timestamp")

    results_df.to_csv(output_path)
    return results_df

## Test storms

In [7]:
storms = []

model = EquationModel(RAW_EQ, FEATURES, is_template=MODE == "template")
test_storms = storm_dates.TEST_STORMS_SYMBOLIC_REGRESSION
storm_indices = []
for sd, ed, storm_id in tqdm(test_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        model,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            model, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)
    
with open(os.path.join(OUTPUT_DIR, 'equation.txt'), 'w') as f:
    f.write(f'Equation: {RAW_EQ}\n')            
    f.write(f'LaTeX: {latex(model.latex_str())}\n')

100%|██████████| 20/20 [00:25<00:00,  1.28s/it]

In [8]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = ["Equation", "Burton", "OBM", "DDM1", "DDM2", "DDM3"]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    res_eq = storm["Pred_DST_Equation"].values
    res_burton = storm["Pred_DST_Burton"].values
    res_obm = storm["Pred_DST_OBM"].values
    res_ddm1 = storm["Pred_DST_DDM1"].values
    res_ddm2 = storm["Pred_DST_DDM2"].values
    res_ddm3 = storm["Pred_DST_DDM3"].values

    m_eq = baseline_models.get_all_metrics(y_true, res_eq)
    m_burton = baseline_models.get_all_metrics(y_true, res_burton)
    m_obm = baseline_models.get_all_metrics(y_true, res_obm)
    m_ddm1 = baseline_models.get_all_metrics(y_true, res_ddm1)
    m_ddm2 = baseline_models.get_all_metrics(y_true, res_ddm2)
    m_ddm3 = baseline_models.get_all_metrics(y_true, res_ddm3)

    summary_df.loc[len(summary_df)] = [
        storm_indices[storm_index],
        *m_eq,
        *m_burton,
        *m_obm,
        *m_ddm1,
        *m_ddm2,
        *m_ddm3,
    ]

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values
res_eq = global_data["Pred_DST_Equation"].values
res_burton = global_data["Pred_DST_Burton"].values
res_obm = global_data["Pred_DST_OBM"].values
res_ddm1 = global_data["Pred_DST_DDM1"].values
res_ddm2 = global_data["Pred_DST_DDM2"].values
res_ddm3 = global_data["Pred_DST_DDM3"].values

m_eq = baseline_models.get_all_metrics(y_true, res_eq)
m_burton = baseline_models.get_all_metrics(y_true, res_burton)
m_obm = baseline_models.get_all_metrics(y_true, res_obm)
m_ddm1 = baseline_models.get_all_metrics(y_true, res_ddm1)
m_ddm2 = baseline_models.get_all_metrics(y_true, res_ddm2)
m_ddm3 = baseline_models.get_all_metrics(y_true, res_ddm3)

summary_df.loc[len(summary_df)] = [
    "Global",
    *m_eq,
    *m_burton,
    *m_obm,
    *m_ddm1,
    *m_ddm2,
    *m_ddm3,
]

display(summary_df)

,Storm Index,Equation_RMSE,Equation_MAE,Equation_R2,Equation_CC,Equation_BFE,Burton_RMSE,Burton_MAE,Burton_R2,Burton_CC,...,DDM2_RMSE,DDM2_MAE,DDM2_R2,DDM2_CC,DDM2_BFE,DDM3_RMSE,DDM3_MAE,DDM3_R2,DDM3_CC,DDM3_BFE
0,54.0,9.082450,7.150428,0.796405,0.922839,11.620567,22.273257,19.295634,-0.224415,0.825122,...,17.034353,14.718489,0.283836,0.819670,19.285046,17.429228,14.902320,0.250248,0.849179,20.944809
1,55.0,17.429458,13.783357,0.748936,0.886955,19.558619,22.561217,19.634219,0.579330,0.889945,...,20.994874,17.672795,0.635713,0.870809,22.088199,22.442717,18.173790,0.583737,0.864456,25.386413
2,56.0,13.276276,10.962537,0.613082,0.889956,15.586261,14.594609,9.904945,0.532425,0.864593,...,11.710892,9.329760,0.698945,0.874185,13.104050,11.378825,9.160091,0.715776,0.872556,12.828221
3,57.0,9.579700,7.665862,0.766690,0.899931,12.124595,18.949308,14.323111,0.087114,0.643703,...,8.303250,6.470139,0.824723,0.917542,11.441876,8.670891,6.332414,0.808857,0.904447,13.883947
4,58.0,9.165543,6.390252,0.797016,0.927846,15.584912,9.491523,7.361750,0.782321,0.889916,...,11.990044,9.586551,0.652635,0.926882,19.031650,11.862568,8.934847,0.659982,0.920503,19.970899
5,59.0,12.207318,10.241290,0.849938,0.955928,9.432197,15.884176,12.114917,0.745927,0.899436,...,10.840170,8.734074,0.881668,0.955437,13.497036,12.354960,9.578556,0.846286,0.954712,16.759531
6,60.0,17.617883,11.828793,0.777722,0.934481,26.807645,25.327401,19.852983,0.540622,0.930660,...,13.320289,10.330457,0.872938,0.963738,17.936865,14.717364,11.742180,0.844887,0.954268,19.772733
7,61.0,10.679534,8.252146,0.932006,0.968053,14.553100,40.396238,21.193252,0.027141,0.886214,...,22.490189,16.826801,0.698454,0.883757,30.616512,20.468681,15.214925,0.750226,0.886201,30.187252
8,62.0,11.394979,9.122644,0.698127,0.886644,12.820999,14.256121,10.561750,0.527503,0.821907,...,10.405858,7.936314,0.748260,0.888742,14.058279,11.805307,9.352887,0.675995,0.859124,16.881751
9,63.0,14.975924,12.167919,0.837054,0.944592,18.193426,22.695026,18.805391,0.625787,0.882456,...,20.014049,16.071049,0.708977,0.932586,28.117249,22.085126,17.377477,0.645630,0.929705,32.083276
10,64.0,10.130700,8.022478,0.802369,0.916027,11.183879,15.163913,11.927870,0.557209,0.851339,...,11.958052,9.921245,0.724642,0.937830,15.054917,13.758703,11.129886,0.635472,0.925553,18.587674
11,65.0,14.249835,10.390993,0.633954,0.808397,16.794854,15.383504,12.952325,0.573395,0.765625,...,14.062862,10.704450,0.643497,0.883355,22.232818,16.592907,12.906062,0.503681,0.796226,26.520995
12,66.0,18.264381,15.416668,0.542265,0.798544,20.120807,28.928601,20.894541,-0.148310,0.409940,...,22.099429,17.822974,0.329859,0.748012,27.987632,19.081747,15.244277,0.500379,0.806706,25.992218
13,67.0,11.028895,8.251830,0.783796,0.906609,15.547703,11.548148,8.497350,0.762958,0.896775,...,14.921955,12.663625,0.604222,0.840770,18.323127,13.803421,11.555887,0.661333,0.872680,19.323836
14,68.0,27.917544,20.658547,0.945960,0.981811,30.007003,71.853080,52.857748,0.642029,0.923274,...,41.572942,29.790561,0.880166,0.951963,48.471863,50.339308,34.754586,0.824300,0.957009,54.646725
15,69.0,10.957599,8.249883,0.788969,0.900695,12.099412,15.788740,11.175405,0.561864,0.761175,...,13.769383,11.664540,0.666771,0.849088,15.951763,12.629479,10.200062,0.719660,0.863997,15.431553
16,70.0,16.846867,12.100777,0.836781,0.944062,19.179360,21.099721,17.360766,0.743973,0.894213,...,19.950045,13.819167,0.771114,0.925916,24.837426,22.293240,15.003399,0.714189,0.894264,27.983468
17,71.0,11.688103,7.816167,0.898042,0.949287,13.278875,17.920997,14.152849,0.760306,0.898102,...,16.261521,12.396000,0.802642,0.945182,18.055185,17.328567,12.601007,0.775892,0.946508,19.930136
18,72.0,18.315026,13.270134,0.948526,0.977507,22.360540,98.405671,48.722910,-0.485983,0.923360,...,53.241797,37.023519,0.565010,0.876357,66.197146,44.726135,30.411752,0.693030,0.878381,55.473828
19,73.0,11.560103,9.467041,0.769727,0.959614,10.804701,17.447878,12.793879,0.475429,0.820136,...,9.024223,7.394594,0.859674,0.929980,10.469337,9.515293,7.434504,0.843986,0.931872,12.582309
20,Mean,13.818406,10.560487,0.788368,0.917989,16.382973,25.998457,18.219180,0.433331,0.833895,...,18.198309,14.043855,0.692687,0.896090,22.837899,18.664223,14.100546,0.682677,0.893417,24.258579
21,Global,14.012626,10.250200,0.885655,0.941677,28.790562,28.569081,16.726500,0.524697,0.858236,...,19.055458,13.156857,0.788546,0.896173,45.264095,19.546453,13.357906,0.777508,0.890177,46.378788

In [9]:
display(summary_df.iloc[-2:, :].style.format({col: "{:.2f}" for col in columns}))

In [10]:
display(summary_df[['Storm Index', 'Equation_BFE', 'Burton_BFE', 'OBM_BFE', 'DDM1_BFE', 'DDM2_BFE', 'DDM3_BFE']])

,Storm Index,Equation_BFE,Burton_BFE,OBM_BFE,DDM1_BFE,DDM2_BFE,DDM3_BFE
0,54.0,11.620567,22.737069,15.339845,21.129540,19.285046,20.944809
1,55.0,19.558619,19.121577,16.826395,23.435284,22.088199,25.386413
2,56.0,15.586261,20.446094,17.798724,13.923395,13.104050,12.828221
3,57.0,12.124595,15.869737,10.829970,13.120449,11.441876,13.883947
4,58.0,15.584912,11.644470,12.822532,20.108684,19.031650,19.970899
5,59.0,9.432197,16.203182,9.970305,14.982619,13.497036,16.759531
6,60.0,26.807645,33.244838,15.577698,36.468144,17.936865,19.772733
7,61.0,14.553100,59.335394,23.901355,28.911696,30.616512,30.187252
8,62.0,12.820999,12.923521,13.610126,14.844234,14.058279,16.881751
9,63.0,18.193426,24.673526,21.192304,29.948383,28.117249,32.083276
10,64.0,11.183879,16.871435,9.879458,14.890617,15.054917,18.587674
11,65.0,16.794854,19.242696,17.209346,22.930795,22.232818,26.520995
12,66.0,20.120807,33.374396,21.705261,26.471653,27.987632,25.992218
13,67.0,15.547703,11.570566,9.020917,22.932887,18.323127,19.323836
14,68.0,30.007003,75.143485,49.726978,29.755937,48.471863,54.646725
15,69.0,12.099412,15.974618,11.976697,17.501922,15.951763,15.431553
16,70.0,19.179360,25.347815,22.555063,27.057703,24.837426,27.983468
17,71.0,13.278875,17.321226,16.718115,17.363032,18.055185,19.930136
18,72.0,22.360540,115.533828,30.115146,69.501769,66.197146,55.473828
19,73.0,10.804701,14.360046,10.775111,12.594635,10.469337,12.582309
20,Mean,16.382973,29.046976,17.877567,23.893669,22.837899,24.258579
21,Global,28.790562,78.350014,43.361586,38.888355,45.264095,46.378788

In [11]:
print(summary_df.loc[summary_df["Storm Index"].isin([57, 68, 'Mean'])].to_latex(index=False, float_format="%.2f"))

\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}
\toprule
Storm Index & Equation_RMSE & Equation_MAE & Equation_R2 & Equation_CC & Equation_BFE & Burton_RMSE & Burton_MAE & Burton_R2 & Burton_CC & Burton_BFE & OBM_RMSE & OBM_MAE & OBM_R2 & OBM_CC & OBM_BFE & DDM1_RMSE & DDM1_MAE & DDM1_R2 & DDM1_CC & DDM1_BFE & DDM2_RMSE & DDM2_MAE & DDM2_R2 & DDM2_CC & DDM2_BFE & DDM3_RMSE & DDM3_MAE & DDM3_R2 & DDM3_CC & DDM3_BFE \\
\midrule
57.00 & 9.58 & 7.67 & 0.77 & 0.90 & 12.12 & 18.95 & 14.32 & 0.09 & 0.64 & 15.87 & 10.28 & 8.56 & 0.73 & 0.86 & 10.83 & 8.77 & 6.75 & 0.80 & 0.92 & 13.12 & 8.30 & 6.47 & 0.82 & 0.92 & 11.44 & 8.67 & 6.33 & 0.81 & 0.90 & 13.88 \\
68.00 & 27.92 & 20.66 & 0.95 & 0.98 & 30.01 & 71.85 & 52.86 & 0.64 & 0.92 & 75.14 & 43.64 & 32.15 & 0.87 & 0.98 & 49.73 & 26.23 & 19.68 & 0.95 & 0.98 & 29.76 & 41.57 & 29.79 & 0.88 & 0.95 & 48.47 & 50.34 & 34.75 & 0.82 & 0.96 & 54.65 \\
Mean & 13.82 & 10.56 & 0.79 & 0.92 & 16.38 & 26.00 & 18.22 & 0.43 & 0.83 & 29.05 & 16.77 & 13.05 & 0.72 & 0.92 & 17.88 & 18.75 & 14.59 & 0.66 & 0.89 & 23.89 & 18.20 & 14.04 & 0.69 & 0.90 & 22.84 & 18.66 & 14.10 & 0.68 & 0.89 & 24.26 \\
\bottomrule
\end{tabular}

## Train storms

In [12]:
storms = []

train_storms = storm_dates.TRAIN_STORMS_SYMBOLIC_REGRESSION
storm_indices = []
for sd, ed, storm_id in tqdm(train_storms):
    start = pd.to_datetime(sd)
    end = pd.to_datetime(ed)
    storm_df = data[
        start - pd.DateOffset(hours=1) : end + pd.DateOffset(hours=1)
    ].copy()
    if storm_df.empty:
        print(f'Storm {storm_id} has no data from {start} to {end}. Skipping.')
        continue

    file_name = f"storm_{storm_id}.png"
    predict_and_plot_storm(
        model,
        start,
        end,
        storm_df,
        storm_id,
        os.path.join(OUTPUT_DIR, file_name),
    )

    csv_name = f"data_storm_{storm_id}.csv"
    storms.append(
        save_prediction_data(
            model, start, end, storm_df, os.path.join(OUTPUT_DIR, csv_name)
        )
    )
    storm_indices.append(storm_id)

100%|██████████| 53/53 [01:21<00:00,  1.54s/it]

In [13]:
metrics = ["RMSE", "MAE", "R2", "CC", "BFE"]
equations = ["Equation", "Burton", "OBM", "DDM1", "DDM2", "DDM3"]

columns = [f"{eq}_{metric}" for eq in equations for metric in metrics]

summary_df = pd.DataFrame(
    columns=["Storm Index"] + columns,
)

for storm_index, storm in enumerate(storms):
    y_true = storm["Observed_DST"].values
    res_eq = storm["Pred_DST_Equation"].values
    res_burton = storm["Pred_DST_Burton"].values
    res_obm = storm["Pred_DST_OBM"].values
    res_ddm1 = storm["Pred_DST_DDM1"].values
    res_ddm2 = storm["Pred_DST_DDM2"].values
    res_ddm3 = storm["Pred_DST_DDM3"].values

    m_eq = baseline_models.get_all_metrics(y_true, res_eq)
    m_burton = baseline_models.get_all_metrics(y_true, res_burton)
    m_obm = baseline_models.get_all_metrics(y_true, res_obm)
    m_ddm1 = baseline_models.get_all_metrics(y_true, res_ddm1)
    m_ddm2 = baseline_models.get_all_metrics(y_true, res_ddm2)
    m_ddm3 = baseline_models.get_all_metrics(y_true, res_ddm3)

    summary_df.loc[len(summary_df)] = [
        storm_indices[storm_index],
        *m_eq,
        *m_burton,
        *m_obm,
        *m_ddm1,
        *m_ddm2,
        *m_ddm3,
    ]

summary_df.loc[len(summary_df)] = ["Mean", *summary_df[columns].mean().values]

global_data = pd.concat(storms, ignore_index=True)
y_true = global_data["Observed_DST"].values
res_eq = global_data["Pred_DST_Equation"].values
res_burton = global_data["Pred_DST_Burton"].values
res_obm = global_data["Pred_DST_OBM"].values
res_ddm1 = global_data["Pred_DST_DDM1"].values
res_ddm2 = global_data["Pred_DST_DDM2"].values
res_ddm3 = global_data["Pred_DST_DDM3"].values

m_eq = baseline_models.get_all_metrics(y_true, res_eq)
m_burton = baseline_models.get_all_metrics(y_true, res_burton)
m_obm = baseline_models.get_all_metrics(y_true, res_obm)
m_ddm1 = baseline_models.get_all_metrics(y_true, res_ddm1)
m_ddm2 = baseline_models.get_all_metrics(y_true, res_ddm2)
m_ddm3 = baseline_models.get_all_metrics(y_true, res_ddm3)

summary_df.loc[len(summary_df)] = [
    "Global",
    *m_eq,
    *m_burton,
    *m_obm,
    *m_ddm1,
    *m_ddm2,
    *m_ddm3,
]

display(summary_df)

,Storm Index,Equation_RMSE,Equation_MAE,Equation_R2,Equation_CC,Equation_BFE,Burton_RMSE,Burton_MAE,Burton_R2,Burton_CC,...,DDM2_RMSE,DDM2_MAE,DDM2_R2,DDM2_CC,DDM2_BFE,DDM3_RMSE,DDM3_MAE,DDM3_R2,DDM3_CC,DDM3_BFE
0,1.0,20.213585,17.117328,0.640361,0.871804,16.822423,29.156901,25.538353,0.251721,0.839101,...,22.568521,19.475600,0.551681,0.896125,14.829997,23.252721,19.882235,0.524086,0.889651,19.966095
1,2.0,22.835546,17.477713,-0.337692,0.578832,19.405386,12.625578,10.846565,0.591082,0.844957,...,18.874640,14.104114,0.086117,0.588612,18.701587,21.678056,16.169453,-0.205519,0.501767,21.927198
2,3.0,11.215986,8.793026,0.879061,0.949642,8.793067,21.695670,17.060808,0.547482,0.844832,...,14.543500,12.109214,0.796658,0.933442,19.227867,15.653912,12.848885,0.764421,0.924793,21.447613
3,4.0,17.213986,14.144183,0.778240,0.920668,19.953851,41.408010,29.564523,-0.283185,0.864301,...,20.949735,17.795732,0.671544,0.887207,21.903819,20.551589,17.276006,0.683910,0.878793,22.014097
4,5.0,18.665306,14.714571,0.766902,0.907633,24.272886,32.233862,22.613058,0.304827,0.899751,...,22.171150,16.574360,0.671115,0.855711,29.435293,22.597948,16.987666,0.658331,0.843171,29.757253
5,6.0,15.532397,12.371153,0.645368,0.883474,16.965733,27.830107,19.744801,-0.138494,0.879934,...,18.066086,15.496299,0.520234,0.820916,17.225424,17.936579,15.021498,0.527088,0.822802,17.003694
6,7.0,10.465127,8.609895,0.808674,0.906307,7.050362,19.666746,16.300287,0.324306,0.815489,...,12.238735,10.768601,0.738327,0.915610,14.937157,13.896036,12.057634,0.662661,0.897081,18.509792
7,8.0,12.263987,9.014927,0.847011,0.962559,13.263640,19.523686,15.070868,0.612279,0.934798,...,10.379121,8.237262,0.890424,0.959182,8.695989,11.590607,9.317260,0.863351,0.957484,10.319187
8,9.0,12.576511,9.406606,0.692773,0.918247,11.592131,17.192414,14.828763,0.425867,0.884437,...,11.275480,8.936104,0.753050,0.884648,10.333607,12.823987,9.634174,0.680563,0.852321,11.559362
9,10.0,13.050190,9.008404,0.639154,0.884235,16.813556,13.699719,11.276735,0.602341,0.862175,...,14.126297,8.265998,0.577191,0.811954,21.448999,16.740966,8.877678,0.406188,0.721946,25.359561
10,11.0,17.947936,14.182177,0.704777,0.851626,26.471161,28.622113,21.780694,0.249199,0.837442,...,21.604379,15.426461,0.572235,0.850046,36.240329,20.519978,14.839406,0.614100,0.815022,30.591424
11,12.0,15.112173,10.515101,0.685759,0.921650,14.319192,26.111370,20.872561,0.061857,0.789250,...,11.858286,9.655578,0.806512,0.903389,11.848628,12.140347,9.220298,0.797198,0.898193,10.623483
12,13.0,13.265907,10.458220,0.805874,0.930026,14.029323,14.860204,10.594753,0.756410,0.907167,...,13.391881,10.171909,0.802170,0.927471,18.613214,13.116327,9.485948,0.810227,0.907093,14.695148
13,14.0,12.811257,9.830699,0.552116,0.832359,10.835162,12.481310,9.517995,0.574889,0.840607,...,11.019275,8.496119,0.668649,0.835868,10.505860,12.386911,8.761436,0.581295,0.815614,10.928079
14,15.0,24.010947,15.689950,0.728833,0.940183,28.174916,48.821237,34.236867,-0.121078,0.912466,...,25.340043,16.256573,0.697982,0.918046,29.152981,24.293142,15.861590,0.722422,0.904867,27.435697
15,16.0,18.188904,15.714046,0.755564,0.877040,20.651944,35.830055,26.611683,0.051478,0.765088,...,23.476835,18.886530,0.592778,0.853508,37.886812,19.525998,15.688416,0.718305,0.871279,25.386777
16,17.0,10.833286,8.694169,0.940088,0.969788,8.830035,29.255617,23.985650,0.563070,0.862378,...,18.460974,14.851175,0.826019,0.972559,20.455583,18.936345,14.856680,0.816943,0.965402,20.214441
17,18.0,16.210249,11.523015,0.581801,0.921077,19.582330,22.090694,17.042553,0.223355,0.789856,...,11.448831,9.122105,0.791394,0.915766,10.102666,18.632032,12.252711,0.447510,0.788279,11.987232
18,19.0,10.024904,7.477991,0.931517,0.965456,11.930764,25.690898,19.189570,0.550238,0.849845,...,16.427224,12.652098,0.816112,0.950681,21.526573,14.398357,11.302586,0.858730,0.955309,17.116363
19,20.0,14.931826,9.410059,0.515837,0.866016,21.315414,15.846394,11.445751,0.454711,0.704716,...,14.183674,8.907165,0.563139,0.845257,18.361994,19.378128,13.063282,0.184565,0.848958,24.638295
20,21.0,9.843541,7.701065,0.927919,0.968332,10.033816,25.623838,21.475224,0.511562,0.928783,...,18.049404,14.445352,0.757648,0.952434,18.773125,20.006957,15.896765,0.702229,0.950931,22.643815
21,22.0,18.914170,15.961274,0.827865,0.952446,19.050654,34.122713,27.455089,0.439752,0.877747,...,27.826059,23.417589,0.627439,0.961030,33.675852,27.875522,23.151254,0.626114,0.948999,32.842751
22,23.0,8.975684,7.551262,0.886570,0.961620,6.602020,15.326803,11.762445,0.669252,0.894984,...,10.907752,7.948793,0.832481,0.948628,10.660532,12.244856,9.039524,0.788894,0.955930,13.278639
23,24.0,14.394709,12.308746,0.666722,0.842277,17.235002,20.082831,17.050934,0.351290,0.825552,...,18.645271,15.331184,0.440838,0.823203,24.843750,18.943970,16.107628,0.422778,0.779410,24.449462
24,25.0,9.437518,6.978002,0.794973,0.918560,9.320807,13.624626,11.432245,0.572688,0.841375,...,8.348194,6.274307,0.839572,0.921619,10.408186,9.213529,7.173576,0.804589,0.921553,13.663795
25,26.0,12.264311,10.297215,0.652165,0.933712,12.357459,33.475303,30.312474,-1.591410,0.738578,...,21.638362,19.008621,-0.082769,0.875593,22.447419,23.287442,20.372983,-0.254095,0.883112,24.579604
26,27.0,13.612072,10.824294,0.553811,0.756881,14.074261,33.328943,29.321551,-1.674934,0.598037,...,22.518080,20.418222,-0.221048,0.679014,24.867115,21.171367,17.978493,-0.079364,0.696498,15.294259
27,28.0,19.343489,13.190657,0.212179,0.853884,30.167217,26.742555,22.309164,-0.505787,0.626422,...,16.120856,11.613007,0.452815,0.875742,23.802038,54.610169,26.744530,-5.279208,0.818350,94.350342
28,29.0,12.014108,9.250668,0.697190,0.939203,12.881471,19.141990,16.321425,0.231292,0.803946,...,9.194517,7.136386,0.822644,0.909088,9.033982,9.469761,7.531622,0.811867,0.908646,10.746749
29,30.0,9.278657,7.244824,0.929090,0.967427,9.642171,33.296013,26.218421,0.086890,0.903959,...,12.833125,10.988170,0.864355,0.935673,10.927161,13.492695,11.697607,0.850054,0.933084,12.787859
30,31.0,16.044902,9.759153,0.956205,0.978119,22.056034,49.352894,30.514371,0.585639,0.972955,...,22.708487,15.589171,0.912274,0.960921,35.629551,22.792841,15.360462,0.911621,0.956415,37.390523
31,32.0,23.880120,20.097481,0.123193,0.857042,24.338882,15.414460,12.858249,0.634668,0.918281,...,13.702660,9.232773,0.711304,0.850558,19.993501,14.829978,9.833697,0.661848,0.819197,20.812292
32,33.0,9.214245,7.137838,0.760187,0.900633,8.867133,12.208578,9.961412,0.578999,0.796900,...,10.847393,9.568232,0.667644,0.872980,12.850402,10.889541,9.260121,0.665056,0.893631,15.862138
33,34.0,16.058226,13.277662,0.513625,0.877294,13.927815,10.535550,8.381513,0.790641,0.890221,...,10.765690,8.206003,0.781395,0.913895,15.933273,11.279223,8.166805,0.760042,0.911463,19.385442
34,35.0,28.252618,22.559199,0.524852,0.886442,32.481128,71.994812,47.187246,-2.085418,0.840422,...,35.622203,28.304405,0.244641,0.863094,39.706293,31.675769,26.217691,0.402736,0.845625,32.493239
35,36.0,10.612487,8.420242,0.878972,0.945769,12.769259,16.707406,13.938064,0.700036,0.888801,...,10.914600,8.705316,0.871983,0.944870,12.839993,12.510690,9.916156,0.831805,0.936418,15.888441
36,37.0,25.550866,21.710600,0.877459,0.964845,26.452305,76.990294,52.941172,-0.112608,0.900697,...,36.415700,29.255099,0.751087,0.922896,35.553696,36.222830,28.745045,0.753717,0.915174,37.730073
37,38.0,9.853031,7.514463,0.656949,0.838191,8.446984,22.130453,18.760329,-0.730611,0.677535,...,9.417925,7.454506,0.686578,0.856084,10.234957,8.685782,6.533721,0.733414,0.869247,10.763071
38,39.0,12.055164,8.903145,0.899758,0.949789,15.941908,22.342457,17.432513,0.655677,0.886373,...,20.579485,15.743566,0.707872,0.897397,30.676551,19.271176,14.937631,0.743834,0.900667,27.170824
39,40.0,19.549865,14.523449,0.551569,0.896148,22.016213,22.426113,16.709266,0.409913,0.906707,...,16.746777,13.308332,0.670944,0.862137,17.878213,17.138100,13.176013,0.655386,0.834403,16.697575
40,41.0,12.493841,10.052664,0.842220,0.934368,14.915449,25.649413,21.480447,0.335009,0.876818,...,20.164128,17.274116,0.589021,0.919099,28.440198,18.450574,15.736146,0.655903,0.889687,23.289495
41,42.0,11.648850,8.642364,0.693583,0.928265,10.957704,21.791444,15.471201,-0.072304,0.887562,...,14.062027,12.072447,0.553479,0.869624,11.218006,12.953278,11.212872,0.621117,0.878731,11.228769
42,43.0,20.687618,17.953281,0.570084,0.883057,18.079162,34.750963,31.692759,-0.213099,0.912650,...,23.655334,20.347986,0.437891,0.897390,17.548483,23.678693,20.580653,0.436780,0.891414,17.469670
43,44.0,10.927737,8.406674,0.802157,0.930917,12.185143,16.949377,13.091058,0.524043,0.852644,...,13.430685,10.823902,0.701148,0.905913,13.876097,14.401517,11.503450,0.656381,0.910543,17.058927
44,45.0,11.907718,10.299125,0.766699,0.919576,11.907872,35.073446,20.793391,-1.024026,0.933345,...,13.823694,11.280723,0.685582,0.920597,16.843118,12.767720,10.772128,0.731783,0.915998,14.708972
45,46.0,16.195311,12.425902,0.872022,0.982043,21.487387,32.187760,27.289019,0.494480,0.901457,...,23.347092,20.267682,0.734036,0.939711,24.785047,24.799540,21.421045,0.699915,0.894360,27.354721
46,47.0,20.768864,17.433618,0.356957,0.830122,22.781677,15.665333,10.698941,0.634158,0.878770,...,16.249990,10.391760,0.606341,0.811318,17.552154,24.977296,13.657722,0.069952,0.618383,25.252654
47,48.0,16.043305,12.029262,0.908637,0.957073,21.449219,27.516166,17.650314,0.731245,0.898487,...,19.825215,15.797244,0.860486,0.978283,25.768212,19.641046,13.043079,0.863066,0.953246,21.379578
48,49.0,18.984824,13.264342,0.935239,0.971210,27.664018,36.296995,27.760542,0.763275,0.930368,...,25.417437,15.296538,0.883918,0.948613,34.740484,21.962618,14.994701,0.913330,0.958617,31.723120
49,50.0,16.205058,11.617331,0.604264,0.860384,16.590475,14.258145,11.730638,0.693641,0.878365,...,15.677245,12.213354,0.629623,0.800729,15.948309,17.501821,13.364707,0.538394,0.734721,18.338595
50,51.0,11.615860,8.659121,0.781049,0.898350,10.613207,17.699042,15.078560,0.491672,0.947338,...,15.010916,12.203694,0.634356,0.935134,16.114717,15.547195,12.491073,0.607763,0.926885,16.794931
51,52.0,12.288652,9.469239,0.753379,0.896635,11.053810,23.434957,18.507750,0.103088,0.753261,...,11.364301,9.300805,0.789085,0.898877,15.214897,12.232898,9.733493,0.755612,0.888686,18.022027
52,53.0,28.440146,19.905758,-0.826286,0.820896,27.691534,21.773573,16.180914,-0.070446,0.881282,...,17.844945,13.318748,0.280989,0.805090,18.265516,16.874284,12.711774,0.357082,0.793214,16.622764
53,Mean,15.372218,11.877795,0.670062,0.903021,16.737971,26.274676,20.148896,0.198314,0.852438,...,17.284532,13.560887,0.643754,0.886476,20.160098,18.517937,14.008849,0.500694,0.867794,21.689734
54,Global,16.131842,11.892542,0.820235,0.912593,27.224719,30.433243,20.614464,0.360217,0.828133,...,18.855619,13.908814,0.754406,0.882890,39.481183,20.678609,14.316058,0.704622,0.858412,42.850637

In [14]:
display(summary_df[['Storm Index', 'Equation_BFE', 'Burton_BFE', 'OBM_BFE', 'DDM1_BFE', 'DDM2_BFE', 'DDM3_BFE']])

,Storm Index,Equation_BFE,Burton_BFE,OBM_BFE,DDM1_BFE,DDM2_BFE,DDM3_BFE
0,1.0,16.822423,24.722894,10.111580,13.437801,14.829997,19.966095
1,2.0,19.405386,10.861256,12.884873,19.256149,18.701587,21.927198
2,3.0,8.793067,25.950905,17.414149,20.804152,19.227867,21.447613
3,4.0,19.953851,40.213707,18.849678,21.296023,21.903819,22.014097
4,5.0,24.272886,51.929814,23.564759,27.490935,29.435293,29.757253
5,6.0,16.965733,33.556980,14.085708,12.948621,17.225424,17.003694
6,7.0,7.050362,24.195663,13.020184,17.712507,14.937157,18.509792
7,8.0,13.263640,21.390040,10.522216,9.832557,8.695989,10.319187
8,9.0,11.592131,13.250031,7.515882,11.832959,10.333607,11.559362
9,10.0,16.813556,11.885662,12.972115,19.511731,21.448999,25.359561
10,11.0,26.471161,41.157901,33.046356,33.091686,36.240329,30.591424
11,12.0,14.319192,21.477129,12.873044,13.141838,11.848628,10.623483
12,13.0,14.029323,19.124166,17.296486,18.170008,18.613214,14.695148
13,14.0,10.835162,10.479902,11.357423,11.022132,10.505860,10.928079
14,15.0,28.174916,69.872478,19.090345,23.638717,29.152981,27.435697
15,16.0,20.651944,56.058005,41.469591,32.525782,37.886812,25.386777
16,17.0,8.830035,25.751200,21.249095,25.427246,20.455583,20.214441
17,18.0,19.582330,17.686509,9.626293,10.912419,10.102666,11.987232
18,19.0,11.930764,27.396406,28.602320,21.529658,21.526573,17.116363
19,20.0,21.315414,20.374594,15.502354,18.395960,18.361994,24.638295
20,21.0,10.033816,24.355424,9.784037,23.187979,18.773125,22.643815
21,22.0,19.050654,38.575552,31.992867,35.614418,33.675852,32.842751
22,23.0,6.602020,14.221006,6.843198,12.497803,10.660532,13.278639
23,24.0,17.235002,21.703231,19.217866,19.794333,24.843750,24.449462
24,25.0,9.320807,10.734511,8.805210,12.782451,10.408186,13.663795
25,26.0,12.357459,33.502855,20.004043,24.808038,22.447419,24.579604
26,27.0,14.074261,39.044695,26.052784,25.925011,24.867115,15.294259
27,28.0,30.167217,40.280252,21.877401,17.508376,23.802038,94.350342
28,29.0,12.881471,17.312317,10.290741,10.495239,9.033982,10.746749
29,30.0,9.642171,35.709202,12.153057,12.577560,10.927161,12.787859
30,31.0,22.056034,81.616252,37.935380,32.753985,35.629551,37.390523
31,32.0,24.338882,12.628640,17.623526,20.140606,19.993501,20.812292
32,33.0,8.867133,11.242094,8.455473,14.399193,12.850402,15.862138
33,34.0,13.927815,14.942222,16.807104,18.329622,15.933273,19.385442
34,35.0,32.481128,85.959557,36.950209,32.018387,39.706293,32.493239
35,36.0,12.769259,16.361856,10.426043,16.499696,12.839993,15.888441
36,37.0,26.452305,105.366803,29.714408,39.245617,35.553696,37.730073
37,38.0,8.446984,23.052136,9.579182,9.790194,10.234957,10.763071
38,39.0,15.941908,24.476875,20.483077,22.045036,30.676551,27.170824
39,40.0,22.016213,24.748720,19.111998,16.225765,17.878213,16.697575
40,41.0,14.915449,33.326992,23.548284,23.345313,28.440198,23.289495
41,42.0,10.957704,25.451327,15.602668,10.883792,11.218006,11.228769
42,43.0,18.079162,38.107893,17.181380,17.861890,17.548483,17.469670
43,44.0,12.185143,14.001115,8.605327,16.262107,13.876097,17.058927
44,45.0,11.907872,38.527174,24.974910,12.463999,16.843118,14.708972
45,46.0,21.487387,23.246693,19.987575,28.373399,24.785047,27.354721
46,47.0,22.781677,12.422955,17.008191,17.097285,17.552154,25.252654
47,48.0,21.449219,36.490982,36.326646,23.680513,25.768212,21.379578
48,49.0,27.664018,49.354950,41.311289,25.540005,34.740484,31.723120
49,50.0,16.590475,12.945797,11.598229,17.783679,15.948309,18.338595
50,51.0,10.613207,12.845984,8.231863,18.383456,16.114717,16.794931
51,52.0,11.053810,18.070658,13.217285,18.400426,15.214897,18.022027
52,53.0,27.691534,22.186993,19.878169,15.160135,18.265516,16.622764
53,Mean,16.737971,29.814131,18.540262,19.695362,20.160098,21.689734
54,Global,27.224719,82.352301,48.429468,37.469248,39.481183,42.850637